[Debug]
LogMode=Ivan

# Overrides of usersettings.ini
#DisableTerrain=True
DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
AllowEnemyUnitsAttackPlayer=False
TestAiDetection=True

#-----------------------------

MissionStartTextDM_Taskforce2=\n\n                             Welcome back commander!\n\n  In this mission your primary objective is to find and sink a <color={*}ffc68c>Slava class cruiser</color> and establish control over a Black Sea.\n WARNING: Mission takes about 10 minutes. Do not forget to use a time compression!\n     Play with sound.
MissionStartTextDM_Taskforce1=\n\n                             Welcome back commander!\n\n  In this mission your primary objective is to obliterate a <color={*}ffc68c>US battlegroup</color> with a full strike of your Basalt missiles.\n

[Language_en]
Name=Dark Souls
Description=YOU DIED!

[Environment]
Date=1974,5,9
Time=3,30

SeaState=3     // 0 ... 12
Clouds=Clear

MapCenterLatitude=43.5
MapCenterLongitude=32.5

[Mission]
Difficulty=5

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
EnemyAIBehavior=ai/NodeCanvas/AIPlayer
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

NumberOfTaskforce1Vessels=1
NumberOfTaskforce2Vessels=5
NumberOfNeutralVessels=

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=1
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[Taskforce1Vessel1]
Type=wp_rkr_slava
RadarsActive=True

TowedArrayDeployed=False
ActiveSonarsEnabled=False
TowedDecoyDeployed=False
#RelativePositionInNM=-80,0,-50
RelativePositionInNM=-150,0,-80
Heading=-140
Telegraph=2
Waypoints=-2,0,-3|240,0,83
Attack=Taskforce2Vessel1,1,wp_ss-n-12,16
#possible variants: Template: 
#targetObject(required),
# timeOfAttack(optional. In seconds from mission start),
# ammunitionFileName(optional), numberOfShots(optional)|<next entry>


[Taskforce2Vessel1]
Type=usn_cgn_virginia
VariantReference=Random
RadarsActive=True
RelativePositionInNm=-190,0,-110
Heading=60
Telegraph=3
Waypoints=2,0,3

[Taskforce2Vessel2]
Type=usn_cg_leahy
VariantReference=Random
RadarsActive=True
RelativePositionInNm=-192,0,-111
Heading=60
Telegraph=3
Waypoints=0,0,2

[Taskforce2Vessel3]
Type=usn_dd_spruance
VariantReference=Random
RadarsActive=True
RelativePositionInNm=-188,0,-111
Heading=60
Telegraph=3
Waypoints=4,0,2

[Taskforce2Vessel4]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant31
RadarsActive=True
RelativePositionInNm=-191,0,-108
Heading=60
Telegraph=3
Waypoints=1,0,4

[Taskforce2Vessel5]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Random
RadarsActive=True
RelativePositionInNm=-187,0,-107
Heading=60
Telegraph=3
Waypoints=5,0,6


[NeutralVessel1]
Type=civ_fv_fishingboat_a
#Type=civ_ms_freighter_b
#Type=civ_ms_amra
#Type=civ_ms_irkutsk
#Type=civ_ms_ritina
#civ_ms_mercur
VariantReference=Random
RadarsActive=False
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=0,0,3
Heading=90
Telegraph=0
Waypoints=12,0,-3

[NeutralVessel2]
Type=civ_fv_fishingboat_a
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=3,0,0
Heading=0
Telegraph=0
Waypoints=-12,0,-3

[NeutralVessel3]
Type=civ_fv_fishingboat_a
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=0,0,-3
Heading=90
Telegraph=0
Waypoints=-12,0,-3

[NeutralVessel4]
Type=civ_fv_fishingboat_a
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=-3,0,0
Heading=0
Telegraph=0
Waypoints=-12,0,-3

[ ============================== Submarines ============================== ]
[Taskforce1Submarine1]
Type=wp_ssgn_echo2
#Type=usn_ssn_sturgeon
#Type=wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
#Type=wp_ssgn_echo2
VariantReference=Random

#RadarsActive=True
#TowedArrayDeployed=True
#ActiveSonarsEnabled=True
#TowedDecoyDeployed=True

RelativePositionInNm=0.8,0,-0.5
Heading=-90
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM

[Taskforce1Submarine2]
Type=wp_ssgn_charlie1
#Type=usn_ssn_sturgeon
#Type=wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
VariantReference=Variant1
#RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=-0,p,-1
Heading=0
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM

[Taskforce2Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,-200,-4
Heading=0
Telegraph=4
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=0,-200,10

[Taskforce2Submarine2]
Type=usn_ssn_los_angeles
VariantReference=Default
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,-200,-5
Heading=0
Telegraph=4
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=0,-200,10

[ =============================== Aircraft =============================== ]
[Taskforce1Aircraft1]
Type=wp_tu-95rt
RadarsActive=True
RelativePositionInNm=-20,30000,15
Heading=-90
Waypoints=-126,30000,25|-146,30000,32|4,30000,400    //X - NM, Y - feet, Z - NM

[Taskforce2Aircraft1]
Type=wp_tu-95rt
RadarsActive=True
RelativePositionInNm=-190,30000,-90
Heading=0
Waypoints=-190,30000,100