[Debug]
LogMode=Ivan

# Overrides of usersettings.ini
#DisableTerrain=True
#DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
DevModeGUIScale=1      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
TestAiDetection=False
AllowEnemyUnitsAttackPlayer=False
DisableStrategicMap=False
ContextMenuScale=1.2
ContextMenuFontSize=20
#-----------------------------

MissionStartTextDM=
\n\n                             Welcome commander!\n\n  In this mission your primary objective is to find and sink a <color={*}ffc68c>cargo vessel</color> transporting military cargo of high value from US to Norway. \n  Intelligence has information that this vessel with a small escort will be passing north of Faroe Islands.\n

[Language_en]
Name=Joint Exercise 
Description=Joint exercise of Soviet and US navy

[Environment]
Date=1982,8,12
Time=9,30

SeaState=4
Clouds=Broken_2
#Clouds=Overcast

#Weather=Rain,Fog,Thunderstorm //Supported values:Rain,Snow,Fog,Thunderstorm
Weather=Thunderstorm
#RainIntensity=500
#RainSize=1

MapCenterLatitude=36.23
MapCenterLongitude=18

[Mission]
Difficulty=1

#PlayerTaskforce=YYYYY-
#EnemyTaskforce=Taskforce1

PlayerTaskforce=Taskforce1
EnemyTaskforce=YYYYY-
EnemyAIBehavior=ai/NodeCanvas/AIPlayer
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Taskforce1_Nation=Soviet
YYYYY-_Nation=USA

Taskforce1_RelativePositionsScale=0.25
YYYYY-_RelativePositionsScale=1


Taskforce1_UI=Default
#YYYYY-_UI=Test

NumberOfTaskforce1Vessels=17
NumberOfYYYYY-Vessels=9
NumberOfNeutralVessels=

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[ ------------------------------ Player Ships ------------------------------ ]
[Taskforce1Vessel1]
Type=wp_pkr_moskva

VariantReference=Variant2

VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=False
TowedDecoyDeployed=False

RelativePositionInNM=50,0,4

Heading=-90
RandomizeCourse=-30,30
Telegraph=2
Waypoints=Turn,0,20,current|RandomTurns,20,-30/30,2/4,current,10/20|-13,0,4

[Taskforce1Vessel2]
Type=wp_bpk_kara

VariantReference=Variant3

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=3,0,1
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos


[Taskforce1Vessel3]
Type=wp_rkr_kynda

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-3,0,1
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos


[Taskforce1Vessel4]
Type=wp_em_sovremenny

VariantReference=Variant3

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=3,0,-2
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos


[Taskforce1Vessel5]
Type=wp_rkr_kresta1

VariantReference=Variant4

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-3,0,-2
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel6]
Type=wp_bpk_kashin

VariantReference=Variant7

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,3
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos


[Taskforce1Vessel7]
Type=wp_mrk_nanuchka

VariantReference=Variant3

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,3
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel8]
Type=wp_bpk_kresta2

VariantReference=Variant3

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=5,0,0
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel9]
Type=wp_bpk_udaloy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-5,0,0
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel10]
Type=wp_skr_krivak2

VariantReference=Variant2

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=7,0,5
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel11]
Type=wp_skr_krivak1

VariantReference=Variant13

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-7,0,5
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel12]
Type=wp_skr_petya2

VariantReference=Variant12

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=0,0,6
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel13]
Type=wp_bpk_kanin

VariantReference=Variant5

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=0,0,-4
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel14]
Type=wp_mpk_grisha3

VariantReference=Variant3

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=6,0,-5
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel15]
Type=wp_mpk_grisha3

VariantReference=Variant29

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-6,0,-5
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel16]
Type=wp_skr_krivak1

VariantReference=Variant3

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=3,0,-7
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel17]
Type=wp_skr_krivak2

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-3,0,-7
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[ ------------------------------ Non Player Ships ------------------------------ ]
[YYYYY-Vessel1]
Type=usn_cv_kitty_hawk

#Type=civ_ms_freighter_b
#Type=wp_bpk_kara
#Type=wp_ptg_osa1
#Type=ins_ptg_aliya
#Type=civ_fv_okean
#Type=usn_cvn_nimitz
#Type=wp_bpk_kara

VariantReference=Variant1

VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=False
TowedDecoyDeployed=False

RelativePositionInNM=30,0,-14

Heading=90
RandomizeCourse=-30,30
Telegraph=2
Waypoints=Turn,0,20,current|RandomTurns,20,-30/30,2/4,current,|-13,0,4

[YYYYY-Vessel2]
Type=usn_cg_ticonderoga

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=3,0,-1
PositionRelativeTo=YYYYY-Vessel1

Heading=Parent
Telegraph=2
Waypoints=FollowFixed,YYYYY-Vessel1,ownPos


[YYYYY-Vessel3]
Type=usn_cg_ticonderoga

VariantReference=Variant2

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-3,0,-1
PositionRelativeTo=YYYYY-Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowFixed,YYYYY-Vessel1,ownPos

[YYYYY-Vessel4]
Type=usn_cg_belknap

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,-3
PositionRelativeTo=YYYYY-Vessel1

Heading=Parent
Telegraph=2
Waypoints=FollowFixed,YYYYY-Vessel1,ownPos


[YYYYY-Vessel5]
Type=usn_dd_spruance

VariantReference=Variant2

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,-3
PositionRelativeTo=YYYYY-Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowFixed,YYYYY-Vessel1,ownPos

[YYYYY-Vessel6] #Gary FFG-51
Type=usn_ffg_oliver_hazard_perry

VariantReference=Variant41

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=6,0,-2
PositionRelativeTo=YYYYY-Vessel1

Heading=Parent
Telegraph=2
Waypoints=FollowFixed,YYYYY-Vessel1,ownPos


[YYYYY-Vessel7] #Reuben James FFG-57
Type=usn_ffg_oliver_hazard_perry

VariantReference=Variant47

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-6,0,-2
PositionRelativeTo=YYYYY-Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowFixed,YYYYY-Vessel1,ownPos

[YYYYY-Vessel8]
Type=usn_dd_gearing

VariantReference=Variant37

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=5,0,-5
PositionRelativeTo=YYYYY-Vessel1

Heading=Parent
Telegraph=2
Waypoints=FollowFixed,YYYYY-Vessel1,ownPos


[YYYYY-Vessel9]
Type=usn_ddg_kidd

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-5,0,-5
PositionRelativeTo=YYYYY-Vessel1

Heading=Parent
Telegraph=3
Waypoints=FollowFixed,YYYYY-Vessel1,ownPos


[NeutralVessel1]
Type=civ_ms_freighter_b
#Type=civ_fv_fishingboat_a
#Type=civ_ms_freighter_b
#Type=civ_ms_amra
#Type=civ_ms_irkutsk
#Type=civ_ms_ritina
#civ_ms_mercur
VariantReference=Variant1
RadarsActive=False
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=0,0,3
Heading=90
Telegraph=0
Waypoints=12,0,-3

[NeutralVessel2]
Type=civ_fv_fishingboat_a
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=3,0,0
Heading=0
Telegraph=0
Waypoints=-12,0,-3

[NeutralVessel3]
Type=civ_fv_fishingboat_a
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=0,0,-3
Heading=90
Telegraph=0
Waypoints=-12,0,-3

[NeutralVessel4]
Type=civ_fv_fishingboat_a
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=-3,0,0
Heading=0
Telegraph=0
Waypoints=-12,0,-3

[ ============================== Submarines ============================== ]
[Taskforce1Submarine1]
Type=usn_ssn_sturgeon
#Type=wp_ssn_alfa
#Type=wp_ssgn_oscar1
#Type=wp_ssgn_charlie2
#Type=wp_ssgn_oscar1
#Type=wp_ssgn_echo2
#Type=usn_ssn_sturgeon
#Type=wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
#Type=wp_ssgn_echo2
VariantReference=Variant1
#VariantReference=Random

#RadarsActive=True
#TowedArrayDeployed=True
ActiveSonarsEnabled=True
#TowedDecoyDeployed=True

#RelativePositionInNm=0.8,-300,-0.5
#RelativePositionInNM=0,p,0
RelativePositionInNM=-30,p,-1
Heading=90
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM

[Taskforce1Submarine2]
Type=wp_ssgn_charlie1
#Type=usn_ssn_sturgeon
#Type=wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
VariantReference=Variant1
#RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=-0,p,-1
Heading=0
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM

[Taskforce2Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,-200,-4
Heading=0
Telegraph=0
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=0,-200,10

[Taskforce2Submarine2]
Type=usn_ssn_los_angeles
VariantReference=Default
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,-200,-5
Heading=0
Telegraph=4
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=0,-200,10

[NeutralSubmarine1]
Type=usn_ssn_los_angeles
VariantReference=Default
RelativePositionInNm=0,-200,-5
Heading=0
Telegraph=4
Waypoints=0,-200,10
[ =============================== Aircraft =============================== ]
[Taskforce1Aircraft1]
Type=usn_a-7e
#Type=usn_a-6e
#Type=usn_f-4j
#Type=wp_tu-16k
#Type=usn_f-4j

#Type=wp_tu-22m2
#Type=wp_mig-23mld
#Type=usn_f-14a
#Type=wp_yak-38
#Type=iriaf_f-4e
#Type=wp_il-38
#Type=usn_ea-6b
#Type=usn_sh-2f

#Type=usn_f-14a
#wp_tu-22m2
#usn_f-14a
#usn_a-7e
#wp_yak-38
#iriaf_f-4e
SquadronReference=Squadron18
RadarsActive=True
#HomeBase=Taskforce1Vessel1
#LoadoutVariant=Strike
#LoadoutVariant=Loadout1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=0.0,9500.0,-50.0
RelativePositionInNm=-2.9,1000,0
Heading=90
Waypoints=225,1000,0|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM

[Taskforce1Aircraft2]
Type=usn_a-7e
#Type=iriaf_f-4e
#Type=usn_e-2c
#Type=wp_mig-27
SquadronReference=Squadron1
LoadoutVariant=Strike
RelativePositionInNm=-6,1400,4.05
Heading=90
Waypoints=225,1400,16|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM


[Taskforce1Aircraft3]
Type=iriaf_f-4e
SquadronReference=Squadron2
LoadoutVariant=IronHand
RelativePositionInNm=-4,1000,-0.05
Heading=90
Waypoints=25,1000,-0.05|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM


[Taskforce1Aircraft4]
Type=iriaf_f-4e
SquadronReference=Random
LoadoutVariant=SEAD
RelativePositionInNm=-6,1000,-0.05
Heading=90
Waypoints=25,1000,-0.05|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM

[Taskforce2Aircraft1]
Type=usn_a-6e
SquadronReference=Squadron1
//LoadoutVariant=Backup
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=0,10000,40
RelativePositionInNm=45,1000,8
Heading=90
Waypoints=Course,90,25,1234

[Taskforce2Aircraft2]
Type=iriaf_f-4e
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=0,10000,40
RelativePositionInNm=-8,1000,0
Heading=90
Waypoints=25,1000,0|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM

[NeutralAircraft1]
Type=usn_f-4j
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=-2.9,5000,7
Heading=220

[ ============================== Helicopters ============================= ]
[Taskforce1Helicopter1]
Type=wp_ka-25
#Type=usn_sh-2f
#Type=wp_ka-27
#Type=usn_sh-3h
#Type=wp_ka-25
SquadronReference=Squadron1
#LoadoutVariant=Loadout2
RadarsActive=True
HomeBase=Taskforce1Vessel1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=-10,4000,0
//RelativePositionInNm=2,50,22
RelativePositionInNm=-12,1400,2
//OverrideSpawnHeightUnity=12.3456
Heading=90
Waypoints=-7,200,0.08|10,100,1    //X - NM, Y - feet, Z - NM

[Taskforce1Helicopter2]
Type=wp_ka-27
#wp_ka-27
SquadronReference=Squadron2
#LoadoutVariant=Loadout3
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=-1,40,-4
Heading=90
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM

[Taskforce1Helicopter3]
Type=usn_sh-2f
SquadronReference=Squadron3
LoadoutVariant=Loadout1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-5,3000.0,0
Heading=90

[Taskforce2Helicopter1]
Type=usn_sh-2f
SquadronReference=Squadron2
//LoadoutVariant=Loadout1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=6,16000,01.08
RelativePositionInNM=-1,400,-4.005
Heading=90
#Waypoints=30,20,10

[Taskforce2Helicopter2]
Type=usn_sh-2f
SquadronReference=Squadron2
LoadoutVariant=Loadout2
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=-2,400,-3.01
Heading=90

[Taskforce2Helicopter3]
Type=usn_sh-2f
SquadronReference=Squadron3
LoadoutVariant=Loadout3
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=-2,400,-1.015
Heading=90

[Taskforce2Helicopter4]
Type=usn_sh-2f
SquadronReference=Squadron4
LoadoutVariant=Loadout3
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=0,40,-5
Heading=90

[NeutralHelicopter1]
Type=wp_ka-27
SquadronReference=Squadron1
RelativePositionInNm=-3,1400,3
Heading=90