[Language_en]
Name=日本語化パック(作業用)
Description=ゲームに日本語の言語サポートを追加します。

[Language_de]
Name=日本語化パック(作業用)
Description=ゲームに日本語の言語サポートを追加します。

[Language_ru]
Name=日本語化パック(作業用)
Description=ゲームに日本語の言語サポートを追加します。

[Language_cn]
Name=日本語化パック(作業用)
Description=ゲームに日本語の言語サポートを追加します。

[Language_ja]
Name=日本語化パック(作業用)
Description=ゲームに日本語の言語サポートを追加します。

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.4.8