[Debug]
LogMode=Ivan
AllowEnemyUnitsAttackPlayer=True
TestAiDetection=True
MissionStartTextDM=\n*This message will not appear in the final game, it is solely to convey the synopsis for the demo video.\n\n June, 1986 - The North Atlantic\n\nFollowing a massive blow on the Northern Front, Soviet submarines and Backfire bombers have crossed into the open Atlantic virtually unopposed. Instructed to prevent American reinforcements from landing in Europe, PACT submarines and aircraft make daily attacks on trans-Atlantic convoys. As NATO leadership scrambles to move submarines into the GIUK Gap to prevent further crossings into the Atlantic, the job of protecting the convoys on their dangerous two week voyage falls to the sailors of American tin cans.\n

[Language_en]
Name=Convoy under fire
Description=June, 1986 - The North Atlantic\n\nFollowing a massive blow on the Northern Front, Soviet submarines and Backfire bombers have crossed into the open Atlantic virtually unopposed. Instructed to prevent American reinforcements from landing in Europe, PACT submarines and aircraft make daily attacks on trans-Atlantic convoys. As NATO leadership scrambles to move submarines into the GIUK Gap to prevent further crossings into the Atlantic, the job of protecting the convoys on their dangerous two week voyage falls to the sailors of American tin cans.\n

[Environment]
Date=1986,6,9
Time=9,30

SeaState=5     // 0 ... 12
Clouds=Broken

Weather=Rain,Fog,Thunderstorm 
RainIntensity=500

MapCenterLatitude=45
MapCenterLongitude=-36

[Mission]
Difficulty=2

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
EnemyAIBehavior=ai/NodeCanvas/AIPlayer
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Taskforce1_Nation=USA
Taskforce2_Nation=Soviet

NumberOfTaskforce1Vessels=8
NumberOfTaskforce2Vessels=
NumberOfNeutralVessels=
NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=2
NumberOfNeutralSubmarines=
NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=4
NumberOfNeutralAircraft=
NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

#Single
[Taskforce1Vessel1] #Pharris FF-1094
Type=usn_ff_knox
VariantReference=Variant43
RadarsActive=True
LoadoutVariant=CIWS
RelativePositionInNM=0,0,20
Heading=90
Telegraph=3
Waypoints=1120,0,20
TowedArrayDeployed=True

#Northern row
[Taskforce1Vessel2] #Gary FFG-51
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant41
RelativePositionInNm=-1,0,0
Heading=90
Telegraph=3
Waypoints=1120,0,0

[Taskforce1Vessel3] #Reuben James FFG-57
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant47
RelativePositionInNm=-3,0,0
Heading=90
Telegraph=3
Waypoints=1120,0,0
//Attack=Taskforce1Vessel6,2,usn_rgm-84,2

#Middle row
[Taskforce1Vessel4] #Merchant
Type=civ_ms_bulk  //civ_ms_freighter_b
VariantReference=Random
RelativePositionInNm=0,0,-1
Heading=90
Telegraph=3
Waypoints=120,0,-1

[Taskforce1Vessel5] #Merchant
Type=civ_ms_roro_a
VariantReference=Random
RelativePositionInNm=-2,0,-1
Heading=90
Telegraph=3
Waypoints=1120,0,-1

[Taskforce1Vessel6] #Merchant
Type=civ_ms_seabee
VariantReference=Random
RelativePositionInNm=-4,0,-1
Heading=90
Telegraph=3
Waypoints=1120,0,-1

#Southern row
[Taskforce1Vessel7] #Merchant
Type=civ_ms_act_1
VariantReference=Random
RelativePositionInNm=-1,0,-2
Heading=90
Telegraph=3
Waypoints=1120,0,-2

[Taskforce1Vessel8] #Merchant
Type=usn_lst_newport
VariantReference=Random
RelativePositionInNm=-3,0,-2
Heading=90
Telegraph=3
Waypoints=1120,0,-2
#================================================================================ Submarines ================================================================================
[Taskforce1Submarine1]
Type=wp_ssn_victor3
VariantReference=Variant2
RelativePositionInNm=8,-200,28
Heading=192
Telegraph=2
Waypoints=2,-200,0|2,-400,2|-2,200,2|-2,200,-2|2,200,-2|2,200,2|-2,200,2||-2,200,-2|0,-200,1    //X - NM, Y - feet, Z - NM


[Taskforce2Submarine1]
Type=wp_ssn_victor3
VariantReference=Random
RelativePositionInNm=8,-200,28
Heading=192
Telegraph=2
Waypoints=2,-200,0|2,-400,2|-2,200,2|-2,200,-2|2,200,-2|2,200,2|-2,200,2||-2,200,-2|0,-200,1    //X - NM, Y - feet, Z - NM
Attack=Taskforce1Vessel1,310|Taskforce1Vessel1,310
TowedArrayDeployed=True

[Taskforce2Submarine2]
Type=wp_ssgn_charlie2
VariantReference=Random
RelativePositionInNm=0,-200,1
Heading=270
Telegraph=0
Waypoints=2,-200,0|2,-400,2|-2,200,2|-2,200,-2|2,200,-2|2,200,2|-2,200,2||-2,200,-2|0,-200,1    //X - NM, Y - feet, Z - NM
TowedArrayDeployed=True

[Taskforce2Submarine3]
Type=wp_ssn_victor3
VariantReference=Variant2
RelativePositionInNm=0,-200,1
Heading=270
Telegraph=0
Waypoints=2,-200,0|2,-400,2|-2,200,2|-2,200,-2|2,200,-2|2,200,2|-2,200,2||-2,200,-2|0,-200,1    //X - NM, Y - feet, Z - NM
TowedArrayDeployed=True

#================================================================================ Aircraft ================================================================================
[Taskforce1Aircraft1] # TEST
Type=wp_tu-22m2
SquadronReference=Squadron1
RelativePositionInNm=70,20000,122
Heading=210
Waypoints=65,20000,114|700,20000,1220
Attack=Taskforce1Vessel8,15,wp_as-4,3|Taskforce1Vessel8,15,wp_as-4|Taskforce1Vessel8,15|Taskforce1Vessel8  //<- possible variants. Template: targetObject(required), timeOfAttack(optional. In seconds from mission start), ammunitionFileName(optional), numberOfShots(optional)|<next entry>

#Turn away time - 65 sec
[Taskforce2Aircraft1]
Type=wp_tu-22m2
SquadronReference=Squadron1
LoadoutVariant=LongRange
RelativePositionInNm=70,20000,122
Heading=210
Waypoints=65,20000,114|700,20000,1220
Attack=Taskforce1Vessel8,25,wp_as-4

[Taskforce2Aircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron2
LoadoutVariant=LongRange
RelativePositionInNm=69.5,20000,122.5
Heading=210
Waypoints=64.5,20000,114.5|700,20000,1220
Attack=Taskforce1Vessel6,25,wp_as-4

[Taskforce2Aircraft3]
Type=wp_tu-22m2
SquadronReference=Squadron3
LoadoutVariant=LongRange
RelativePositionInNm=72,20000,122
Heading=210
Waypoints=67,20000,114|700,20000,1220
Attack=Taskforce1Vessel7,55,wp_as-4

[Taskforce2Aircraft4]
Type=wp_tu-22m2
SquadronReference=Squadron4
LoadoutVariant=LongRange
RelativePositionInNm=71.5,20000,122.5
Heading=210
Waypoints=66.5,20000,114.5|700,20000,1220
Attack=Taskforce1Vessel5,55,wp_as-4
