[Debug]
LogMode=Ivan
DevModeGUIScale=1      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
AllowEnemyUnitsAttackPlayer=True
#FullscreenStrategicMap=True
ContextMenuScale=1.2
ContextMenuFontSize=20
#-----------------------------

#MissionStartTextDM=

[Language_en]
Name=Hide and Seek
Description=3 Soviet vessels vs 3 Nato.Ships are randomly spawned and have to find eachother.

[Environment]
Date=1982,4,2
Time=12,00

SeaState=2
Clouds=Broken

MapCenterLatitude=27
MapCenterLongitude=-46


[Mission]
Difficulty=2

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

EnemyAIPlayerBehaviourPath=ai/NodeCanvas/AIPlayer
EnemyAIUnitBehaviourPath=ai/NodeCanvas/AIUnit
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

Taskforce1_UI=Default
Taskforce2_UI=Test


NumberOfTaskforce1LandUnits=

NumberOfTaskforce1Vessels=3
NumberOfTaskforce2Vessels=3
NumberOfNeutralVessels=15

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=1
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[ ================================ Vessels =============================== ]
[Taskforce1Vessel1]
Type=wp_bpk_udaloy,wp_bpk_kara,wp_bpk_kresta2
VariantReference=Random

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,30
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

[Taskforce1Vessel2]
Type=wp_em_sovremenny,wp_rkr_kresta1,wp_rkr_kynda
VariantReference=Random

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=1,3
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

[Taskforce1Vessel3]
Type=wp_ptg_osa1,wp_ptg_osa2,wp_mrk_nanuchka
VariantReference=Random

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=1,3
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

[------------------------------------------]
[Taskforce2Vessel1]
Type=usn_cg_ticonderoga,usn_cg_belknap
VariantReference=Random

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,30
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

[Taskforce2Vessel2]
Type=usn_dd_spruance,usn_ddg_adams_late
VariantReference=Random

RandomSpawnCenter=Taskforce2Vessel1
RandomSpawnRange=5,10
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

[Taskforce2Vessel3]
Type=usn_ffg_oliver_hazard_perry,usn_ff_garcia,usn_dd_gearing
RandomSpawnCenter=Taskforce2Vessel1
RandomSpawnRange=5,10
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

[------------------------------------------]
[NeutralVessel1]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel2]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel3]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel4]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel5]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel6]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel7]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel8]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel9]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel10]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel11]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel12]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel13]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel14]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[NeutralVessel15]
SpawnChance=0.75
Type=civ_fv_fishingboat_a,civ_fv_okean,civ_fv_sidetrawler,civ_ms_act_1,civ_ms_amra,civ_ms_andizhan,civ_ms_bulk,civ_ms_c7s68,civ_ms_c8,civ_ms_car_carrier_a,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_irkutsk,civ_ms_kommunist,civ_ms_mairangi_bay,civ_ms_mercur,civ_ms_metallurg_anosov,civ_ms_murom,civ_ms_poltava,civ_ms_ritina,civ_ms_roro_a,civ_ms_roro_b,civ_ms_seabee,civ_ms_slavyansk,civ_ms_super_p

RandomSpawnCenter=0,0,0
RandomSpawnRange=15,50
RandomSpawnDirection=-179,180

Heading=Random
Telegraph=3

Waypoints=RandomTurns,20,-30/30,5

[ ============================== Submarines ============================== ]
[------------------------------------------]
[------------------------------------------]
[ =============================== Aircraft =============================== ]
[Taskforce1Aircraft1]
Type=wp_mig-17
SquadronReference=Default
RadarsActive=True
HomeBase=
RelativePositionInNm=0,400,0
Heading=30
[------------------------------------------]
[------------------------------------------]
[ ============================== Helicopters ============================= ]
[------------------------------------------]
[------------------------------------------]
[ ============================== Land Units ============================== ]
[------------------------------------------]
[------------------------------------------]
