[Debug]
LogMode=Ivan
DevModeGUIScale=1      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
AllowEnemyUnitsAttackPlayer=True
#FullscreenStrategicMap=True
ContextMenuScale=1.2
ContextMenuFontSize=20
#-----------------------------

#MissionStartTextDM=

[Language_en]
Name=Ice Fortress
Description=NATO fleet must defend Iceland from Soviet landing attempt

[Environment]
Date=1984,11,8
Time=9,30

SeaState=4
Clouds=Broken

lat = 63.99
#-180.13,1,-361.431

#Iceland South
MapCenterLatitude=66.5
MapCenterLongitude=-21

#Iceland South
MapCenterLatitude=65
MapCenterLongitude=-21

[Mission]
Difficulty=2

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=USA
Taskforce2_Nation=Soviet

Taskforce1_UI=Default
Taskforce2_UI=Test


#Taskforce1_NumberOfFormations=1
#Taskforce1_Formation1=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel6|TF Kiev|LineAstern|0.5
#Taskforce1_Formation_2=Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6



NumberOfTaskforce1LandUnits=1

NumberOfTaskforce1Vessels=10
NumberOfTaskforce2Vessels=
NumberOfNeutralVessels=

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=2
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[ ================================ Vessels =============================== ]
[Taskforce1Vessel1]
Type=usn_cgn_virginia
VariantReference=Variant4
RelativePositionInNM=-95,0,-139
Heading=-45
Telegraph=0

[Taskforce1Vessel2]
Type=usn_cgn_virginia
VariantReference=Variant3
RelativePositionInNM=-93,0,-135
Heading=-45
Telegraph=0


[Taskforce1Vessel3]
Type=usn_dd_spruance
VariantReference=Variant29
RelativePositionInNM=-94,0,-137
Heading=-45
Telegraph=0

[Taskforce1Vessel4]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant38
RelativePositionInNM=-96,0,-135
Heading=-45
Telegraph=0

[Taskforce1Vessel5]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant39
RelativePositionInNM=-97,0,-137
Heading=-45
Telegraph=0

[Taskforce1Vessel6]
Type=usn_ff_knox
VariantReference=Variant39
RelativePositionInNM=-99,0,-126
Heading=-139
Telegraph=3
Waypoints=-117,0,-147|-120,0,-197|-40,0-205|-170,0-205|-120,0-200

[Taskforce1Vessel7]
Type=usn_cg_leahy
VariantReference=Variant8
RelativePositionInNM=172,0,-40
Heading=-45
Telegraph=0

[Taskforce1Vessel8]
Type=usn_ddg_adams_late
VariantReference=Variant9
RelativePositionInNM=168,0,-37
Heading=-45
Telegraph=0

[Taskforce1Vessel9]
Type=usn_ff_garcia
VariantReference=Variant2
RelativePositionInNM=166,0,-35
Heading=-45
Telegraph=0

[Taskforce1Vessel10]
Type=usn_ff_garcia
VariantReference=Variant7
RelativePositionInNM=163,0,-32
Heading=-45
Telegraph=0

[------------------------------------------]
[Taskforce2Vessel1]
Type=wp_mrk_nanuchka
#Type=civ_ms_freighter_b
#Type=wp_bpk_kara
#Type=wp_ptg_osa1
#Type=ins_ptg_aliya
#Type=civ_fv_okean
#Type=usn_cvn_nimitz
#Type=wp_bpk_kara
VariantReference=Variant2
//VariantReference=Random
#RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=-4,0,-1
Heading=0
Telegraph=0
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=20,0,24

[------------------------------------------]
[NeutralVessel1]
Type=civ_ms_freighter_b
VariantReference=Variant1
RadarsActive=False
RelativePositionInNm=15,0,3
Heading=90
Telegraph=0
Waypoints=12,0,-3

[ ============================== Submarines ============================== ]
[Taskforce1Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Variant1
#Random

#RadarsActive=True
#TowedArrayDeployed=True
ActiveSonarsEnabled=True
#TowedDecoyDeployed=True

#RelativePositionInNm=0.8,-300,-0.5
#RelativePositionInNM=0,p,0
RelativePositionInNM=-5,-100,-1
Heading=90
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM

[------------------------------------------]
[Taskforce2Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,-200,-4
Heading=0
Telegraph=0
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=0,-200,10

[------------------------------------------]
[NeutralSubmarine1]
Type=usn_ssn_los_angeles
VariantReference=Default
RelativePositionInNm=0,-200,-5
Heading=0
Telegraph=4
Waypoints=0,-200,10
[ =============================== Aircraft =============================== ]
[Taskforce1Aircraft1]
Type=wp_tu-16k

SquadronReference=Squadron1
LoadoutVariant=LongRange

RelativePositionInNm=-15,30000,208
Heading=191

#AttackPos:-26,30000,139  Turn away =870sec

Waypoints=Turn,0,40,30000,785|770,30000,275

Attack=Taskforce1LandUnit1,780,wp_as-2

[Taskforce1Aircraft1]
Type=wp_tu-22m2

SquadronReference=Squadron1
LoadoutVariant=LandStrikeLongRange

RelativePositionInNm=-15,30000,208
Heading=191

AttackPos:-26,30000,139  Turn away =870sec

Waypoints=-26,30000,139|770,30000,275
Attack=Taskforce1LandUnit1,780,wp_as-4b

[Taskforce1Aircraft2]
Type=usaf_f-15c

SquadronReference=Squadron1
LoadoutVariant=Patrol

RelativePositionInNm=-15,30000,170
Heading=0

Waypoints=Turn,0,10,30000

[------------------------------------------]
[Taskforce2Aircraft1]
Type=usn_f-4j
SquadronReference=Squadron12
RadarsActive=True
LoadoutVariant=Attack

RelativePositionInNm=10,2000,-13.8
Heading=180
Waypoints=Turn,0,4,current
Attack=Taskforce1LandUnit1,0,usn_mk-82

[------------------------------------------]
[NeutralAircraft1]
Type=civ_707
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=-2.9,5000,7
Heading=220

[ ============================== Helicopters ============================= ]
[Taskforce1Helicopter1]
MissionTarget=Protect
Type=wp_ka-25
#Type=usn_sh-2f
#Type=wp_ka-27
#Type=usn_sh-3h
#Type=wp_ka-25
SquadronReference=Squadron1
#LoadoutVariant=Loadout2
RadarsActive=True
HomeBase=Taskforce1Vessel1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=-10,4000,0
RelativePositionInNm=-0,1000,-1
#RelativePositionInNm=-12,1400,2
//OverrideSpawnHeightUnity=12.3456
Heading=90
#Waypoints=FollowLoose,Taskforce1Aircraft1,2,0,1
#Waypoints=Turn,0,20,current
#Waypoints=-7,200,0.08|10,100,1    //X - NM, Y - feet, Z - NM

[------------------------------------------]
[Taskforce2Helicopter1]
MissionTarget=Destroy
Type=usn_sh-2f
SquadronReference=Squadron2


RelativePositionInNM=-1,400,-4.005
Heading=90


[------------------------------------------]
[NeutralHelicopter1]
Type=wp_ka-27
SquadronReference=Squadron1
RelativePositionInNm=-3,1400,3
Heading=90

[ ============================== Land Units ============================== ]
[--Taskforce1LandUnit11]
Type=wp_sam_site_sa-5
VariantReference=Variant1

RadarsActive=True

RelativePositionInKm=0,869,-30
OverrideSpawnHeightUnity=3.95
Heading=0

[------------------------------------------]
[Taskforce1LandUnit1]
Type=wp_large_pvo_airbase
VariantReference=Variant1
RelativePositionInNm=-97.45,242,-151.18
#RelativePositionInNm=-97.45,242,-60.55
OverrideSpawnHeightUnity=1

CustomAirGroup=True
usaf_f-15c=Default,12
usn_f-14a=Squadron5,1|Squadron7,10
usn_a-7e=Squadron7,3|Squadron8,4
usn_a-6e=Squadron2,8
usn_e-2c=Squadron6,2
usn_ea-6b=Squadron1,3
usn_p-3c=Default,3