[Debug]
LogMode=None
AllowEnemyUnitsAttackPlayer=True
TestAiDetection=True
MissionStartTextDM=Interception, soutch of Iceland

[Mission]
Difficulty=3

[Language_en]
Name=Interception, south of Iceland
Description=2 F-14 vs 4 Tu-22s vs fleet

[Environment]
Date=1983,5,10
Time=16,30

SeaState=2     // 0 ... 12
Clouds=broken_2	//scattered_2 //broken	//scattered_1 //Clear

MapCenterLatitude=63.3	//31.72
MapCenterLongitude=-17.97		//33.16

NumberOfTaskforce1Vessels=3
NumberOfTaskforce2Vessels=0
NumberOfNeutralVessels=0
NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=
NumberOfTaskforce1Aircraft=2
NumberOfTaskforce2Aircraft=0
NumberOfNeutralAircraft=4
NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
EnemyAIBehavior=ai/NodeCanvas/AIPlayer
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Taskforce1_Nation=US
Taskforce2_Nation=Soviet


[Taskforce1Vessel1]
MissionTarget=Protect
Type=rn_dd_battle
//wp_pt_shershen-e
//ir_ptg_combattante_II
VariantReference=
RadarsActive=True
RelativePositionInNM=-40,0,0
Heading=90
Telegraph=1
Waypoints=25,0,-25

[Taskforce1Vessel2]
MissionTarget=Protect
Type=usn_ddg_adams_late
//wp_pt_shershen
//usn_dd_spruance
VariantReference=
RelativePositionInNm=-41.5,0,0.5
Heading=90
Telegraph=1
Waypoints=26,0,-26

[Taskforce1Vessel3]
Type=usn_ae_kilauea
//wp_ptg_osa1
VariantReference=
RelativePositionInNm=-42,0,-1
Heading=90
Telegraph=1
Waypoints=26.3,0,-26.3

[Taskforce1Vessel3]
Type=civ_ms_amra
//wp_ptg_osa1
VariantReference=
RelativePositionInNm=-43,0,-2
Heading=90
Telegraph=1
Waypoints=27.3,0,-26.3

[---------- Taskforce2 Vessels----------]
[Taskforce2Vessel1]
MissionTarget=Destroy
Type=usn_dd_spruance
//ins_ptg_saar2
//rn_dd_c-class
//usn_dd_spruance
VariantReference=
RelativePositionInNm=-6,0,-2
Heading=90
Telegraph=2
Waypoints=600,0,-15

[Taskforce2Vessel2]
MissionTarget=Destroy
Type=usn_ddg_adams_late
//usn_ffg_knox
VariantReference=
RelativePositionInNm=-7.2,0,-2
Heading=90
Telegraph=2
Waypoints=599,0,-11

[Taskforce2Vessel3]
SType=usn_ffg_oliver_hazard_perry
//ins_pt_saar
//wp_pt_shershen
VariantReference=
RelativePositionInNm=-9.5,0,-4
Heading=90
Telegraph=2
Waypoints=603,0,-15

[Taskforce2Vessel4]
MissionTarget=Destroy
Type=usn_ae_kilauea
//civ_ms_freighter_b
VariantReference=Variant1
RelativePositionInNm=-11,0,-4
Heading=90
Telegraph=3
Waypoints=595,0,-19

[---------- Neutral Vessels----------]
[NeutralVessel1]
#Italy goes from south west to east+
Type=civ_ms_mercur
VariantReference=Variant4
RelativePositionInNm=-42,0,-2
Heading=90
Telegraph=3
Waypoints=220,0,-3|245,0,-3

[NeutralVessel2]
#UK goes from north west to east+
Type=civ_ms_amra
VariantReference=Variant12
RelativePositionInNm=-4,0,-2
Heading=55
Telegraph=3
Waypoints=-40,0,-2|-25,0,15|99,0,15|500,0,500

[NeutralVessel3]
#UK goes from south west to east+
Type=civ_ms_amra
VariantReference=Variant12
RelativePositionInNm=-10,0,-15
Heading=71
Telegraph=3
Waypoints=-20,0,-23|15,0-20|500,0,500

[NeutralVessel4]
#Italy goes from northeast to west+
Type=civ_ms_ritina
VariantReference=Variant12
RelativePositionInNm=16,0,10
Heading=246
Telegraph=3
Waypoints=-120,0,-40|-150,0,-500

[NeutralVessel5]
#Soviet, comes from north east to soutwest
Type=civ_ms_mercur
VariantReference=Variant1
RelativePositionInNm=18,0,12
Heading=244
Telegraph=5
Waypoints=-120,0,-40|-150,0,-500
#================================================================================ Submarines ================================================================================

#================================================================================ Aircraft ================================================================================
[Taskforce1Aircraft1]
Type=usn_f-14a
//usn_f-14a
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=0,15000,0
Heading=30
Waypoints=30,15000,10|10,12000,-10|-20,15000,-20    //X - NM, Y - feet, Z - NM

[Taskforce1Aircraft2]
Type=usn_f-14a
//usn_f-14a
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=-0.3,15000,-0.3
Heading=30
Waypoints=30.3,15000,10.3|10.3,12000,-10.3|-20.3,15000,-20.3    //X - NM, Y - feet, Z - NM

[NeutralAircraft1]	//[Taskforce2Aircraft1]
Type=wp_tu-22m2
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=5,18000,9
Heading=190
Telegraph=3
Waypoints=-40,13000,0|40,18000,120

[NeutralAircraft2] //[Taskforce2Aircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=5.2,18000,9.2
Heading=190
Telegraph=3
Waypoints=-40.2,13000,0.2|40.2,18000,120.2

[NeutralAircraft3]	//[Taskforce2Aircraft3]
Type=wp_tu-22m2
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=5.4,18000,9.4
Heading=190
Telegraph=3
Waypoints=-40.4,13000,0.4|40.4,18000,120.4

[NeutralAircraft4]	//[Taskforce2Aircraft4]
Type=wp_tu-22m2
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=5.6,18000,9.6
Heading=190
Telegraph=3
Waypoints=-40.6,13000,0.6|40.6,18000,120.6

[NeutralAircraft5]
Type=wp_tu-22m2
SquadronReference=Squadron2
RadarsActive=True
RelativePositionInNm=-30.05,14000,9.05
Heading=90
Telegraph=3
Waypoints=600.05,10000,9.05

#================================================================================ Helicopters ================================================================================
