[Debug]
LogMode=Ivan

# Overrides of usersettings.ini
#DisableTerrain=True
DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
#DevModeGUIScale=1.5      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons

DisableStrategicMap=False
ContextMenuScale=1.2
ContextMenuFontSize=20
#-----------------------------
TestAiDetection=True
AllowEnemyUnitsAttackPlayer=True
EnemyWeaponStatus=Free

MissionStartTextDM=
\n\n                             Welcome commander!\n\n  In this mission your primary objective is to find and sink a <color={*}ffc68c>cargo vessel</color> transporting military cargo of high value from US to Norway. \n  Intelligence has information that this vessel with a small escort will be passing north of Faroe Islands.\n

[Language_en]
Name=Pacific Patrol
Description=3 NATO ships were sighted near Kuril islands. Command belives they are support to a submarine deployment in the Sea of Okhotsk. Soviet squadron was sent to investigate. \n\nTake caution: You well equipped to deal with the enemy, but also very vulnerable.

[Environment]
Date=1985,5,9
Time=9,30

SeaState=3
Clouds=Broken

Weather=Rain,Fog,Thunderstorm //Supported values:Rain,Snow,Fog,Thunderstorm
#RainIntensity=500
#RainSize=1

MapCenterLatitude=50
MapCenterLongitude=150


[Mission]
Difficulty=4

PlayerTaskforce=Taskforce2
EnemyTaskforce=Taskforce1
EnemyAIBehavior=ai/NodeCanvas/AIPlayer
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

Taskforce1_UI=Default
#Taskforce2_UI=Test
MapInitialZoom=8.5

NumberOfTaskforce1LandUnits=

NumberOfTaskforce1Vessels=5
NumberOfTaskforce2Vessels=3
NumberOfNeutralVessels=16

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=1
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[------------------------------ Taskforce1 Ships ------------------------------]
[Taskforce1Vessel1]
Type=wp_bpk_kanin

VariantReference=Random
VisualSystemsOn=True
RadarsActive=False
TowedArrayDeployed=False
ActiveSonarsEnabled=False
TowedDecoyDeployed=False

Heading=45
RandomizeCourse=-45,45

Telegraph=3
Waypoints=Turn,0,20,0

[Taskforce1Vessel2]
Type=wp_mrk_nanuchka

VariantReference=Random
RadarsActive=False

RelativePositionInNm=-1,0,3
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=Turn,0,20,0

[Taskforce1Vessel3]
Type=wp_ptg_osa1

VariantReference=Random
RadarsActive=False

RelativePositionInNm=1,0,3
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=Turn,0,20,0

[Taskforce1Vessel4]
Type=wp_skr_petya2

VariantReference=Random
RadarsActive=False

RelativePositionInNm=-3,0,5
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=Turn,0,20,0

[Taskforce1Vessel5]
Type=wp_mpk_grisha3

VariantReference=Random
RadarsActive=False

RelativePositionInNm=3,0,5
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=3
Waypoints=Turn,0,20,0

[------------------------------ Taskforce2 Ships ------------------------------]
[Taskforce2Vessel1]
Type=usn_cg_belknap

VariantReference=Random
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,30
RandomSpawnDirection=-179,180

Heading=Parent
Telegraph=2
Waypoints=Turn,0,5,0|ToSpawnPosition,Taskforce1Vessel1,0,300|195,0,-70|220,0,-130|1500,0,-200


[Taskforce2Vessel2]
Type=usn_ff_knox

VariantReference=Random
RadarsActive=False

PositionRelativeTo=Taskforce2Vessel1

RandomSpawnCenter=Taskforce2Vessel1
RandomSpawnRange=5,10
RandomSpawnDirection=-179,180

Heading=Parent
RandomizeCourse=-45,45

Telegraph=3
Waypoints=Turn,0,5,0|ToSpawnPosition,Taskforce1Vessel1,0,300|195,0,-70|220,0,-130|1500,0,-200

[Taskforce2Vessel3]
Type=usn_dd_gearing

VariantReference=Random
RadarsActive=False

PositionRelativeTo=Taskforce2Vessel1

RandomSpawnCenter=Taskforce2Vessel1
RandomSpawnRange=5,10
RandomSpawnDirection=-179,180

Heading=Parent
RandomizeCourse=-45,45

Telegraph=3
Waypoints=Turn,0,5,0|ToSpawnPosition,Taskforce1Vessel1,0,300|195,0,-70|220,0,-130|1500,0,-200

[------------------------------ Neutral Ships ------------------------------]
[NeutralVessel1]  #USSR Fishingboat
SpawnChance=0.75
Type=civ_fv_fishingboat_a

VariantReference=Variant1             //Variant1 = USSR
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-80,80

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|20,0,570         //20,0,570 = Magadan

[NeutralVessel2]  #USSR Fishingboat
SpawnChance=0.75
Type=civ_fv_fishingboat_a

VariantReference=Variant1             //Variant1 = USSR
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-80,80

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|20,0,570         //20,0,570 = Magadan

[NeutralVessel3]  #USSR Okean trawler
SpawnChance=0.75
Type=civ_fv_okean

VariantReference=Variant1             //Variant1 = USSR
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-80,80

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|20,0,570         //20,0,570 = Magadan


[NeutralVessel4]  #USSR Okean trawler
SpawnChance=0.75
Type=civ_fv_okean

VariantReference=Variant1             //Variant1 = USSR
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-179,180

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|20,0,570         //20,0,570 = Magadan


[NeutralVessel5]  #Japan Fishingboat
SpawnChance=0.75
Type=civ_fv_fishingboat_a

VariantReference=Variant4             //Variant4 = Japan
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-179,180

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|-340,0,-350         //20,0,570 = Abashiri

[NeutralVessel6]  #Japan Fishingboat
SpawnChance=0.75
Type=civ_fv_fishingboat_a

VariantReference=Variant4             //Variant4 = Japan
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-179,180

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|-340,0,-350         //20,0,570 = Abashiri

[NeutralVessel7]  #Japan Fishingboat
SpawnChance=0.75
Type=civ_fv_fishingboat_a

VariantReference=Variant4             //Variant4 = Japan
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-179,180

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|-340,0,-350         //20,0,570 = Abashiri


[NeutralVessel8]  #China Fishingboat
SpawnChance=0.75
Type=civ_fv_fishingboat_a

VariantReference=Variant5             //Variant5 = China
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-179,180

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|-340,0,-260|-600,0,-260|-900,0,-460   //Path to China's waters

[NeutralVessel9]  #China Fishingboat
SpawnChance=0.75
Type=civ_fv_fishingboat_a

VariantReference=Variant5             //Variant5 = China
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-179,180

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|-340,0,-260|-600,0,-260|-900,0,-460   //Path to China's waters

[NeutralVessel10] #China Fishingboat
SpawnChance=0.75
Type=civ_fv_fishingboat_a

VariantReference=Variant5             //Variant5 = China
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,80
RandomSpawnDirection=-179,180

Heading=0
RandomizeCourse=-179,180

Telegraph=2
Waypoints=Turn,0,20,0|-340,0,-260|-600,0,-260|-900,0,-460   //Path to China's waters


[NeutralVessel11] #Random Bulk Carrier
Type=civ_ms_bulk

VariantReference=Random
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,30
RandomSpawnDirection=-179,180

Heading=Parent
Telegraph=2
Waypoints=Turn,0,5,0|20,0,570         //20,0,570 = Magadan


[NeutralVessel12] #Random Bulk Carrier
Type=civ_ms_bulk

VariantReference=Random
RadarsActive=False

RandomSpawnCenter=NeutralVessel11
RandomSpawnRange=5,10
RandomSpawnDirection=-179,180

Heading=Parent
RandomizeCourse=-45,45

Telegraph=3
Waypoints=Turn,0,5,0|20,0,570         //20,0,570 = Magadan

[NeutralVessel13] #Random Bulk Carrier
Type=civ_ms_bulk

VariantReference=Random
RadarsActive=False

RandomSpawnCenter=NeutralVessel11
RandomSpawnRange=5,10
RandomSpawnDirection=-179,180

Heading=Parent
RandomizeCourse=-45,45

Telegraph=3
Waypoints=Turn,0,5,0|20,0,570         //20,0,570 = Magadan


[NeutralVessel14] #US freighter b
Type=civ_ms_freighter_b

VariantReference=Variant1
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=15,30
RandomSpawnDirection=-179,180

Heading=Parent
Telegraph=2
Waypoints=Turn,0,20,0|-340,0,-260|-600,0,-260|-900,0,-460   //Path to China's waters


[NeutralVessel15] #Random Super P
Type=civ_ms_super_p

VariantReference=Random
RadarsActive=False

RandomSpawnCenter=NeutralVessel14
RandomSpawnRange=5,10
RandomSpawnDirection=-179,180

Heading=Parent
RandomizeCourse=-45,45

Telegraph=3
Waypoints=Turn,0,20,0|-340,0,-260|-600,0,-260|-900,0,-460   //Path to China's waters

[NeutralVessel16] #Random Super P
Type=civ_ms_super_p

VariantReference=Random
RadarsActive=False

RandomSpawnCenter=NeutralVessel14
RandomSpawnRange=5,10
RandomSpawnDirection=-179,180

Heading=Parent
RandomizeCourse=-45,45

Telegraph=3
Waypoints=Turn,0,20,0|-340,0,-260|-600,0,-260|-900,0,-460   //Path to China's waters

[ ============================== Submarines ============================== ]
[Taskforce2Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Random
RadarsActive=False

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=10,15
RandomSpawnDirection=-179,180
RandomSpawnAltitude=-200/-120

DepthForNamedWaypoints=TODO

Heading=0
Telegraph=2
Waypoints=ToSpawnPosition,Taskforce1Vessel1,-200/-120|110,-200,240

