[Debug]
LogMode=Ivan
AllowEnemyUnitsAttackPlayer=True
TestAiDetection=True
MissionStartTextDM=Test night engagement Indian OSAs vs Pakistani forces

[Mission]
Difficulty=3

[Language_en]
Name=Persian clash
Description=Play stupid games win stupid prizes

[Environment]
Date=1982,3,12
Time=13,30

SeaState=2     // 0 ... 12
Clouds=scattered	//scattered_2 //broken	//scattered_1 //Clear

MapCenterLatitude=27.26	//31.72
MapCenterLongitude=51.14	//33.16

NumberOfTaskforce1Vessels=2
NumberOfTaskforce2Vessels=3
NumberOfNeutralVessels=3
NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=
NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=0
NumberOfNeutralAircraft=0
NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=Iran
Taskforce2_Nation=USN


[Taskforce1Vessel1]
Type=ir_ptg_combattante_II
//rn_dd_battle
//wp_pt_shershen-e
//ir_ptg_combattante_II
VariantReference=1
RadarsActive=True
RelativePositionInNM=0,0,0
Heading=270
Telegraph=1
Waypoints=-15,0,-15

[Taskforce1Vessel2]
MissionTarget=Protect
Type=ir_ptg_combattante_II
//wp_pt_shershen
//usn_dd_spruance
VariantReference=2
RelativePositionInNm=0.5,0,0.5
Heading=270
Telegraph=1
Waypoints=-16,0,-16

[Taskforce1Vessel3]
Type=wp_pt_p6
//wp_ptg_osa1
VariantReference=
RelativePositionInNm=-1,0,-1
Heading=330
Telegraph=1
Waypoints=-50,0,-17

[---------- Taskforce2 Vessels----------]
[Taskforce2Vessel1]
MissionTarget=Destroy
Type=usn_dd_spruance
//ins_ptg_saar2
//rn_dd_c-class
//usn_dd_spruance
VariantReference=
RelativePositionInNm=-6,0,-2
Heading=90
Telegraph=2
Waypoints=600,0,-15

[Taskforce2Vessel2]
MissionTarget=Destroy
Type=usn_ddg_adams_late
//usn_ffg_knox
VariantReference=
RelativePositionInNm=-7.2,0,-2
Heading=90
Telegraph=2
Waypoints=599,0,-11

[Taskforce2Vessel3]
Type=usn_ffg_oliver_hazard_perry
//ins_pt_saar
//wp_pt_shershen
VariantReference=
RelativePositionInNm=-9.5,0,-4
Heading=90
Telegraph=2
Waypoints=603,0,-15

[Taskforce2Vessel4]
MissionTarget=Destroy
Type=usn_ae_kilauea
//civ_ms_freighter_b
VariantReference=Variant1
RelativePositionInNm=-11,0,-4
Heading=90
Telegraph=3
Waypoints=595,0,-19

[---------- Neutral Vessels----------]
[NeutralVessel1]
#Italy goes from south west to east+
Type=civ_ms_mercur
VariantReference=Variant4
RelativePositionInNm=-5,0,-5
Heading=41
Telegraph=3
Waypoints=20,0,-3|500,0,500

[NeutralVessel2]
#UK goes from north west to east+
Type=civ_ms_amra
VariantReference=Variant12
RelativePositionInNm=-4,0,-2
Heading=55
Telegraph=3
Waypoints=-40,0,-2|-25,0,15|99,0,15|500,0,500

[NeutralVessel3]
#UK goes from south west to east+
Type=civ_ms_amra
VariantReference=Variant12
RelativePositionInNm=-10,0,-15
Heading=71
Telegraph=3
Waypoints=-20,0,-23|15,0-20|500,0,500

[NeutralVessel4]
#Italy goes from northeast to west+
Type=civ_ms_ritina
VariantReference=Variant12
RelativePositionInNm=16,0,10
Heading=246
Telegraph=3
Waypoints=-120,0,-40|-150,0,-500

[NeutralVessel5]
#Soviet, comes from north east to soutwest
Type=civ_ms_mercur
VariantReference=Variant1
RelativePositionInNm=18,0,12
Heading=244
Telegraph=5
Waypoints=-120,0,-40|-150,0,-500
#================================================================================ Submarines ================================================================================

#================================================================================ Aircraft ================================================================================
[Taskforce2Aircraft1]
Type=usn_f-14a
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=-30,5000,-100
Heading=220
Waypoints=-60,5000,-100|0,5000,-100|-60,5000,-100    //X - NM, Y - feet, Z - NM

[NeutralAircraft1]
Type=wp_tu-22m2
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=-30,10000,9
Heading=90
Telegraph=3
Waypoints=600,10000,9

[NeutralAircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron2
RadarsActive=True
RelativePositionInNm=-30.05,10000,9.05
Heading=90
Telegraph=3
Waypoints=600.05,10000,9.05

#================================================================================ Helicopters ================================================================================
