
[Debug]
DisableEnemyAIPlayer=True
DevModeGUIScale = 1.1

[Language_en]
Name=procedural-city-test
Description=For testing of autogen only!
Taskforce1VictoryMessage=For testing of autogen only!
Taskforce1DefeatMessage=For testing of autogen only!

[Mission]
LogMode=Ian

Difficulty=2
PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
Taskforce1_Nation=WP
Taskforce2_Nation=NATO
NumberOfTaskforce1Vessels=1
NumberOfTaskforce2Vessels=0
NumberOfNeutralVessels=0
NumberOfTaskforce1Submarines=1
NumberOfTaskforce2Submarines=0
NumberOfNeutralSubmarines=0
NumberOfTaskforce1Aircraft=0
NumberOfTaskforce2Aircraft=0
NumberOfNeutralAircraft=0
NumberOfTaskforce1Helicopters=0
NumberOfTaskforce2Helicopters=0
NumberOfNeutralHelicopters=0
NumberOfTaskforce1LandUnits=0
NumberOfTaskforce2LandUnits=0
NumberOfNeutralLandUnits=0
NumberOfTriggers=1

[Environment]
Date=1979,6,01
Time=15,00
SeaState=3
Clouds=Broken

MapCenterLatitude=36.26
MapCenterLongitude=-5.19

; ; Himalayas
; MapCenterLatitude=28.0529
; MapCenterLongitude=87.2090

; ; Tokyo Bay
; MapCenterLatitude=35.279829
; MapCenterLongitude=139.392115

; ; Berlin
; MapCenterLatitude=52.4135
; MapCenterLongitude=12.104

; ; Bergen Norway
; MapCenterLatitude=60.407
; MapCenterLongitude=5.289166

; ; Narvik Fjord
; MapCenterLatitude=68.426695
; MapCenterLongitude=17.137733
; Emden
; MapCenterLatitude=53.307391
; MapCenterLongitude=7.145060
; Murmansk
; MapCenterLatitude=68.999203
; MapCenterLongitude=33.036945
; Archangelsk
; MapCenterLatitude=64.55
; MapCenterLongitude=40.5

; ; Niigata
; MapCenterLatitude=37.9497108
; MapCenterLongitude=139.0016708

; Honolulu
; MapCenterLatitude=21.3400792
; MapCenterLongitude=-157.9728127
; Serengeti
; MapCenterLatitude=-2.1189069
; MapCenterLongitude=34.1733967
; Hawaii
; MapCenterLatitude=20.466
; MapCenterLongitude=-156.4328
; Port Moresby
; MapCenterLatitude=-9.570733
; MapCenterLongitude=147.116973
; Iceland South
; MapCenterLatitude=63.796061
; MapCenterLongitude=-22.552217
; GIUK
; MapCenterLatitude=58
; MapCenterLongitude=-23

; ; Gremikha USSR
; MapCenterLatitude=68.05972222
; MapCenterLongitude=39.51361111

; Straits of Hormuz
; MapCenterLatitude=26.584155
; MapCenterLongitude=56.245727

; Kharg Island
; pCenterLatitude=29.2697578
; pCenterLongitude=50.2510527

; Reydarfjördur
; MapCenterLatitude=65.021641
; MapCenterLongitude=-13.988764

; Norfolk US
; MapCenterLatitude=36.93111111
; MapCenterLongitude=-76.33055556

; New York US
; MapCenterLatitude=40.548803
; MapCenterLongitude=-74.038944

; Rota Spain
; MapCenterLatitude=36.622941
; MapCenterLongitude=-6.342686

; Solomons
; MapCenterLatitude=-9.144619
; MapCenterLongitude=160.189064

; [PlayerHelicopter1]
; Type=usn_sh-2f
; SquadronReference=Squadron1
; #possible keys: RelativePositionInNM or RelativePositionInKm
; #negative values go west for x and north for z, height (y) is in feet
; RelativePositionInKm=-0.1,100.0,-20.0
; Heading=90

[Taskforce1Vessel1]
Type=wp_ptg_tarantul
VariantReference=Variant1
RelativePositionInNM=15.24,0,-6.5
Heading=-90
Telegraph=0

[Taskforce1Vessel2]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-6.25
Heading=-90
Telegraph=0

[Taskforce1Vessel3]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-6.0
Heading=-90
Telegraph=0
[Taskforce1Vessel4]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-5.75
Heading=-90
Telegraph=0
[Taskforce1Vessel5]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-5.5
Heading=-90
Telegraph=0
[Taskforce1Vessel6]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-5.25
Heading=-90
Telegraph=0
[Taskforce1Vessel7]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-5.0
Heading=-90
Telegraph=0
[Taskforce1Vessel8]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-4.75
Heading=-90
Telegraph=0
[Taskforce1Vessel9]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-4.5
Heading=-90
Telegraph=0
[Taskforce1Vessel10]
Type=wp_rkr_slava
VariantReference=Variant1
RelativePositionInNM=15.25,0,-4.25
Heading=-90
Telegraph=0

[Taskforce1Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Variant0
WeaponStatus=Free
RelativePositionInNM=15.24,-150,-6.4
Heading=136
Telegraph=0


[Trigger1]
Disabled=True
Condition_Type=Time
Condition_Time=10
Action_EndMission=True
