[Debug]
LogMode=Ivan

# Overrides of usersettings.ini
#DisableTerrain=True
#DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
DevModeGUIScale=1      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons

TestAiDetection=True
AllowEnemyUnitsAttackPlayer=False

ContextMenuScale=1.2
ContextMenuFontSize=20
#-----------------------------

MissionStartTextDM=GO!

[Language_en]
Name=Performance Test
Description=Joint exercise of Soviet and US navy

[Environment]
Date=1974,5,9
Time=12,0

SeaState=4
Clouds=Broken_2
Overcast

#Weather=Rain,Fog,Thunderstorm //Supported values:Rain,Snow,Fog,Thunderstorm
Weather=Thunderstorm
#RainIntensity=500
#RainSize=1

MapCenterLatitude=36.23
MapCenterLongitude=18

[Mission]
Difficulty=1

#PlayerTaskforce=Taskforce2
#EnemyTaskforce=Taskforce1

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

Taskforce1_RelativePositionsScale=0.25
Taskforce2_RelativePositionsScale=0.25


Taskforce1_UI=Default
#Taskforce2_UI=Test

NumberOfTaskforce1Vessels=10
NumberOfTaskforce2Vessels=10
NumberOfNeutralVessels=

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[ ------------------------------ Player Ships ------------------------------ ]
[Taskforce1Vessel1]
Type=usn_cg_ticonderoga

VariantReference=Variant1

VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=False
TowedDecoyDeployed=False

WeaponStatus=Hold

RelativePositionInNM=50,0,7

Heading=-90
Telegraph=3
Waypoints=Turn,0,20,current

[Taskforce1Vessel2]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,2
PositionRelativeTo=Taskforce1Vessel1

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos


[Taskforce1Vessel3]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,2
PositionRelativeTo=Taskforce1Vessel1

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos


[Taskforce1Vessel4]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,-2
PositionRelativeTo=Taskforce1Vessel1

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos


[Taskforce1Vessel5]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,-2
PositionRelativeTo=Taskforce1Vessel1

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos

[Taskforce1Vessel6]
Type=usn_cg_ticonderoga

VariantReference=Variant1

VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=False
TowedDecoyDeployed=False

WeaponStatus=Hold

RelativePositionInNM=54,0,7

Heading=-90
Telegraph=3
Waypoints=Turn,0,20,current

[Taskforce1Vessel7]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,2
PositionRelativeTo=Taskforce1Vessel6

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel6,ownPos


[Taskforce1Vessel8]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,2
PositionRelativeTo=Taskforce1Vessel6

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel6,ownPos


[Taskforce1Vessel9]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,-2
PositionRelativeTo=Taskforce1Vessel6

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel6,ownPos


[Taskforce1Vessel10]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,-2
PositionRelativeTo=Taskforce1Vessel6

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce1Vessel6,ownPos


[ ------------------------------ Non Player Ships ------------------------------ ]
[Taskforce2Vessel1]
Type=usn_cg_ticonderoga

VariantReference=Variant1

VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=False
TowedDecoyDeployed=False

RelativePositionInNM=50,0,-10

WeaponStatus=Hold

Heading=90
Telegraph=3
Waypoints=Turn,0,20,current

[Taskforce2Vessel2]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,2
PositionRelativeTo=Taskforce2Vessel1

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce2Vessel1,ownPos


[Taskforce2Vessel3]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,2
PositionRelativeTo=Taskforce2Vessel1

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce2Vessel1,ownPos


[Taskforce2Vessel4]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,-2
PositionRelativeTo=Taskforce2Vessel1

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce2Vessel1,ownPos


[Taskforce2Vessel5]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,-2
PositionRelativeTo=Taskforce2Vessel1

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce2Vessel1,ownPos

[Taskforce2Vessel6]
Type=usn_cg_ticonderoga

VariantReference=Variant1

VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=False
TowedDecoyDeployed=False

RelativePositionInNM=54,0,-10

WeaponStatus=Hold

Heading=90
Telegraph=3
Waypoints=Turn,0,20,current

[Taskforce2Vessel7]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,2
PositionRelativeTo=Taskforce2Vessel6

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce2Vessel6,ownPos


[Taskforce2Vessel8]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,2
PositionRelativeTo=Taskforce2Vessel6

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce2Vessel6,ownPos


[Taskforce2Vessel9]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=2,0,-2
PositionRelativeTo=Taskforce2Vessel6

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce2Vessel6,ownPos


[Taskforce2Vessel10]
Type=usn_cg_leahy

VariantReference=Variant1

RadarsActive=True
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False

RelativePositionInNm=-2,0,-2
PositionRelativeTo=Taskforce2Vessel6

WeaponStatus=Hold

Heading=Parent
Telegraph=3
Waypoints=FollowLoose,Taskforce2Vessel6,ownPos