[Debug]
#AllowEnemyUnitsAttackPlayer=True
#TestAiDetection=True
LogMode=Ivan

[Environment]
Date=1974,5,9
Time=12,0

SeaState=4     // 0 ... 12
Clouds=Scattered

//Bergen Norway
//MapCenterLatitude=60.407
//MapCenterLongitude=5.289166
//Tokyo Bay
//MapCenterLatitude=35.279829
//MapCenterLongitude=139.392115
//Narvik Fjord
//MapCenterLatitude=68.426695
//MapCenterLongitude=17.137733
//Emden
//MapCenterLatitude=53.307391
//MapCenterLongitude=7.145060
//Murmansk
//MapCenterLatitude=68.999203
//MapCenterLongitude=33.036945
//Archangelsk
//MapCenterLatitude=64.55
//MapCenterLongitude=40.5
//Niigata
//MapCenterLatitude=37.9497108
//MapCenterLongitude=139.0016708
//Honolulu
//MapCenterLatitude=21.3400792
//MapCenterLongitude=-157.9728127
//Serengeti
//MapCenterLatitude=-2.1189069
//MapCenterLongitude=34.1733967
//Hawaii
//MapCenterLatitude=20.466
//MapCenterLongitude=-156.4328
//Port Moresby
//MapCenterLatitude=-9.570733
//MapCenterLongitude=147.116973
//Iceland South
//MapCenterLatitude=63.796061
//MapCenterLongitude=-22.552217
//GIUK
//MapCenterLatitude=58
//MapCenterLongitude=-23
//Gremikha USSR
MapCenterLatitude=68.05972222
MapCenterLongitude=39.51361111
//Straits of Hormuz
//MapCenterLatitude=26.584155
//MapCenterLongitude=56.245727
//Kharg Island
//MapCenterLatitude=29.2697578
//MapCenterLongitude=50.2510527
//Reydarfjördur
//MapCenterLatitude=65.021641
//MapCenterLongitude=-13.988764
//Norfolk US
//MapCenterLatitude=36.93111111
//MapCenterLongitude=-76.33055556
//New York US
//MapCenterLatitude=40.548803
//MapCenterLongitude=-74.038944
//Rota Spain
//MapCenterLatitude=36.622941
//MapCenterLongitude=-6.342686
//Solomons
//MapCenterLatitude=-9.144619
//MapCenterLongitude=160.189064

//MapCenterLatitude=30.386823458
//MapCenterLongitude=53.62415257

//MapCenterLatitude=27.199160915
//MapCenterLongitude=56.2132273

//MapCenterLatitude=29.2632331848145
//MapCenterLongitude=50.3000335693359

[Mission]
MapInitialZoom=7

NumberOfPlayerVessels=0
NumberOfEnemyVessels=0 //1
NumberOfNeutralVessels=0
NumberOfPlayerSubmarines=0
NumberOfEnemySubmarines=0
NumberOfNeutralSubmarines=0
NumberOfPlayerAircraft=1
NumberOfEnemyAircraft=0
NumberOfNeutralAircraft=0
NumberOfPlayerHelicopters=0
NumberOfEnemyHelicopters=0
NumberOfNeutralHelicopters=0
NumberOfPlayerLandUnits=1
NumberOfEnemyLandUnits=0

[PlayerLandUnit1]
Type=wp_large_pvo_airbase
VariantReference=Variant1
RelativePositionInKm=0,776.574828,-20
Heading=0

[PlayerLandUnit2]
Type=wp_sam_site_sa-5
VariantReference=Variant1

RadarsActive=True

RelativePositionInKm=0,869,-30
OverrideSpawnHeightUnity=3.95
Heading=0

[EnemyLandUnit1]
Type=wp_large_pvo_airbase
VariantReference=Variant1
RelativePositionInKm=0,776.574828,-20
Heading=0

[EnemyLandUnit2]
Type=wp_sam_site_sa-5
VariantReference=Variant1

RadarsActive=True

RelativePositionInKm=0,869,-30
OverrideSpawnHeightUnity=3.95
Heading=0

[PlayerAircraft1]
Type=wp_mig-23mld
usn_s-3a
wp_mig-23a
wp_il-38
wp_yak-38
wp_tu-142m
wp_tu-95rt
wp_tu-16k
wp_tu-16
wp_su-24a
wp_mig-27
wp_mig-25pd
usaf_f-15c
wp_il-38
usn_s-3a
usn_e-2c
usn_p-3c
usn_f-4j
usn_ea-6b
usn_a-6e
iriaf_f-4e
usn_a-6e
iaf_f-4e_kurnass
usn_f-14a
wp_mig-23mld
usn_ra-5c
usn_a-7e
wp_tu-22m2
wp_tu-16k
SquadronReference=Default
LoadoutVariant=Empty
#LoadoutVariant=Default
#LoadoutVariant=LandStrikeShortRange
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25.6,40000.0,18.0
#Waypoints=25.1,30000.0,250.0 | 50.0,10000,230.0
Heading=180

[PlayerVessel1]
Type=usn_bb_iowa
usn_bb_iowa
usn_cvn_nimitz
usn_cg_ticonderoga
wp_bpk_kanin
usn_ff_knox
wp_bpk_udaloy
wp_bdk_ivan_rogov
usn_dd_spruance
wp_rkr_kirov
wp_bpk_udaloy
usn_dd_spruance
VariantReference=Variant1
TowedArrayDeployed=True
ActiveSonarsEnabled=True
TowedDecoyDeployed=False
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=10,0.0,20
#RelativePositionInKm=20,0,17.5
RelativePositionInNm=0,0,2
#SingleUnitBehaviour=ai/SingleUnitBehaviours/UserUnitTest
Heading=270
Telegraph=0

[PlayerAircraft2]
Type=usn_a-6e
SquadronReference=Default
LoadoutVariant=Default
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,10000.0,-5
Heading=180

[PlayerAircraft3]
Type=usn_ea-6b
SquadronReference=Default
LoadoutVariant=Default
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,10000.0,-8
Heading=180

[PlayerHelicopter1]
Type=usn_sh-2f
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-0.1,100.0,-20.0
Heading=90

[EnemyAircraft1]
Type=wp_tu-16k
wp_tu-16k
SquadronReference=Squadron1
#RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25.6,9700.0,20.0
Waypoints=25.6,9700.0,250.0
Heading=10

[EnemyAircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=181,10000,180
Heading=220

[EnemyAircraft3]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=182,10000,180
Heading=220

[EnemyAircraft4]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=183,10000,180
Heading=220

[EnemyAircraft5]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=184,10000,180
Heading=220

[EnemyAircraft6]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=185,10000,180
Heading=220