[Debug]
LogMode=Ian
# Overrides of usersettings.ini
AllowEnemyUnitsAttackPlayer=True
#EnemyWeaponStatus=Free
TestAiDetection=True
MissionStartTextDM=Initial AI Testing Scene

DisableTerrain=True
#DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
DevModeGUIScale=1.2      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
ContextMenuScale=1.2
ContextMenuFontSize=20
DisableEnemyAIPlayer=True

[Language_en]
Name=test-ai-player
Description=This is a scenario for testing the AI Player. 

[Environment]
Date=1982,6,6
Time=12,00
SeaState=0     // 0 ... 12
Clouds=Scattered_2

MapCenterLatitude=43.4
MapCenterLongitude=50

[Mission]
Difficulty=2

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

#OPTIONAL
EnemyAIPlayerBehaviourPath=ai/NodeCanvas/AIPlayer
EnemyAIUnitBehaviourPath=ai/NodeCanvas/AIUnit
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

NumberOfTaskforce1Vessels=2
NumberOfTaskforce2Vessels=
NumberOfNeutralVessels=

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=1
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

Taskforce1_NumberOfFormations=1
Taskforce1_Formation1=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel7,Taskforce1Vessel8,Taskforce1Vessel9,Taskforce1Vessel10,Taskforce1Vessel11|AI Force|LineAbreast|1.0

Taskforce2_NumberOfFormations=1
Taskforce2_Formation1=Taskforce2Vessel1,Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4,Taskforce2Vessel5|Test Enemy|LineAbreast|1.0



[Taskforce1Vessel1]
Type=usn_cg_leahy
VariantReference=Variant1
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNM=5,0,0
Heading=270
Telegraph=3
Waypoints=0,0,0

[Taskforce1Vessel2]
Type=usn_cg_leahy
VariantReference=Variant2
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=2,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=Parent

// Always keep this unit in INI for super sensor. 
[Taskforce1Vessel3]
Type=ins_ptg_aliya
VariantReference=Variant1
ActiveSonarsEnabled=True
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=-2,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=Parent



[Taskforce1Vessel3]
Type=usn_cg_leahy
VariantReference=Variant3
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=-2,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=Parent

[Taskforce1Vessel4]
Type=usn_cg_leahy
VariantReference=Variant4
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=4,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=0

[Taskforce1Vessel5]
Type=usn_cg_leahy
VariantReference=Variant5
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=-4,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=0

[Taskforce1Vessel6]
Type=usn_cg_leahy
VariantReference=Variant6
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=6,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=0


[Taskforce1Vessel7]
Type=usn_cg_leahy
VariantReference=Variant7
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=-6,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=0


[Taskforce1Vessel8]
Type=usn_cg_leahy
VariantReference=Variant8
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=8,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=0

[Taskforce1Vessel9]
Type=usn_cg_leahy
VariantReference=Variant1
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=-8,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=0

[Taskforce1Vessel10]
Type=usn_cg_leahy
VariantReference=Variant1
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=10,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=0


[Taskforce1Vessel11]
Type=usn_cg_leahy
VariantReference=Variant1
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=-10,0,0
PositionRelativeTo=Taskforce1Vessel1
Heading=Parent
Telegraph=0



[---------- Taskforce2 Vessels----------]

[Taskforce2Vessel1]
Type=usn_cg_leahy
VariantReference=Variant4
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNM=-25,0,0
Heading=90
Telegraph=2
Waypoints=0,0,0

[Taskforce2Vessel2]
Type=usn_cg_leahy
VariantReference=Variant5
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=1,0,0
PositionRelativeTo=Taskforce2Vessel1
Heading=Parent

[Taskforce2Vessel3]
Type=wp_rkr_kirov
VariantReference=Variant1
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=-1,0,0
PositionRelativeTo=Taskforce2Vessel1
Heading=Parent

[Taskforce2Vessel4]
Type=ir_fab_boghammar
VariantReference=Variant1
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=2,0,0
PositionRelativeTo=Taskforce2Vessel1
Heading=Parent

[Taskforce2Vessel5]
Type=usn_cg_belknap
VariantReference=Variant1
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
WeaponStatus=Tight
RelativePositionInNm=2,0,0
PositionRelativeTo=Taskforce2Vessel1
Heading=Parent


#================================================================================ Submarines ================================================================================
[ ============================== Submarines ============================== ]
[Taskforce2Submarine1]
Type=wp_ssn_victor2
VariantReference=Random
#RadarsActive=True
#TowedArrayDeployed=True
ActiveSonarsEnabled=True
#TowedDecoyDeployed=True
WeaponStatus=Tight
RelativePositionInNM=-6,-200,0
Heading=90
Telegraph=3

#================================================================================ Aircraft ================================================================================
[Taskforce2Aircraft1]
Type=usn_f-14a
SquadronReference=Squadron1
RadarsActive=False
RelativePositionInNm=-30,5000,-100
Heading=220
Waypoints=-60,5000,-100|0,5000,-100|-60,5000,-100    //X - NM, Y - feet, Z - NM

[NeutralAircraft1]
Type=wp_tu-22m2
SquadronReference=Squadron1
RadarsActive=False
RelativePositionInNm=-30,10000,9
Heading=90
Telegraph=3
Waypoints=600,10000,9

[NeutralAircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron2
RadarsActive=False
RelativePositionInNm=-30.05,10000,9.05
Heading=90
Telegraph=3
Waypoints=600.05,10000,9.05



[---------- AIUnit Objectives ----------]
[Taskforce1Vessel1Objective1]
Directive=MoveToWayPoint # Keep move towards direction
Type=SingleUnit
Vector=0,1
Telegraph=3
Success=Timer,Encounter

[Taskforce1Vessel1Objective2]
Directive=DestroyHostiles
UnitID=1,3,5
Success=Any, All, 
 

[---------- Neutral Vessels----------]
[NeutralVessel1]
#Italy goes from south west to east+
Type=civ_ms_ritina
VariantReference=Variant4
RelativePositionInNm=-16,0,-24
Heading=41
Telegraph=3
Waypoints=20,0,-3|500,0,500
[NeutralVessel2]
#UK goes from north west to east+
Type=civ_ms_amra
VariantReference=Variant12
RelativePositionInNm=-42,0,-2
Heading=90
Telegraph=3
Waypoints=-40,0,-2|-25,0,15|99,0,15|500,0,500
[NeutralVessel3]
#UK goes from south west to east+
Type=civ_ms_amra
VariantReference=Variant12
RelativePositionInNm=-30,0,-25
Heading=71
Telegraph=3
Waypoints=-20,0,-23|15,0-20|500,0,500
[NeutralVessel4]
#Italy goes from northeast to west+
Type=civ_ms_ritina
VariantReference=Variant12
RelativePositionInNm=16,0,10
Heading=246
Telegraph=3
Waypoints=-120,0,-40|-150,0,-500

[NeutralVessel5]
#Soviet, comes from north east to soutwest
Type=civ_ms_mercur
VariantReference=Variant1
RelativePositionInNm=18,0,12
Heading=244
Telegraph=5
Waypoints=-120,0,-40|-150,0,-500

[---------- AI Player Objectives ----------]
[Objective1]
Directive=AttackingVector # Keep move towards direction
Type=SingleUnit
UnitID=1,3,5
Vector=0,1
Telegraph=3
Success=Timer,Encounter

[Objective2]
Directive=DestroyHostiles
UnitID=1,3,5
Success=Any, All, 
 