[Environment]
Date=1974,5,9
Time=12,30

OceanWavesAudioClip=audio/environment/Sea_Waves_Big_10sec_loop_stereo
OceanWavesAudioVolume=0.0

Clouds=Broken

NumberOfPlayerVessels=1
NumberOfEnemyVessels=1
NumberOfNeutralVessels=6
NumberOfPlayerAircraft=0
NumberOfEnemyAircraft=0
NumberOfNeutralAircraft=0
NumberOfPlayerHelicopters=0
NumberOfEnemyHelicopters=0
NumberOfNeutralHelicopters=0

//Bergen Norway
//MapCenterLatitude=60.407
//MapCenterLongitude=5.289166
//Tokyo Bay
//MapCenterLatitude=35.279829
//MapCenterLongitude=139.392115
//Narvik Fjord
//MapCenterLatitude=68.426695
//MapCenterLongitude=17.137733
//Emden
//MapCenterLatitude=51.307391
//MapCenterLongitude=7.645060
//Murmansk
//MapCenterLatitude=68.999203
//MapCenterLongitude=33.036945
//Archangelsk
//MapCenterLatitude=64.55
//MapCenterLongitude=40.5
//Niigata
//MapCenterLatitude=37.9497108
//MapCenterLongitude=139.0016708
//Honolulu
//MapCenterLatitude=21.3400792
//MapCenterLongitude=-157.9728127
//Serengeti
//MapCenterLatitude=-2.1189069
//MapCenterLongitude=34.1733967
//Hawaii
//MapCenterLatitude=20.466
//MapCenterLongitude=-156.4328
//Port Moresby
//MapCenterLatitude=-9.570733
//MapCenterLongitude=147.116973
//Iceland South
//MapCenterLatitude=63.796061
//MapCenterLongitude=-22.552217
//GIUK
MapCenterLatitude=62
MapCenterLongitude=-7.5
//Gremikha USSR
//MapCenterLatitude=68.05972222
//MapCenterLongitude=39.51361111
//Straits of Hormuz
//MapCenterLatitude=26.584155
//MapCenterLongitude=56.245727
//Kharg Island
//MapCenterLatitude=29.2697578
//MapCenterLongitude=50.2510527
//Reydarfjördur
//MapCenterLatitude=65.021641
//MapCenterLongitude=-13.988764
//Norfolk US
//MapCenterLatitude=36.93111111
//MapCenterLongitude=-76.33055556
//New York US
//MapCenterLatitude=40.548803
//MapCenterLongitude=-74.038944
//Rota Spain
//MapCenterLatitude=36.622941
//MapCenterLongitude=-6.342686

//Baku
//MapCenterLatitude=36.978397
//MapCenterLongitude=53.736483

//MapCenterLatitude=30.386823458
//MapCenterLongitude=53.62415257

//Vättern
//MapCenterLatitude=58.247581
//MapCenterLongitude=11.242221

//MapCenterLatitude=27.199160915
//MapCenterLongitude=56.2132273

//=45.414437
//MapCenterLongitude=12.809160
//Kamchatka
//MapCenterLatitude=56.092698
//MapCenterLongitude=162.469231

//Thanh Hoa
//MapCenterLatitude=19.981032
//MapCenterLongitude=105.370872

//Solomons
//MapCenterLatitude=-9.144619
//MapCenterLongitude=160.189064

[PlayerVessel1]
#Type=usn_cv_america_79
#Type=usn_dd_spruance
#Type=wp_bpk_kresta2
#Type=wp_skr_krivak1
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.0,0.0,0.0
Heading=30
Telegraph=0

[PlayerVessel2]
Type=usn_cv_kitty_hawk
VariantReference=Variant3
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=100,0.0,160.0
Heading=180
Telegraph=5

[PlayerVessel3]
Type=usn_cv_kitty_hawk
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=-150.0,0.0,0.5
#RelativePositionInNM=0.0,0.0,0.5
#Latitude=22.0
#Longitude=-156.4328
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.0,0.0,0.6
Heading=90
Telegraph=0

[PlayerVessel4]
Type=usn_dd_spruance
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=-150.0,0.0,0.5
#RelativePositionInNM=0.0,0.0,0.5
Latitude=22.0
Longitude=-156.4328
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-3.0,0.0,6.0
Heading=90
Telegraph=5

[PlayerVessel5]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=-150.0,0.0,0.5
#RelativePositionInNM=0.0,0.0,0.5
Latitude=22.0
Longitude=-156.4328
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=3.0,0.0,12.0
Heading=90
Telegraph=5

[PlayerVessel6]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=-150.0,0.0,0.5
#RelativePositionInNM=0.0,0.0,0.5
Latitude=22.0
Longitude=-156.4328
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-3.0,0.0,-12.0
Heading=90
Telegraph=5

[EnemyVessel1]
Type=wp_skr_krivak1
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,0.0,13
Heading=0
Telegraph=0

[EnemyVessel2]
Type=usn_cg_belknap
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=100,0,1
Heading=270
Telegraph=0

[NeutralVessel1]
Type=usn_ae_kilauea
VariantReference=Variant4
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=11.88,0.0,0
Heading=0
Telegraph=0

[NeutralVessel2]
Type=usn_ae_kilauea
VariantReference=Variant3
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=14.9,0.0,0
Heading=0
Telegraph=0

[NeutralVessel3]
Type=usn_ae_kilauea
VariantReference=Variant5
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=17.37,0.0,0
Heading=0
Telegraph=0

[NeutralVessel4]
Type=usn_ae_kilauea
VariantReference=Variant6
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=20.57,0.0,0
Heading=0
Telegraph=0

[NeutralVessel5]
Type=usn_ae_kilauea
VariantReference=Variant6
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=22.86,0.0,0
Heading=0
Telegraph=0

[NeutralVessel6]
Type=usn_ae_kilauea
VariantReference=Variant6
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=23.69,0.0,0
Heading=0
Telegraph=0

[PlayerAircraft1]
Type=wp_tu-95rt
#Type=usn_f-14a
#Type=wp_mig-25p
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=80.0,1000.0,120.0
Heading=90

[PlayerAircraft2]
Type=usn_f-14a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=100.0,1000.0,90.0
Heading=90

[PlayerAircraft3]
Type=usn_f-14a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20.0,0.1,10.0
Heading=90

[PlayerHelicopter1]
Type=usn_sh-2f
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-0.1,100.0,-10.0
Heading=90

[EnemyAircraft1]
Type=usn_f-14a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-10.0,20000.0,0.0
Heading=180

[EnemyHelicopter1]
Type=usn_sh-2f
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=10.0,1000.0,2.0
Heading=270