[Debug]
LogMode=Ivan

[Environment]
Date=1974,5,9
Time=07,15

SeaState=2     // 0 ... 12
Clouds=Scattered

MapCenterLatitude=50
MapCenterLongitude=-1

[Mission]
Difficulty=0

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=USA
Taskforce2_Nation=Soviet

NumberOfTaskforce1LandUnits=1

NumberOfTaskforce1Vessels=
NumberOfTaskforce2Vessels=
NumberOfNeutralVessels=

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=27
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[Taskforce1LandUnit1]
Type=wp_large_pvo_airbase
VariantReference=Variant1
RelativePositionInKm=0,0,-20
Heading=0

[Taskforce1Aircraft1]
Type=civ_707
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.0,1500.0,0.0
Heading=220

[Taskforce1Aircraft2]
Type=iaf_f-4e_kurnass
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=100.0,1500.0,0.0
Heading=220

[Taskforce1Aircraft3]
Type=wp_yak-38
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=200.0,1500.0,0.0
Heading=220

[Taskforce1Aircraft4]
Type=usaf_f-15c
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=300.0,1500.0,0.0
Heading=220

[Taskforce1Aircraft5]
Type=usn_a-6e
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=400.0,1500.0,0.0
Heading=220

[Taskforce1Aircraft6]
Type=usn_a-7e
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=500.0,1500.0,0.0
Heading=220

[Taskforce1Aircraft7]
Type=usn_e-2c
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.0,1500.0,100.0
Heading=220

[Taskforce1Aircraft8]
Type=usn_ea-6b
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=100.0,1500.0,100.0
Heading=220

[Taskforce1Aircraft9]
Type=usn_f-4j
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=200.0,1500.0,100.0
Heading=220

[Taskforce1Aircraft10]
Type=usn_f-14a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=300.0,1500.0,100.0
Heading=220

[Taskforce1Aircraft11]
Type=usn_p-3c
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=400.0,1500.0,100.0
Heading=220

[Taskforce1Aircraft12]
Type=usn_ra-5c
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=500.0,1500.0,100.0
Heading=220

[Taskforce1Aircraft13]
Type=usn_s-3a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.0,1500.0,200.0
Heading=220

[Taskforce1Aircraft14]
Type=wp_il-38
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=100.0,1500.0,200.0
Heading=220

[Taskforce1Aircraft15]
Type=wp_mig-23a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=200.0,1500.0,200.0
Heading=220

[Taskforce1Aircraft16]
Type=wp_mig-23mld
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=300.0,1500.0,200.0
Heading=220

[Taskforce1Aircraft17]
Type=wp_mig-25pd
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=400.0,1500.0,200.0
Heading=220

[Taskforce1Aircraft18]
Type=wp_mig-27
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=500.0,1500.0,200.0
Heading=220

[Taskforce1Aircraft19]
Type=wp_p-42
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.0,1500.0,300.0
Heading=220

[Taskforce1Aircraft20]
Type=wp_su-24a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=100.0,1500.0,300.0
Heading=220

[Taskforce1Aircraft21]
Type=wp_tu-16
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=200.0,1500.0,300.0
Heading=220

[Taskforce1Aircraft22]
Type=wp_tu-16k
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=300.0,1500.0,300.0
Heading=220

[Taskforce1Aircraft23]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=400.0,1500.0,300.0
Heading=220

[Taskforce1Aircraft24]
Type=wp_tu-95rt
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=500.0,1500.0,300.0
Heading=220

[Taskforce1Aircraft25]
Type=wp_tu-142m
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.0,1500.0,400.0
Heading=220

#BROKEN!
#[Taskforce1Aircraft26]
#Type=iriaf_f-4e
#SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=100.0,1500.0,400.0
#Heading=220

[Taskforce1Aircraft27]
Type=civ_dc-10
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=100.0,1500.0,400.0
Heading=220