[Debug]
LogMode=Ivan
AllowEnemyUnitsAttackPlayer=True
TestAiDetection=True
# Overrides of usersettings.ini
DisableTerrain=True
DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
ScaleStep=0.2             // Value that is added or substracted from the scale by scale change buttons
#-----------------------------

TestAiDetection=True
MissionStartTextDM=
\n\n                             Welcome commander!\n\n  In this mission your primary objective is to find and sink a <color={*}ffc68c>cargo vessel</color> transporting military cargo of high value from US to Norway. \n  Intelligence has information that this vessel with a small escort will be passing north of Faroe Islands.\n

[Mission]
Difficulty=1

[Language_en]
Name=test-przemek 3
Description=

[Environment]
Date=1971,5,9
Time=16,30

SeaState=4     // 0 ... 12
Clouds=Broken

NumberOfPlayerVessels=3
NumberOfEnemyVessels=1
NumberOfNeutralVessels=
NumberOfPlayerSubmarines=
NumberOfEnemySubmarines=
NumberOfNeutralSubmarines=
NumberOfPlayerAircraft=
NumberOfEnemyAircraft=
NumberOfNeutralAircraft=
NumberOfPlayerHelicopters=
NumberOfEnemyHelicopters=
NumberOfNeutralHelicopters=


MapCenterLatitude=0
MapCenterLongitude=0

#MapCenterLatitude=41
#MapCenterLongitude=29

#MapCenterLatitude=58
#MapCenterLongitude=-23


[PlayerVessel1]
Type=rn_dd_c-class
//usn_mso_aggressive
//ins_ff_blackwood
//ins_ptg_saar_4
//ins_pt_saar
//wp_ptg_osa1
//usn_bb_iowa
//wp_skr_krivak1
//usn_dd_spruance

VariantReference=Variant1
RadarsActive=True

TowedArrayDeployed=False
ActiveSonarsEnabled=False
TowedDecoyDeployed=False

#CustomAirGroup=True
#usn_f-14a=Squadron1,4|Squadron2,8
#usn_s-3a=Squadron3,5

#LoadoutVariant=CIWS

#RelativePositionInNM=0,0,0
RelativePositionInNM=0,0,0
Heading=90
Telegraph=0
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=10,0,0

[PlayerVessel2]
Type=ins_ff_blackwood
//ins_ptg_saar_2
//usn_bb_iowa
//wp_kr_sverdlov
#Type=wp_bpk_kara
#Type=wp_skr_krivak1
#Type=usn_dd_spruance
#Type=wp_rkr_kynda
#Type=usn_ddg_adams_late

#Type=usn_ffg_oliver_hazard_perry
#Type=usn_cg_belknap
#Type=wp_bpk_kanin
#Type=usn_ssn_sturgeon
#usn_cgn_virginia
#ir_fab_boghammar
#wp_pkr_moskva
#wp_ptg_osa1
#usn_cg_ticonderoga
#usn_cgn_virginia
#usn_bb_iowa
#usn_ff_knox
#usn_cv_kitty_hawk
#usn_cg_leahy
#ins_ptg_aliya
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=10,0.0,20
RelativePositionInNm=0.1,0,0.1
#RelativePositionInNm=2,0,-2.5
Heading=90
Telegraph=0
Waypoints=10,0,1

[PlayerVessel3]
Type=usn_mso_aggressive
//Type=usn_dd_spruance
//usn_ff_knox
//wp_skr_krivak1
VariantReference=Variant1
RelativePositionInNm=0.2,0,-0.01
Heading=90
Telegraph=0
Waypoints=2,0,1

[EnemyVessel1]
Type=rn_dd_c-class
//wp_ptg_osa1
//wp_kr_sverdlov
//wp_bpk_kara
NameReference=Random
RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=4,0,4
Heading=199
Telegraph=1
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=28,0,5

[EnemyVessel2]
Type=wp_kr_sverdlov
//wp_bpk_kara
//wp_kr_sverdlov
NameReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=2.5,0,1
Heading=199
Telegraph=1
Waypoints=28,0,5.2

[EnemyVessel3]
Type=wp_ptg_osa1
//usn_ddg_adams_late
VariantReference=Variant3
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=3,0,1
Heading=211
Telegraph=2
Waypoints=6,0,5.5

[NeutralVessel1]
Type=civ_fv_fishingboat_a
#Type=civ_ms_freighter_b
#Type=civ_ms_amra
#Type=civ_ms_irkutsk
#Type=civ_ms_ritina
#civ_ms_mercur
NameReference=Random
RadarsActive=False
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=0,0,3
Heading=90
Telegraph=0
Waypoints=12,0,-3

[NeutralVessel2]
Type=civ_fv_fishingboat_a
NameReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=3,0,0
Heading=0
Telegraph=0
Waypoints=-12,0,-3

[NeutralVessel3]
Type=civ_fv_fishingboat_a
NameReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=0,0,-3
Heading=90
Telegraph=0
Waypoints=-12,0,-3

[NeutralVessel4]
Type=civ_fv_fishingboat_a
NameReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInNm=-3,0,0
Heading=0
Telegraph=0
Waypoints=-12,0,-3

#================================================================================ Submarines ================================================================================
[PlayerSubmarine1]
Type=wp_ssn_victor3
#Type=usn_ssn_sturgeon
#Type=wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
#Type=wp_ssgn_echo2
NameReference=Random
#RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=2,p,-5.08
Heading=90
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM

[PlayerSubmarine2]
Type=wp_ssgn_charlie1
#Type=usn_ssn_sturgeon
#Type=wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
VariantReference=Variant1
#RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=10.06,p,2
Heading=90
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM

[EnemySubmarine1]
Type=usn_ssn_sturgeon
NameReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,-200,-4
Heading=90
Telegraph=0
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=0,-200,10

#================================================================================ Aircraft ================================================================================
[PlayerAircraft1]
Type=usn_f-14a
wp_yak-38
iriaf_f-4e
wp_il-38
usn_ea-6b
usn_sh-2f

#Type=usn_f-14a
#wp_tu-22m2
#usn_f-14a
#usn_a-7e
#wp_yak-38
#iriaf_f-4e
SquadronReference=Squadron1
RadarsActive=True
HomeBase=PlayerVessel1
//LoadoutVariant=Empty
#LoadoutVariant=Loadout1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=0.0,9500.0,-50.0
RelativePositionInNm=-4,400,0
Heading=90
Waypoints=225,200,0|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM

[PlayerAircraft2]
Type=usn_s-3a
SquadronReference=Squadron1
//LoadoutVariant=Strike
RelativePositionInNm=-4,200,0.05
Heading=90
Waypoints=25,200,0.05|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM


[PlayerAircraft3]
Type=iriaf_f-4e
SquadronReference=Squadron2
LoadoutVariant=IronHand
RelativePositionInNm=-4,1000,-0.05
Heading=90
Waypoints=25,1000,-0.05|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM


[PlayerAircraft4]
Type=iriaf_f-4e
SquadronReference=Random
LoadoutVariant=SEAD
RelativePositionInNm=-6,1000,-0.05
Heading=90
Waypoints=25,1000,-0.05|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM

[EnemyAircraft1]
Type=wp_yak-38
SquadronReference=Squadron1
LoadoutVariant=Backup
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=0,10000,40
RelativePositionInNm=-3,1000,0
Heading=90
Waypoints=25,1000,0|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM

[EnemyAircraft2]
Type=iriaf_f-4e
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=0,10000,40
RelativePositionInNm=-8,1000,0
Heading=90
Waypoints=25,1000,0|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM

[NeutralAircraft1]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=50,95000,0
Heading=220

#================================================================================ Helicopters ================================================================================
[PlayerHelicopter1]
MissionTarget=Protect
Type=wp_ka-27
SquadronReference=111
#LoadoutVariant=Loadout2
RadarsActive=True
HomeBase=PlayerVessel1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=-10,4000,0
//RelativePositionInNm=2,50,22
RelativePositionInNm=0.5,400,-0
Heading=90
#Waypoints=-7,200,0.08    //X - NM, Y - feet, Z - NM

[PlayerHelicopter2]
Type=wp_ka-25
#wp_ka-27
SquadronReference=Squadron2
#LoadoutVariant=Loadout3
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,100,-4
Heading=90
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM

[PlayerHelicopter3]
Type=usn_sh-2f
SquadronReference=Squadron3
LoadoutVariant=Loadout1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-5,3000.0,0
Heading=90

[EnemyHelicopter1]
MissionTarget=Destroy
Type=usn_sh-2f
SquadronReference=Squadron2
LoadoutVariant=Loadout1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=6,16000,01.08
RelativePositionInNM=0,40,-2
Heading=90

[EnemyHelicopter2]
MissionTarget=Destroy
Type=usn_sh-2f
SquadronReference=Squadron2
LoadoutVariant=Loadout2
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=-1,40,-4
Heading=90

[EnemyHelicopter3]
MissionTarget=Destroy
Type=usn_sh-2f
SquadronReference=Squadron3
LoadoutVariant=Loadout3
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=1,40,-4
Heading=90

[EnemyHelicopter4]
Type=usn_sh-2f
SquadronReference=Squadron4
LoadoutVariant=Loadout3
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=0,40,-5
Heading=90