#Not sure about this mission. Probably it should be deleted
[Debug]
LogMode=Ivan

# Overrides of usersettings.ini
#DisableTerrain=True
#DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
DevModeGUIScale=1.5      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
AllowEnemyUnitsAttackPlayer=False
#-----------------------------

TestAiDetection=True

[Language_en]
Name=BehaviourTask Test mission
Description=Mission for testing BehaviourTask

[Environment]
Date=1974,5,9
Time=9,30

SeaState=3
Clouds=Clear

[Mission]
Difficulty=1

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

MapCenterLatitude=36
MapCenterLongitude=25

NumberOfTaskforce1Vessels=1
NumberOfTaskforce2Vessels=
NumberOfNeutralVessels=
NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=
NumberOfTaskforce1Aircraft=1
NumberOfTaskforce2Aircraft=2
NumberOfNeutralAircraft=
NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[Taskforce1Vessel1]
Type=usn_dd_spruance
wp_bpk_kara
#Behaviour=ASW
VariantReference=Variant1
RadarsActive=True

TowedArrayDeployed=True
ActiveSonarsEnabled=True
TowedDecoyDeployed=False

#LoadoutVariant=CIWS

RelativePositionInNM=0,0,-3
Heading=90
Telegraph=0
Waypoints=-80,0,200

[Taskforce2Vessel1]
Type=wp_bpk_kara
VariantReference=Variant1
RadarsActive=True

TowedArrayDeployed=True
ActiveSonarsEnabled=True
TowedDecoyDeployed=False

#LoadoutVariant=CIWS

RelativePositionInNM=0,0,-4
Heading=90
Telegraph=0
Waypoints=20,0,0

[ ============================== Submarines ============================== ]
[Taskforce1Submarine1]
Type=wp_ssn_victor3
#Type=usn_ssn_sturgeon
#Type=wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
#Type=wp_ssgn_echo2
VariantReference=Random
#RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0.8,p,-0.5
Heading=-90
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM


[Taskforce2Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,0,-4
Heading=0
Telegraph=4
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=0,-200,10


[ =============================== Aircraft =============================== ]

[Taskforce1Aircraft1]
Type=usn_a-7e
SquadronReference=Squadron1
LoadoutVariant=Test
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=0,10000,40
RelativePositionInNm=-3,1000,0
Heading=90
Waypoints=25,1000,0|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM

[Taskforce2Aircraft1]
Type=usn_f-14a
SquadronReference=Squadron1
//LoadoutVariant=Backup
Behaviour=AirPatrol
RelativePositionInNm=-3,1000,20
Heading=90
Waypoints=25,1000,100|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM


[Taskforce2Aircraft2]
Type=usn_e-2c
SquadronReference=Squadron1
RelativePositionInNm=-3,1000,-1
Heading=90
#Waypoints=25,1000,0|2,4000,2|4,200,4    //X - NM, Y - feet, Z - NM
[ ============================== Helicopters ============================= ]


[ ============================== Behaviour Definitions ============================= ]
[Behaviour_ASW]
Stuff=stuff

[Behaviour_AirPatrol]
Stuff=stuff
