[Environment]
Date=1974,5,9
Time=9,30

Clouds=Broken

NumberOfPlayerVessels=2
NumberOfEnemyVessels=0
NumberOfNeutralVessels=0
NumberOfPlayerSubmarines=0
NumberOfEnemySubmarines=1
NumberOfNeutralSubmarines=0
NumberOfPlayerAircraft=1
NumberOfEnemyAircraft=0
NumberOfNeutralAircraft=0
NumberOfPlayerHelicopters=0
NumberOfEnemyHelicopters=0
NumberOfNeutralHelicopters=0

//MapCenterLatitude=0
//MapCenterLongitude=0

//Bergen Norway
//MapCenterLatitude=60.407
//MapCenterLongitude=5.289166
//Tokyo Bay
//MapCenterLatitude=35.279829
//MapCenterLongitude=139.392115
//Narvik Fjord
//MapCenterLatitude=68.426695
//MapCenterLongitude=17.137733
//Emden
//MapCenterLatitude=53.307391
//MapCenterLongitude=7.145060
//Murmansk
//MapCenterLatitude=68.999203
//MapCenterLongitude=33.036945
//Archangelsk
//MapCenterLatitude=64.55
//MapCenterLongitude=40.5
//Niigata
//MapCenterLatitude=37.9497108
//MapCenterLongitude=139.0016708
//Honolulu
//MapCenterLatitude=21.3400792
//MapCenterLongitude=-157.9728127
//Serengeti
//MapCenterLatitude=-2.1189069
//MapCenterLongitude=34.1733967
//Hawaii
//MapCenterLatitude=20.466
//MapCenterLongitude=-156.4328
//Port Moresby
//MapCenterLatitude=-9.570733
//MapCenterLongitude=147.116973
//Iceland South
//MapCenterLatitude=63.796061
//MapCenterLongitude=-22.552217
//GIUK
MapCenterLatitude=58
MapCenterLongitude=-23
//Gremikha USSR
//MapCenterLatitude=68.05972222
//MapCenterLongitude=39.51361111
//Straits of Hormuz
//MapCenterLatitude=26.584155
//MapCenterLongitude=56.245727
//Kharg Island
//MapCenterLatitude=29.2697578
//MapCenterLongitude=50.2510527
//Reydarfjördur
//MapCenterLatitude=65.021641
//MapCenterLongitude=-13.988764
//Norfolk US
//MapCenterLatitude=36.93111111
//MapCenterLongitude=-76.33055556
//New York US
//MapCenterLatitude=40.548803
//MapCenterLongitude=-74.038944
//Rota Spain
//MapCenterLatitude=36.622941
//MapCenterLongitude=-6.342686
//Solomons
//MapCenterLatitude=-9.144619
//MapCenterLongitude=160.189064

//MapCenterLatitude=30.386823458
//MapCenterLongitude=53.62415257

//MapCenterLatitude=27.199160915
//MapCenterLongitude=56.2132273

[PlayerVessel1]
#Type=usn_cvn_nimitz
#Type=usn_cv_kitty_hawk
#Type=wp_takr_kiev
#Type=usn_cg_leahy
#Type=usn_ffg_oliver_hazard_perry
#Type=wp_rkr_kynda
#Type=wp_em_sovremenny
#Type=usn_cg_ticonderoga
#Type=wp_skr_krivak1
#Type=wp_rkr_kresta1
#Type=usn_cg_belknap
#Type=civ_ms_act_1
#Type=usn_cgn_virginia
#Type=wp_ptg_osa1
#Type=ir_fab_boghammar
#Type=wp_bpk_udaloy
#Type=wp_bpk_kresta2
#Type=wp_ptg_osa2
Type=usn_dd_spruance
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=10,0.0,20
RelativePositionInKm=0,0,0
Heading=100
Telegraph=3

[PlayerVessel2]
#Type=usn_cvn_nimitz
Type=usn_ffg_oliver_hazard_perry
#Type=usn_dd_spruance
#Type=wp_bpk_kresta2
VariantReference=Variant2
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=0.0,0.0,0.0
RelativePositionInKm=10,0,10
Heading=100
Telegraph=3

[PlayerVessel3]
Type=usn_ffg_oliver_hazard_perry
#Type=usn_cv_kitty_hawk
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=-150.0,0.0,0.5
#RelativePositionInNM=0.0,0.0,0.5
#Latitude=22.0
#Longitude=-156.4328
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=-180,0,-180
Heading=90
Telegraph=0

[PlayerVessel4]
Type=usn_ffg_oliver_hazard_perry
#Type=usn_dd_spruance
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=-150.0,0.0,0.5
#RelativePositionInNM=0.0,0.0,0.5
#Latitude=22.0
#Longitude=-156.4328
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=-180,0,180
Heading=90
Telegraph=0

[PlayerVessel5]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=-150.0,0.0,0.5
#RelativePositionInNM=0.0,0.0,0.5
Latitude=22.0
Longitude=-156.4328
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=3.0,0.0,12.0
Heading=90
Telegraph=5

[PlayerVessel6]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=-150.0,0.0,0.5
#RelativePositionInNM=0.0,0.0,0.5
Latitude=22.0
Longitude=-156.4328
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-3.0,0.0,-12.0
Heading=90
Telegraph=5

[EnemyVessel1]
Type=wp_skr_krivak1
#Type=usn_ffg_oliver_hazard_perry
#Type=wp_em_sovremenny
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-10,0,10
Heading=310
Telegraph=0

[EnemyVessel2]
Type=wp_skr_krivak1
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=35,0,20
Heading=310
Telegraph=3

[EnemyVessel3]
Type=wp_skr_krivak1
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,0.0,22
Heading=90
Telegraph=5

[EnemyVessel4]
Type=wp_skr_krivak1
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-2,0.0,20.0
Heading=90
Telegraph=5

[NeutralVessel1]
Type=civ_ms_ritina
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=20,0.0,-20
Heading=280
Telegraph=0

[NeutralVessel2]
Type=civ_ms_ritina
VariantReference=Variant18
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=-50,0.0,-40
Heading=90
Telegraph=3

[NeutralVessel3]
Type=civ_ms_mairangi_bay
VariantReference=Variant5
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=-50,0.0,40
Heading=90
Telegraph=3

[PlayerSubmarine1]
Type=wp_ssn_victor3
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,-200,5
Heading=270
Telegraph=0

[EnemySubmarine1]
Type=wp_ssn_alfa
#Type=usn_ssn_sturgeon
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=2,-200,-3
Heading=170
Telegraph=5

[EnemySubmarine2]
Type=wp_ssgn_charlie1
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20,-200,-7
Heading=270
Telegraph=0

[PlayerAircraft1]
#Type=usn_s-3a
#Type=usn_f-14a
#Type=wp_tu-95rt
#Type=wp_tu-142m
Type=usn_a-7e
#Type=wp_mig-25p
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.0,9500.0,-50.0
Heading=10

[PlayerAircraft2]
#Type=usn_f-14a
Type=usn_a-7e
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0.2,9500.0,-50.2
Heading=10

[PlayerAircraft3]
Type=usn_f-14a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20.0,0.1,10.0
Heading=90

[PlayerHelicopter1]
Type=usn_sh-2f
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-0.1,100.0,-10.0
Heading=90

[EnemyAircraft1]
#Type=usn_a-7e
Type=wp_tu-95rt
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=10,8000,10
Heading=200
