[Debug]
#LogMode=Ivan
#DisableTerrain=True

AllowEnemyUnitsAttackPlayer=False

[Environment]
Date=1986,7,9
Time=7,0

SeaState=3     // 0 ... 12
Clouds=Clear
#Weather=Rain //Supported values:Rain,Snow,Fog,Thunderstorm

//North of Crete
//MapCenterLatitude=36.103398
//MapCenterLongitude=24.815894
//Bergen Norway
//MapCenterLatitude=60.407
//MapCenterLongitude=5.289166
//Tokyo Bay
//MapCenterLatitude=35.279829
//MapCenterLongitude=139.392115
//Narvik Fjord
//MapCenterLatitude=68.252551
//MapCenterLongitude=17.072467
//Emden
//MapCenterLatitude=53.307391
//MapCenterLongitude=7.145060
//Murmansk
//MapCenterLatitude=68.999203
//MapCenterLongitude=33.036945
//Archangelsk
//MapCenterLatitude=64.55
//MapCenterLongitude=40.5
//Niigata
//MapCenterLatitude=37.9497108
//MapCenterLongitude=139.0016708
//Honolulu
//MapCenterLatitude=21.3400792
//MapCenterLongitude=-157.9728127
//Serengeti
//MapCenterLatitude=-2.1189069
//MapCenterLongitude=34.1733967
//Hawaii
//MapCenterLatitude=20.466
//MapCenterLongitude=-156.4328
//Port Moresby
//MapCenterLatitude=-9.570733
//MapCenterLongitude=147.116973
//Iceland South
//MapCenterLatitude=63.796061
//MapCenterLongitude=-22.552217
//GIUK
//MapCenterLatitude=58
//MapCenterLongitude=-23
//Gremikha USSR
//MapCenterLatitude=68.05972222
//MapCenterLongitude=39.51361111
//Straits of Hormuz
//MapCenterLatitude=26.584155
//MapCenterLongitude=56.245727
//Kharg Island
//MapCenterLatitude=29.2697578
//MapCenterLongitude=50.2510527
//Reydarfjördur
//MapCenterLatitude=65.021641
//MapCenterLongitude=-13.988764
//Norfolk US
//MapCenterLatitude=36.93111111
//MapCenterLongitude=-76.33055556
//New York US
//MapCenterLatitude=40.548803
//MapCenterLongitude=-74.038944
//Rota Spain
//MapCenterLatitude=36.622941
//MapCenterLongitude=-6.342686
//Solomons
//MapCenterLatitude=-9.144619
//MapCenterLongitude=160.189064

//MapCenterLatitude=30.386823458
//MapCenterLongitude=53.62415257

//MapCenterLatitude=27.199160915
//MapCenterLongitude=56.2132273

//Finnish Bay entrance
//MapCenterLatitude=59.472066
//MapCenterLongitude=21.712637

//MapCenterLatitude=76.08306763993095
//MapCenterLongitude=15.250523315370913

//MapCenterLatitude=50
//MapCenterLongitude=150

//MapCenterLatitude=70
//MapCenterLongitude=-16

//Falklands
//MapCenterLatitude=-50.5
//MapCenterLongitude=-57.5

//Gibraltar
//MapCenterLatitude=35.9
//MapCenterLongitude=-7

//Arctics
//MapCenterLatitude=80.4
//MapCenterLongitude=2.3

//Jutland
//MapCenterLatitude=56.34
//MapCenterLongitude=6.94

MapCenterLatitude=-30
MapCenterLongitude=-30

[Mission]
PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

Taskforce1_UI=Default
Taskforce2_UI=Default

Taskforce1_NumberOfFormations=0
Taskforce1_Formation1=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel7,Taskforce1Vessel8,Taskforce1Vessel9,Taskforce1Vessel10|TF Rogov|Box|1.0
Taskforce2_NumberOfFormations=0
Taskforce2_Formation1=Taskforce2Vessel1,Taskforce2Vessel2|Test
#Taskforce1_Formation2=Taskforce1Aircraft1,Taskforce1Aircraft2,Taskforce1Aircraft3,Taskforce1Aircraft4|Air One|Vic|0.25

NumberOfTaskforce1LandUnits=

NumberOfTaskforce1Vessels=1
NumberOfTaskforce2Vessels=0
NumberOfNeutralVessels=

NumberOfTaskforce1Submarines=0
NumberOfTaskforce2Submarines=0
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=0
NumberOfTaskforce2Aircraft=0
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=0
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[Taskforce1Aircraft1]
Type=usn_a-7e
usn_a-6e
usn_a-7e
SquadronReference=Default
LoadoutVariant=SEAD
#LoadoutVariant=Default
#LoadoutVariant=LandStrikeShortRange
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,2000.4,5
#Waypoints=25.1,30000.0,250.0 | 50.0,10000,230.0
Heading=180

[Taskforce1Aircraft2]
Type=usn_f-14a
SquadronReference=Default
LoadoutVariant=Default
#LoadoutVariant=Default
#LoadoutVariant=LandStrikeShortRange
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,10000.0,-5
#Waypoints=25.1,30000.0,250.0 | 50.0,10000,230.0
Heading=180

[Taskforce1Aircraft3]
Type=usn_f-14a
SquadronReference=Default
LoadoutVariant=Default
#LoadoutVariant=Default
#LoadoutVariant=LandStrikeShortRange
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,10000.0,2.5
#Waypoints=25.1,30000.0,250.0 | 50.0,10000,230.0
Heading=180

[Taskforce1Aircraft4]
Type=usn_f-14a
SquadronReference=Default
LoadoutVariant=Default
#LoadoutVariant=Default
#LoadoutVariant=LandStrikeShortRange
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,10000.0,-2.5
#Waypoints=25.1,30000.0,250.0 | 50.0,10000,230.0
Heading=180

[Taskforce2Aircraft1]
Type=usn_a-7e
usn_a-6e
usn_a-7e
SquadronReference=Default
LoadoutVariant=SEAD
#LoadoutVariant=Default
#LoadoutVariant=LandStrikeShortRange
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=0,10000.4,5
#Waypoints=25.1,30000.0,250.0 | 50.0,10000,230.0
Heading=180

[Taskforce1Vessel1]
Type=wp_bpk_udaloy
usn_clg_oklahoma_city
wp_bpk_kara
wp_em_sovremenny
usn_cg_belknap
usn_cgn_virginia
usn_bb_iowa
ir_fab_boghammar
wp_bpk_kara
wp_cv_orel
usn_cv_kitty_hawk
wp_bpk_udaloy
rn_dd_c-class
wp_bdk_ivan_rogov
wp_mrk_nanuchka
VariantReference=Variant1
RelativePositionInNM=0,0,0
Heading=0
Telegraph=0

[Taskforce1Vessel2]
Type=usn_ff_garcia
wp_ptg_osa1
VariantReference=Random
#PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=-0.3,0,0
#Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce1Vessel3]
Type=wp_ptg_osa1
VariantReference=Random
PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=1,0,0
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce1Vessel4]
Type=wp_ptg_osa1
VariantReference=Random
PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=0,0,1
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce1Vessel5]
Type=wp_ptg_osa1
VariantReference=Random
PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=0,0,-1
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce1Vessel6]
Type=wp_ptg_osa1
VariantReference=Random
PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=1,0,1
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce1Vessel7]
Type=wp_ptg_osa1
VariantReference=Random
PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=-1,0,1
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce1Vessel8]
Type=wp_ptg_osa1
VariantReference=Random
PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=1,0,-1
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce1Vessel9]
Type=wp_ptg_osa1
VariantReference=Random
PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=-1,0,-1
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce1Vessel10]
Type=wp_ptg_osa1
VariantReference=Random
PositionRelativeTo=Taskforce1Vessel1
RelativePositionInNM=-2,0,-1
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=0

[Taskforce2Vessel1]
Type=usn_cg_belknap
wp_bdk_ivan_rogov
usn_bb_iowa
wp_bpk_udaloy
wp_cv_orel
wp_bdk_ivan_rogov
wp_mrk_nanuchka
RadarsActive=True
VariantReference=Default
RelativePositionInNM=0,0,-5
Heading=90
Telegraph=3

[Taskforce2Vessel2]
Type=wp_mrk_nanuchka
wp_cv_orel
wp_bdk_ivan_rogov
wp_mrk_nanuchka
RadarsActive=True
VariantReference=Default
RelativePositionInNM=-2,0,-1
Waypoints=FollowLoose,Taskforce1Vessel1,ownPos
Heading=Parent
Telegraph=3

[NeutralVessel1]
Type=civ_ms_ritina
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=-1,0,1
Heading=240
Telegraph=5

[Taskforce1Submarine1]
Type=wp_ssgn_charlie2
wp_ssn_alfa
wp_ssn_victor2
wp_ssn_november
wp_ssn_alfa
wp_ssgn_oscar1
wp_ssgn_echo2
wp_ssgn_charlie2
wp_ssbn_yankee
wp_ssbn_delta3
wp_ss_tango
usn_ssbn_franklin
usn_ssn_sturgeon
wp_ss_foxtrot
wp_ssn_victor3
usn_ssn_los_angeles
CrewSkill=Seasoned
VariantReference=Variant1
TowedArrayDeployed=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=0,p,0
Waypoints=Turn,0,100,current
Heading=180
Telegraph=1

[Taskforce2Submarine1]
Type=usn_ssn_sturgeon
usn_ssn_los_angeles
wp_ssn_alfa
wp_ssn_victor3
wp_ssn_victor3 //wp_ssgn_oscar1 //usn_ssn_los_angeles //wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
VariantReference=Variant1
TowedArrayDeployed=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=0,p,-10
Heading=90
Telegraph=1

[Taskforce1Helicopter1]
Type=wp_ka-27
usn_sh-2f
wp_ka-27
usn_sh-3h
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNM=0,500,0.5
Heading=90

[PlayerSubmarine2]
Type=wp_ssgn_echo2
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=10,-200,140
Heading=270
Telegraph=0

[EnemySubmarine1]
Type=usn_ssn_los_angeles //usn_ssn_los_angeles //wp_ssgn_charlie1 //usn_ssn_sturgeon //wp_ssgn_charlie1
VariantReference=Variant1
ActiveSonarsEnabled=False
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=13.5,-50,17.5
Heading=220
Telegraph=5

[EnemyAircraft1]
Type=usn_a-7e //usn_ea-6b //usn_s-3a //wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=PrecisionStrike
RelativePositionInKm=4,500,2
Heading=10

[EnemyAircraft2]
Type=usn_a-7e
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=PrecisionStrike
RelativePositionInKm=20,600,30
Heading=10

[PlayerAircraft1]
Type=usn_a-7e
wp_tu-95rt
wp_tu-16k //usn_s-3a //usn_a-7e //usn_ea-6b
VariantReference=Default
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Default
RelativePositionInKm=20,20000,30
Heading=10

[PlayerAircraft2]
Type=usn_a-7e
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Test
RelativePositionInKm=40,600,30
Heading=60

[PlayerAircraft3]
Type=usn_f-14a
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25.05,9500.0,100.0
LoadoutVariant=Default
Heading=10

[PlayerAircraft4]
Type=wp_mig-23
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25.05,9500.0,150.0
Heading=10

[PlayerAircraft5]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=8,10000,-20
Heading=10
LoadoutVariant=Default

[PlayerAircraft6]
Type=usn_f-14a
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=8,9000,-25
LoadoutVariant=Default
Heading=10

[PlayerHelicopter1]
Type=usn_sh-2f //usn_sh-2f
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20,40,18.5
#Waypoints=25,40,40
Heading=90

[EnemyAircraft3]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Loadout1
RelativePositionInKm=182,10000,180
Heading=220

[EnemyAircraft4]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Loadout1
RelativePositionInKm=183,10000,180
Heading=220

[EnemyAircraft5]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Loadout1
RelativePositionInKm=184,10000,180
Heading=220

[EnemyAircraft6]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Loadout1
RelativePositionInKm=-0.1,10000.0,-20.0
Heading=220

[EnemyHelicopter1]
Type=usn_sh-2f
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20,2500,37.5
Heading=90

[EnemyHelicopter2]
Type=usn_sh-2f
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=30,2500,-17.5
Heading=90

[EnemyHelicopter3]
Type=usn_sh-2f
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20,2500,47.5
Heading=90

[EnemyHelicopter4]
Type=usn_sh-2f
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=30,2500,17.5
Heading=90

[EnemyHelicopter5]
Type=usn_sh-2f
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25,2500,35
Heading=90

[EnemyHelicopter6]
Type=usn_sh-2f
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=35,2500,25
Heading=90