[Debug]
LogMode=Martin

# Overrides of usersettings.ini
DisableTerrain=True
DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
AllowEnemyUnitsAttackPlayer=False
DisableStrategicMap=False
#-----------------------------

TestAiDetection=True

[Environment]
Date=1974,5,9
Time=12,30

SeaState=4     // 0 ... 12
Clouds=Clear

#Weather=Rain,Snow,Fog //Supported values:Rain,Snow,Fog,Thunderstorm

MuseumMission=False

NumberOfPlayerVessels=25
NumberOfEnemyVessels=25
NumberOfNeutralVessels=0
NumberOfPlayerSubmarines=0
NumberOfEnemySubmarines=0
NumberOfNeutralSubmarines=0
NumberOfPlayerAircraft=0
NumberOfEnemyAircraft=0
NumberOfNeutralAircraft=0
NumberOfPlayerHelicopters=0
NumberOfEnemyHelicopters=0
NumberOfNeutralHelicopters=0

//Bergen Norway
//MapCenterLatitude=60.407
//MapCenterLongitude=5.289166
//GIUK
MapCenterLatitude=58
MapCenterLongitude=-23

[PlayerVessel1]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-2,0,-2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel2]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-1,0,-2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel3]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=0,0,-2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel4]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=1,0,-2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel5]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=2,0,-2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel6]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-2,0,-1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel7]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-1,0,-1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel8]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=0,0,-1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel9]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=1,0,-1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel10]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=2,0,-1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel11]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-2,0,0
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel12]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-1,0,0
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel13]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=0,0,0
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel14]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=1,0,0
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel15]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=2,0,0
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel16]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-2,0,1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel17]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-1,0,1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel18]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=0,0,1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel19]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=1,0,1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel20]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=2,0,1
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel21]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-2,0,2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel22]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=-1,0,2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel23]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=0,0,2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel24]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=1,0,2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[PlayerVessel25]
Type=usn_dd_spruance
VariantReference=Variant1
RelativePositionInNm=2,0,2
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

// -------------------------------------------------------------------------------

[EnemyVessel1]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-22,0,-22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel2]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-21,0,-22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel3]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=20,0,-22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel4]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=21,0,-22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel5]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=22,0,-22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel6]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-22,0,-21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel7]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-21,0,-21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel8]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=20,0,-21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel9]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=21,0,-21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel10]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=22,0,-21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel11]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-22,0,20
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel12]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-21,0,20
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel13]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=20,0,20
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel14]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=21,0,20
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel15]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=22,0,20
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel16]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-22,0,21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel17]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-21,0,21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel18]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=20,0,21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel19]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=21,0,21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel20]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=22,0,21
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel21]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-22,0,22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel22]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=-21,0,22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel23]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=20,0,22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel24]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=21,0,22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True

[EnemyVessel25]
Type=wp_bpk_udaloy
VariantReference=Variant1
RelativePositionInNm=22,0,22
Heading=270
Telegraph=0
VisualSystemsOn=True
RadarsActive=True
TowedArrayDeployed=True
ActiveSonarsEnabled=True
