[Debug]
#LogMode=Ivan
#DisableTerrain=True

#AllowEnemyUnitsAttackPlayer=False
#TestAiDetection=True

[Environment]
Date=1974,5,9
Time=12,0

SeaState=4     // 0 ... 12
Clouds=Broken

NumberOfPlayerVessels=2
NumberOfEnemyVessels=2
NumberOfNeutralVessels=0
NumberOfPlayerSubmarines=0
NumberOfEnemySubmarines=1
NumberOfNeutralSubmarines=0
NumberOfPlayerAircraft=1
NumberOfEnemyAircraft=0
NumberOfNeutralAircraft=0
NumberOfPlayerHelicopters=0
NumberOfEnemyHelicopters=0
NumberOfNeutralHelicopters=0

//North of Crete
//MapCenterLatitude=36.103398
//MapCenterLongitude=24.815894
//Bergen Norway
//MapCenterLatitude=60.407
//MapCenterLongitude=5.289166
//Tokyo Bay
//MapCenterLatitude=35.279829
//MapCenterLongitude=139.392115
//Narvik Fjord
//MapCenterLatitude=68.252551
//MapCenterLongitude=17.072467
//Emden
//MapCenterLatitude=53.307391
//MapCenterLongitude=7.145060
//Murmansk
//MapCenterLatitude=68.999203
//MapCenterLongitude=33.036945
//Archangelsk
//MapCenterLatitude=64.55
//MapCenterLongitude=40.5
//Niigata
//MapCenterLatitude=37.9497108
//MapCenterLongitude=139.0016708
//Honolulu
//MapCenterLatitude=21.3400792
//MapCenterLongitude=-157.9728127
//Serengeti
//MapCenterLatitude=-2.1189069
//MapCenterLongitude=34.1733967
//Hawaii
//MapCenterLatitude=20.466
//MapCenterLongitude=-156.4328
//Port Moresby
//MapCenterLatitude=-9.570733
//MapCenterLongitude=147.116973
//Iceland South
//MapCenterLatitude=63.796061
//MapCenterLongitude=-22.552217
//GIUK
//MapCenterLatitude=58
//MapCenterLongitude=-23
//Gremikha USSR
//MapCenterLatitude=68.05972222
//MapCenterLongitude=39.51361111
//Straits of Hormuz
//MapCenterLatitude=26.584155
//MapCenterLongitude=56.245727
//Kharg Island
//MapCenterLatitude=29.2697578
//MapCenterLongitude=50.2510527
//Reydarfjördur
//MapCenterLatitude=65.021641
//MapCenterLongitude=-13.988764
//Norfolk US
MapCenterLatitude=36.93111111
MapCenterLongitude=-76.33055556
//New York US
//MapCenterLatitude=40.548803
//MapCenterLongitude=-74.038944
//Rota Spain
//MapCenterLatitude=36.622941
//MapCenterLongitude=-6.342686
//Solomons
//MapCenterLatitude=-9.144619
//MapCenterLongitude=160.189064

//MapCenterLatitude=30.386823458
//MapCenterLongitude=53.62415257

//MapCenterLatitude=27.199160915
//MapCenterLongitude=56.2132273

//Finnish Bay entrance
//MapCenterLatitude=59.472066
//MapCenterLongitude=21.712637

//MapCenterLatitude=76.08306763993095
//MapCenterLongitude=15.250523315370913

[PlayerVessel1]
Type=usn_ffg_oliver_hazard_perry //usn_ffg_oliver_hazard_perry //wp_bpk_kara //usn_dd_spruance //wp_bpk_udaloy  //wp_skr_krivak1 //wp_takr_kiev //wp_pkr_moskva //usn_cv_kitty_hawk 
VariantReference=Variant1
TowedArrayDeployed=True
ActiveSonarsEnabled=False
TowedDecoyDeployed=False
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=10,0.0,20
RelativePositionInKm=15,0,35
#RelativePositionInKm=0,0,0
SingleUnitBehaviour=ai/SingleUnitBehaviours/UserUnitTest
Heading=350
Telegraph=1

[PlayerVessel2]
Type=usn_ffg_oliver_hazard_perry //usn_dd_gearing //wp_rkr_kynda
VariantReference=Variant1
RelativePositionInKm=10,0,20
TowedArrayDeployed=True
Heading=350
Telegraph=1

[PlayerVessel3]
Type=wp_ptg_osa1
VariantReference=Variant1
RelativePositionInKm=10,0,-15
Heading=350
Telegraph=3

[EnemyVessel1]
Type=usn_dd_spruance //wp_ptg_osa1 //wp_bpk_kara //wp_rkr_kynda //wp_takr_kiev //usn_dd_spruance
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
TowedArrayDeployed=True
ActiveSonarsEnabled=True
TowedDecoyDeployed=False
RelativePositionInKm=21.3,0,8.8
Heading=270
Telegraph=3

[EnemyVessel2]
Type=wp_rkr_kynda
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
TowedArrayDeployed=True
ActiveSonarsEnabled=True
TowedDecoyDeployed=False
RelativePositionInKm=21.3,0,15
Heading=270
Telegraph=3

[NeutralVessel1]
Type=civ_ms_ritina
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=-1,0,1
Heading=240
Telegraph=5

[PlayerSubmarine1]
Type=usn_ssn_los_angeles //wp_ssn_victor3 //wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
VariantReference=Variant1
TowedArrayDeployed=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=13.5,-60,16.5
Heading=270
Telegraph=1

[PlayerSubmarine2]
Type=wp_ssgn_echo2
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=10,-200,140
Heading=270
Telegraph=0

[EnemySubmarine1]
Type=wp_ssn_victor3 //usn_ssn_sturgeon //wp_ssgn_charlie1
VariantReference=Variant1
ActiveSonarsEnabled=False
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20,-100,26
Heading=180
Telegraph=5

[EnemyAircraft1]
Type=usn_a-7e //usn_ea-6b //usn_s-3a //wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=IronHand
RelativePositionInKm=40,500,25
Heading=10

[EnemyAircraft2]
Type=usn_a-7e
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=PrecisionStrike
RelativePositionInKm=20,600,30
Heading=10

[PlayerAircraft1]
Type=usn_a-7e //usn_ea-6b
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Test
RelativePositionInKm=20,600,30
Heading=10

[PlayerAircraft2]
Type=usn_a-6e
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Attack
RelativePositionInKm=40,600,30
Heading=60

[PlayerAircraft3]
Type=usn_f-14a
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25.05,9500.0,100.0
LoadoutVariant=Default
Heading=10

[PlayerAircraft4]
Type=wp_mig-23
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25.05,9500.0,150.0
Heading=10

[PlayerAircraft5]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=8,10000,-20
Heading=10
LoadoutVariant=Default

[PlayerAircraft6]
Type=usn_f-14a
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=8,9000,-25
LoadoutVariant=Default
Heading=10

[PlayerHelicopter1]
Type=usn_sh-2f
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20,40,18.5
Heading=90

[EnemyAircraft3]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Loadout1
RelativePositionInKm=182,10000,180
Heading=220

[EnemyAircraft4]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Loadout1
RelativePositionInKm=183,10000,180
Heading=220

[EnemyAircraft5]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Loadout1
RelativePositionInKm=184,10000,180
Heading=220

[EnemyAircraft6]
Type=wp_tu-22m2
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
LoadoutVariant=Loadout1
RelativePositionInKm=-0.1,10000.0,-20.0
Heading=220