[Environment]
Date=1974,5,9
Time=14,15

SeaState=4     // 0 ... 12
Clouds=Scattered

NumberOfPlayerVessels=2
NumberOfEnemyVessels=1 //1
NumberOfNeutralVessels=0
NumberOfPlayerSubmarines=1
NumberOfEnemySubmarines=1
NumberOfNeutralSubmarines=0
NumberOfPlayerAircraft=3
NumberOfEnemyAircraft=3
NumberOfNeutralAircraft=0
NumberOfPlayerHelicopters=1
NumberOfEnemyHelicopters=0
NumberOfNeutralHelicopters=0

//Bergen Norway
//MapCenterLatitude=60.407
//MapCenterLongitude=5.289166
//Tokyo Bay
//MapCenterLatitude=35.279829
//MapCenterLongitude=139.392115
//Narvik Fjord
//MapCenterLatitude=68.426695
//MapCenterLongitude=17.137733
//Emden
//MapCenterLatitude=53.307391
//MapCenterLongitude=7.145060
//Murmansk
//MapCenterLatitude=68.999203
//MapCenterLongitude=33.036945
//Archangelsk
//MapCenterLatitude=64.55
//MapCenterLongitude=40.5
//Niigata
//MapCenterLatitude=37.9497108
//MapCenterLongitude=139.0016708
//Honolulu
//MapCenterLatitude=21.3400792
//MapCenterLongitude=-157.9728127
//Serengeti
//MapCenterLatitude=-2.1189069
//MapCenterLongitude=34.1733967
//Hawaii
//MapCenterLatitude=20.466
//MapCenterLongitude=-156.4328
//Port Moresby
//MapCenterLatitude=-9.570733
//MapCenterLongitude=147.116973
//Iceland South
//MapCenterLatitude=63.796061
//MapCenterLongitude=-22.552217
//GIUK
//MapCenterLatitude=58
//MapCenterLongitude=-23
//Gremikha USSR
//MapCenterLatitude=68.05972222
//MapCenterLongitude=39.51361111
//Straits of Hormuz
//MapCenterLatitude=26.584155
//MapCenterLongitude=56.245727
//Kharg Island
MapCenterLatitude=29.2697578
MapCenterLongitude=50.2510527
//Reydarfjördur
//MapCenterLatitude=65.021641
//MapCenterLongitude=-13.988764
//Norfolk US
//MapCenterLatitude=36.93111111
//MapCenterLongitude=-76.33055556
//New York US
//MapCenterLatitude=40.548803
//MapCenterLongitude=-74.038944
//Rota Spain
//MapCenterLatitude=36.622941
//MapCenterLongitude=-6.342686
//Solomons
//MapCenterLatitude=-9.144619
//MapCenterLongitude=160.189064

//MapCenterLatitude=30.386823458
//MapCenterLongitude=53.62415257

//MapCenterLatitude=27.199160915
//MapCenterLongitude=56.2132273

[PlayerVessel1]
Type=usn_dd_spruance
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInKm=10,0.0,20
RelativePositionInKm=8,0,-15
#RelativePositionInKm=0,0,0
Heading=350
Telegraph=0

[PlayerVessel2]
Type=wp_rkr_kynda
VariantReference=Variant1
RelativePositionInKm=40,0,-15
Heading=350
Telegraph=3

[EnemyVessel1]
Type=wp_skr_krivak1
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25,0,-15
Heading=270
Telegraph=3

[NeutralVessel1]
Type=civ_ms_ritina
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#RelativePositionInNM=18.6,0.0,24.75
#RelativePositionInNM=0.0,0.0,92.0
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=80,0,-50
RelativePositionInKm=-1,0,1
Heading=240
Telegraph=5

[PlayerSubmarine1]
Type=wp_ssgn_charlie1
#Type=wp_ssn_victor3
#Type=wp_ss_foxtrot
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=10,-200,-15
Heading=270
Telegraph=0

[EnemySubmarine1]
Type=wp_ssgn_charlie1
VariantReference=Variant1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=20,-200,20
Heading=220
Telegraph=1

[PlayerAircraft1]
Type=iriaf_f-4e
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=35.0,12500.0,30.0
Heading=120

[PlayerAircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=35.02,11550.0,30.02
Heading=120

[PlayerAircraft3]
Type=usn_f-14a
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=25.05,12500.0,30.0
Heading=210

[PlayerHelicopter1]
Type=usn_sh-2f
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=-0.1,100.0,-20.0
Heading=90

[EnemyAircraft1]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=10,11000,18
Heading=220

[EnemyAircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=11,11000,18
Heading=220

[EnemyAircraft3]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=12,12000,14
Heading=220

[EnemyAircraft4]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=183,10000,180
Heading=220

[EnemyAircraft5]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=184,10000,180
Heading=220

[EnemyAircraft6]
Type=wp_tu-22m2
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInKm=185,10000,180
Heading=220