[Debug]
#LogMode=Ivan
DevModeGUIScale=1      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
AllowEnemyUnitsAttackPlayer=True
#FullscreenStrategicMap=True
ContextMenuScale=1.2
ContextMenuFontSize=20
#-----------------------------

#MissionStartTextDM=

[Language_en]
Name=Test TMA mission
Description=Test TMA mission

[Environment]
Date=1982,4,2
Time=09,40

SeaState=2
Clouds=Scattered

MapCenterLatitude=27
MapCenterLongitude=-46


[Mission]
Difficulty=1

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

EnemyAIPlayerBehaviourPath=ai/NodeCanvas/AIPlayer
EnemyAIUnitBehaviourPath=ai/NodeCanvas/AIUnit
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Taskforce1_Nation=Vietnam
Taskforce2_Nation=USA

Taskforce1_UI=Default
Taskforce2_UI=Test


NumberOfTaskforce1LandUnits=

NumberOfTaskforce1Vessels=1
NumberOfTaskforce2Vessels=3
NumberOfNeutralVessels=0

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=0
NumberOfTaskforce2Aircraft=0
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[ ================================ Vessels =============================== ]
[Taskforce1Vessel1]
Type=wp_ptg_tarantul
VariantReference=Random
RelativePositionInNm=0,0,0
#RandomSpawnCenter=0,0,0
#RandomSpawnRange=15,30
#RandomSpawnDirection=-30,30
Heading=0
#Heading=Random
Telegraph=1

[------------------------------------------]
[Taskforce2Vessel1]
Type=usn_dd_gearing
#usn_ae_kilauea,usn_bb_iowa
VariantReference=Random
RelativePositionInNm=-20,0,0
Heading=0
Telegraph=1

[Taskforce2Vessel2]
Type=usn_dd_gearing
#usn_ae_kilauea,usn_bb_iowa
VariantReference=Random
RelativePositionInNm=0,0,30
Heading=0
Telegraph=1

[Taskforce2Vessel3]
Type=usn_dd_gearing
#usn_ae_kilauea,usn_bb_iowa
VariantReference=Random
RelativePositionInNm=-40,0,0
Heading=0
Telegraph=1

#RandomSpawnCenter=Taskforce1Vessel1
#RandomSpawnRange=5,10
#RandomSpawnDirection=-179,180

Heading=0
Telegraph=2

[------------------------------------------]
[ ============================== Submarines ============================== ]
[------------------------------------------]
[------------------------------------------]
[ =============================== Aircraft =============================== ]
[------------------------------------------]
[------------------------------------------]
[ ============================== Helicopters ============================= ]
[------------------------------------------]
[------------------------------------------]
[ ============================== Land Units ============================== ]
[------------------------------------------]
[------------------------------------------]
