[Debug]
LogMode=Ivan

# Overrides of usersettings.ini
#DisableTerrain=True
DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons

AllowEnemyUnitsAttackPlayer=True
EnemyWeaponStatus=Free
TestAiDetection=True

MissionStartTextDM=Test night engagement Indian OSAs vs Pakistani forces


[Language_en]
Name=Shershens Torpedo Run
Description=Hypothetical: Late evening Shershens attack on C-class DD

[Environment]
Date=1971,4,12
Time=16,50

SeaState=4     // 0 ... 12
Clouds=broken_2	//scattered_2 //broken	//scattered_1 //Clear

MapCenterLatitude=68.259
MapCenterLongitude=39.513

//south of Karachi
//MapCenterLatitude=24.48
//MapCenterLongitude=66.71
//Bergen Norway
//MapCenterLatitude=60.407
//MapCenterLongitude=5.289166
//Tokyo Bay
//MapCenterLatitude=35.279829
//MapCenterLongitude=139.392115
//Narvik Fjord
//MapCenterLatitude=68.426695
//MapCenterLongitude=17.137733
//Emden
//MapCenterLatitude=51.307391
//MapCenterLongitude=7.645060
//Murmansk
//MapCenterLatitude=68.999203
//MapCenterLongitude=33.036945
//Archangelsk
//MapCenterLatitude=64.55
//MapCenterLongitude=40.5
//Niigata
//MapCenterLatitude=37.9497108
//MapCenterLongitude=139.0016708
//Honolulu
//MapCenterLatitude=21.3400792
//MapCenterLongitude=-157.9728127
//Serengeti
//MapCenterLatitude=-2.1189069
//MapCenterLongitude=34.1733967
//Hawaii
//MapCenterLatitude=20.466
//MapCenterLongitude=-156.4328
//Port Moresby
//MapCenterLatitude=-9.570733
//MapCenterLongitude=147.116973
//Iceland South
//MapCenterLatitude=63.796061
//MapCenterLongitude=-22.552217
//GIUK
//MapCenterLatitude=55
//MapCenterLongitude=-21
//Gremikha USSR
//MapCenterLatitude=68.05972222
//MapCenterLongitude=39.51361111
//Straits of Hormuz
//MapCenterLatitude=26.584155
//MapCenterLongitude=56.245727
//Kharg Island
//MapCenterLatitude=29.2697578
//MapCenterLongitude=50.2510527
//Reydarfjördur
//MapCenterLatitude=65.021641
//MapCenterLongitude=-13.988764
//Norfolk US
//MapCenterLatitude=36.93111111
//MapCenterLongitude=-76.33055556
//New York US
//MapCenterLatitude=40.548803
//MapCenterLongitude=-74.038944
//Rota Spain
//MapCenterLatitude=36.622941
//MapCenterLongitude=-6.342686

[Mission]
Difficulty=3

NumberOfTaskforce1Vessels=4
NumberOfTaskforce2Vessels=3
NumberOfNeutralVessels=0
NumberOfTaskforce1Submarines=0
NumberOfTaskforce2Submarines=0
NumberOfNeutralSubmarines=0
NumberOfTaskforce1Aircraft=0
NumberOfTaskforce2Aircraft=0
NumberOfNeutralAircraft=0
NumberOfTaskforce1Helicopters=0
NumberOfTaskforce2Helicopters=0
NumberOfNeutralHelicopters=0

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=India
Taskforce2_Nation=Pakistan


[Taskforce1Vessel1]
Type=wp_pt_shershen
//wp_pt_shershen_ins
//ir_ffg_alvand
//rn_dd_battle
//wp_pt_shershen-e
//ir_ptg_combattante_II
VariantReference=
RadarsActive=True
RelativePositionInNM=0,0,0
Heading=330
Telegraph=3
Waypoints=-50,0,-15

[Taskforce1Vessel2]
//MissionTarget=Protect
Type=wp_pt_shershen
//usn_dd_spruance
VariantReference=
RadarsActive=True
RelativePositionInNm=-0.5,0,-0.5
Heading=330
Telegraph=3
Waypoints=-50,0,-16

[Taskforce1Vessel3]
Type=wp_pt_shershen
//wp_ptg_osa1
VariantReference=
RadarsActive=True
RelativePositionInNm=1,0,-1
Heading=330
Telegraph=3
Waypoints=-50,0,-17

[Taskforce1Vessel4]
Type=wp_ptg_osa1
VariantReference=
RadarsActive=True
RelativePositionInNm=4,0,0
Heading=330
Telegraph=3
Waypoints=-50,0,-17

[---------- Taskforce2 Vessels----------]
[Taskforce2Vessel1]
//MissionTarget=Destroy
Type=rn_dd_battle
//rn_dd_c-class
//usn_dd_spruance
VariantReference=
RadarsActive=True
RelativePositionInNm=-4,0,-2
Heading=90
Telegraph=2
Waypoints=2,0,2

[Taskforce2Vessel2]
Type=rn_dd_c-class
VariantReference=
RadarsActive=True
RelativePositionInNm=-4.4,0,-2
Heading=90
Telegraph=2
Waypoints=2.4,0,2

[Taskforce2Vessel3]
Type=pak_msc_adjutant
VariantReference=
RelativePositionInNm=-4.1,0,-2.8
Heading=90
Telegraph=2
Waypoints=3,0,-1

[Taskforce2Vessel4]
Type=civ_ms_freighter_b
VariantReference=Variant1
RelativePositionInNm=-11,0,-4
Heading=90
Telegraph=3
Waypoints=595,0,-19

[---------- Neutral Vessels----------]
[NeutralVessel1]
#Italy goes from south west to east+
Type=civ_ms_mercur
VariantReference=Variant4
RelativePositionInNm=-5,0,5
Heading=41
Telegraph=2
Waypoints=20,0,-3|500,0,500

[NeutralVessel2]
#UK goes from north west to east+
Type=civ_ms_amra
VariantReference=Variant12
RelativePositionInNm=-6,0,2
Heading=90
Telegraph=3
Waypoints=-40,0,-2|-25,0,15|99,0,15|500,0,500

[NeutralVessel3]
#UK goes from south west to east+
Type=civ_ms_amra
VariantReference=Variant12
RelativePositionInNm=-30,0,-25
Heading=71
Telegraph=3
Waypoints=-20,0,-23|15,0-20|500,0,500

[NeutralVessel4]
#Italy goes from northeast to west+
Type=civ_ms_ritina
VariantReference=Variant12
RelativePositionInNm=16,0,10
Heading=246
Telegraph=3
Waypoints=-120,0,-40|-150,0,-500

[NeutralVessel5]
#Soviet, comes from north east to soutwest
Type=civ_ms_mercur
VariantReference=Variant1
RelativePositionInNm=18,0,12
Heading=244
Telegraph=5
Waypoints=-120,0,-40|-150,0,-500
#================================================================================ Submarines ================================================================================

#================================================================================ Aircraft ================================================================================
[Taskforce2Aircraft1]
Type=usn_f-14a
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=-30,5000,-100
Heading=220
Waypoints=-60,5000,-100|0,5000,-100|-60,5000,-100    //X - NM, Y - feet, Z - NM

[NeutralAircraft1]
Type=wp_tu-22m2
SquadronReference=Squadron1
RadarsActive=True
RelativePositionInNm=-30,10000,9
Heading=90
Telegraph=3
Waypoints=600,10000,9

[NeutralAircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron2
RadarsActive=True
RelativePositionInNm=-30.05,10000,9.05
Heading=90
Telegraph=3
Waypoints=600.05,10000,9.05

#================================================================================ Helicopters ================================================================================
