[General]
#Hidden=True
Type=Tutorial

[Language_en]
Name=Officer Training 1 - Basic Vessel Controls
Description=Tutorial mission
Taskforce1VictoryMessage=Victory!|Congratulations, commander! You are victorious!
Taskforce1DefeatMessage=Defeat|You failed to complete mission objectives, commander.

Training_VO_Intro_Message_1=<size=22>Officer Training 1 - Basic Vessel Controls</size>|Welcome aboard the Oliver Hazard Perry Captain! \nLet's get you up to speed on commanding your first vessel shall we? \n
Training_VO_1_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|Situational awareness is one of the many key elements if we want to go up against OPFOR. \nLet's get you squared away with the Map Controls.
Training_VO_2_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|Using the left mouse button and dragging will pan the map window.
Training_VO_3_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|You can also zoom in and out of the map by scrolling with the mouse wheel.
Training_VO_4_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|If you need to recenter the minimap on the unit your are spectating, hit <color={*}ffc68c>{Key_CenterToTarget}</color> to recenter the minimap.
Training_VO_5_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|If you need to move the map to another part of your game window, you can use the cursor and Left Click and Drag anywhere on the black section where is says Tactical Display. This also applies to resizing the Tac Display. Using your cursor, you can move over the boundaries of the tac display window to resize it.
Training_VO_6_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|Let's trying looking at the global map Captain. You can either hit the <color={*}ffc68c>{Key_MapToggleFullscreen}</color> key or click on the Maximize Button the map window to view the full map. If you need to exit the map, click on the X button on the top right side of the window. (Mention pulling up minimap again)
Training_VO_7_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|Let's return to our ship and move the vessel with direct control first. All vessels and Submarines in Sea Power use a Engine Order Telegraph (EOT) control scheme. This means a ship can move the following speeds: Back Full, Stop, Ahead 1/3, Ahead 2/3, Ahead Standard, Ahead Full, and Ahead Flank.
Training_VO_8_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|Ahead standard usually means to proceed forward at the most economical fuel efficient speed for that ship type. Ahead full usually means to proceed forward at 50% of the maximum speed for that ship type. Ahead flank usually means to proceed forward at 100% or the maximum speed for that ship type.
Training_VO_9_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|If you hit <color={*}ffc68c>{Key_IncreaseTelegraph}</color> once, the ship mode will change to direct control and it's speed will change from the stop order to the Ahead 1/3 order. Hitting <color={*}ffc68c>{Key_IncreaseTelegraph}</color> again will order the engines to Ahead 2/3 and so on. We can reduce our speed with the <color={*}ffc68c>{Key_DecreaseTelegraph}</color> key accordingly. It will generally be easier to set the speed of your vessel with the SPD button at the bottom left, beside the ship name however.
Training_VO_10_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|When it comes to turning the ship, you can shift the rudder with <color={*}ffc68c>{Key_RudderLeft}</color> and <color={*}ffc68c>{Key_RudderRight}</color> keys. Turning the vessel with the <color={*}ffc68c>{Key_RudderLeft}</color> and <color={*}ffc68c>{Key_RudderRight}</color> keys will set the rudder to 5 Degree increments to the left or right respectively. Hitting the opposite key will reset the rudder to 0 degrees.
Training_VO_11_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|Keep in mind you can also use the mini-map and set a waypoint to let your fellow officers handle the controls. You can right click anywhere on the mini-map or map while the vessel is selected to set a waypoint. Your officers will now control the rudder and move to the assigned point at the speed you have set for this vessel. Feel free to change the speed as needed. If you need to set multiple waypoints, you can hold shift while placing a waypoint to queue up multiple move orders.
Training_VO_12_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|Let's get our Radar so we can see beyond what our eyes can see. You can right click on the ship and see a section called 'Sensors', if we click on this, we can turn on our air and surface radars now. These controls can also be accessed by clicking the EMCOM/Radio Routine button on the bottom right side of the screen. The EMCOM button in the sensor menu will shut off all active sensors, which can be useful for staying undected longer in a combat zone.
Training_VO_13_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|With our sensors now online, you may notice a yellow track has been added to our Tactical Display. This is a unidentified unit/ Any unidentified units will be marked as a track with a ID number. If Radar can detect a unit, the track will display a (r) to show radar is tracking it. Even when a unit is visible on radar, you will still need a unit to provide Visual Identification, or VID in most cases. You can have any unit VID a unkown track by having a selected unit, then right clicking on the unknown track.
Training_VO_14_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|
Training_VO_15_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|
Training_VO_16_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|
Training_VO_17_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|
Training_VO_18_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|
Training_VO_19_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|
Training_VO_2_Message=<size=22>Officer Training 1 - Basic Vessel Controls</size>|


[Environment]
Date=1974,11,18
Time=12,23
SeaState=4
Clouds=Clear
WindDirection=NE
MapCenterLatitude=38
MapCenterLongitude=7.17
MapInitialZoom=10

[Mission]
Difficulty=2
PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
Taskforce1_Nation=US
Taskforce2_Nation=WP
NumberOfTaskforce1LandUnits=0
NumberOfTaskforce2LandUnits=0
NumberOfNeutralLandUnits=0
NumberOfTaskforce1Vessels=1
NumberOfTaskforce2Vessels=1
NumberOfNeutralVessels=0
NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=0
NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=0
NumberOfNeutralAircraft=0
NumberOfTaskforce1Helicopters=1
NumberOfTaskforce2Helicopters=0
NumberOfNeutralHelicopters=0
Taskforce2_NumberOfFormations=
Taskforce2_Formation1=Taskforce2Vessel1,Taskforce2Vessel3,Taskforce2Vessel4,Taskforce2Vessel5,Taskforce2Vessel2|Test Formation|Loose
NumberOfTriggers=100


[Taskforce1Vessel1]
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant1
RelativePositionInNM=-1,0,-2
Heading=-90
Telegraph=0
Telegraph=0

[Taskforce2Vessel1]
Type=civ_ms_super_p
VariantReference=Variant1
StationRole=AAW
RelativePositionInNM=1,0,0
Heading=-90
Telegraph=2
Telegraph=0
Waypoints=Turn,0,20,current

[Taskforce2Vessel2]
Type=usn_ff_knox
VariantReference=Variant4
StationRole=ASW
RelativePositionInNM=1.49,0,-0.5
Heading=-90
Telegraph=4
Waypoints=Turn,0,20,current


[Taskforce2Vessel3]
Type=usn_ff_garcia
VariantReference=Variant10
StationRole=ASW
RelativePositionInNM=1.49,0,0.5
Heading=-90
Telegraph=4


[Taskforce2Vessel4]
Type=civ_ms_freighter_b
VariantReference=Variant2
RelativePositionInNM=2,0,0.02
Heading=-90
Telegraph=0

[Taskforce2Vessel5]
Type=usn_ddg_adams_early
VariantReference=Variant6
StationRole=ASW
RelativePositionInNM=3,0,0
Heading=-90
Telegraph=0

[Taskforce1Submarine1]
Type=wp_ssn_november
Type=wp_ssgn_charlie1
VariantReference=Variant2
VisualSystemsOn=False
RelativePositionInNM=-4.5,-100,-0.5
Heading=90
Telegraph=0

[Taskforce2Submarine1]
Type=usn_ssn_los_angeles
VariantReference=Variant2
VisualSystemsOn=False
RelativePositionInNM=0,-100,-0.5
Heading=90
Telegraph=0

[Taskforce1Helicopter1]
Undetectable=True
Type=wp_ka-27
SquadronReference=Squadron0
#VisualSystemsOn=False
RadarsActive=True
RelativePositionInNM=0,3999,0
Heading=29

[Taskforce1Helicopter2]
Undetectable=True
Type=wp_ka-27
SquadronReference=Squadron0
#VisualSystemsOn=False
RadarsActive=True
RelativePositionInNM=-1,20,0
Heading=29
#SetSelected=True


[Taskforce1Aircraft1]
Undetectable=True
Type=wp_il-38
SquadronReference=Squadron0
#VisualSystemsOn=False
RadarsActive=True
RelativePositionInNM=0,800,0
Heading=90
Waypoints=Turn,0,20,current
SetSelected=True

[ ============================== Triggers ============================= ]
[Trigger1]  #Mission exit
Name=Mission exit
Description=Trigger to end mission automaticaly
Disabled=True
Condition_Type=Time
Condition_Time=10
Action_EndMission=True

[Trigger2]  #Start Message
Name=Start Message
Description=Message displayed at the beginning of the mission
Condition_Type=Time
Condition_Time=0.5
Action_Taskforce1_Message=Training_VO_Intro_Message_1
#Action_Taskforce1_VoiceMessage=ActiveSonarOn
Action_EnableTriggers=Trigger3
Action_ReactivateTriggers=Trigger3

[Trigger3] # Message
Name=Message 1
Disabled=True
Condition_Type=Time
Condition_Time=1
Action_Taskforce1_Message=Training_VO_1_Message
Action_Taskforce1_Intel=Training_VO_1_Message
Action_EnableTriggers=Trigger4
Action_ReactivateTriggers=Trigger4

[Trigger4] # Message
Name=Message 2
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_2_Message
Action_Taskforce1_Intel=Training_VO_2_Message
Action_EnableTriggers=Trigger5
Action_ReactivateTriggers=Trigger5

[Trigger5] # Message
Name=Message 3
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_3_Message
Action_Taskforce1_Intel=Training_VO_3_Message
Action_EnableTriggers=Trigger6
Action_ReactivateTriggers=Trigger6

[Trigger6] # Message
Name=Message 4
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_4_Message
Action_Taskforce1_Intel=Training_VO_4_Message
Action_EnableTriggers=Trigger7
Action_ReactivateTriggers=Trigger7

[Trigger7] # Message
Name=Message 5
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_5_Message
Action_Taskforce1_Intel=Training_VO_5_Message
Action_EnableTriggers=Trigger8
Action_ReactivateTriggers=Trigger8

[Trigger8] # Message
Name=Message 6
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_6_Message
Action_Taskforce1_Intel=Training_VO_6_Message
Action_EnableTriggers=Trigger9
Action_ReactivateTriggers=Trigger9

[Trigger9] # Message
Name=Message 7
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_7_Message
Action_Taskforce1_Intel=Training_VO_7_Message
Action_EnableTriggers=Trigger10
Action_ReactivateTriggers=Trigger10

[Trigger10] # Message
Name=Message 8
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_8_Message
Action_Taskforce1_Intel=Training_VO_8_Message
Action_EnableTriggers=Trigger11
Action_ReactivateTriggers=Trigger11

[Trigger11] # Message
Name=Message 9
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_9_Message
Action_Taskforce1_Intel=Training_VO_9_Message
Action_EnableTriggers=Trigger12
Action_ReactivateTriggers=Trigger12

[Trigger12] # Message
Name=Message 10
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_10_Message
Action_Taskforce1_Intel=Training_VO_10_Message
Action_EnableTriggers=Trigger13
Action_ReactivateTriggers=Trigger13

[Trigger13] # Message
Name=Message 11
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_11_Message
Action_Taskforce1_Intel=Training_VO_11_Message
Action_EnableTriggers=Trigger14
Action_ReactivateTriggers=Trigger14

[Trigger14] # Message
Name=Message 12
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_12_Message
Action_Taskforce1_Intel=Training_VO_12_Message
Action_EnableTriggers=Trigger15
Action_ReactivateTriggers=Trigger15

[Trigger15] # Message
Name=Message 13
Disabled=True
Condition_Type=Time
Condition_Time=2
Action_Taskforce1_Message=Training_VO_13_Message
Action_Taskforce1_Intel=Training_VO_13_Message
Action_EnableTriggers=Trigger16
Action_ReactivateTriggers=Trigger16

