

Synopsise: Convoy from point A to B. Condition: Dont loose  >50% transports

Player: Nato
Vessels:3-6 (Probably increse for big convoy)
Transports:5-20
All in 1 formation

Enemy: WP

Vessels: 1-2 formations along the route

Subs: 1-2 formations along the route

Aircraft: 1-2 formations along the route
1-2 spawn areas north or south of route



[Debug]
LogMode=Ivan
DevModeGUIScale=1      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons

AllowEnemyUnitsAttackPlayer=True

MissionStartTextDM=\n*This message will not appear in the final game, it is solely to convey the synopsis for the demo video.\n\n June, 1986 - The North Atlantic\n\nFollowing a massive blow on the Northern Front, Soviet submarines and Backfire bombers have crossed into the open Atlantic virtually unopposed. Instructed to prevent American reinforcements from landing in Europe, PACT submarines and aircraft make daily attacks on trans-Atlantic convoys. As NATO leadership scrambles to move submarines into the GIUK Gap to prevent further crossings into the Atlantic, the job of protecting the convoys on their dangerous two week voyage falls to the sailors of American tin cans.\n

[Language_en]
Name=Test Convoy Mission
Description=Instant Action test

[Environment]
Date=1986,6,9
Time=9,30

SeaState=5     // 0 ... 12
Clouds=Broken

Weather=Rain,Fog,Thunderstorm 
RainIntensity=500

MapCenterLatitude=45
MapCenterLongitude=-36

[Mission]
EnemyAIPlayerBehaviourPath=ai/NodeCanvas/AIPlayer
EnemyAIUnitBehaviourPath=ai/NodeCanvas/AIUnit
EnemyAIUnitOrdersFolder=ai/NodeCanvas/AIUnitOrders/

Difficulty=2

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=USA
Taskforce2_Nation=Soviet

NumberOfTaskforce1Vessels=10  //26
NumberOfTaskforce2Vessels=1//1
NumberOfNeutralVessels=
NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=0//2
NumberOfNeutralSubmarines=
NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=0//4
NumberOfNeutralAircraft=
NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=


Taskforce1_NumberOfFormations=1
Taskforce1_Formation1=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel7,Taskforce1Vessel8,Taskforce1Vessel9,Taskforce1Vessel10,Taskforce1Vessel11,Taskforce1Vessel12,Taskforce1Vessel13,Taskforce1Vessel14,Taskforce1Vessel15,Taskforce1Vessel16,Taskforce1Vessel17,Taskforce1Vessel18,Taskforce1Vessel19,Taskforce1Vessel20,Taskforce1Vessel22,Taskforce1Vessel23,Taskforce1Vessel24,Taskforce1Vessel25,Taskforce1Vessel26|NATO Convoy|LineAbreast|1.5|OverrideSpawnPositions

Taskforce2_NumberOfFormations=0
Taskforce2_Formation1=Taskforce2Vessel1,Taskforce2Vessel3|MRK Patrol


[ ================================ Vessels =============================== ]
#Single
[Taskforce1Vessel1] #Pharris FF-1094
Type=usn_ff_knox
VariantReference=Variant43
RadarsActive=True
LoadoutVariant=CIWS
RelativePositionInNM=0,0,20
Heading=90
Telegraph=3
Waypoints=1120,0,20
TowedArrayDeployed=True

#Northern row
[Taskforce1Vessel2] #Gary FFG-51
SpawnChance=0
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant41
Telegraph=3
Waypoints=1120,0,0

[Taskforce1Vessel3] #Reuben James FFG-57
SpawnChance=0
Type=usn_ffg_oliver_hazard_perry
VariantReference=Variant47
Telegraph=3
//Attack=Taskforce1Vessel6,2,usn_rgm-84,2

#Middle row
[Taskforce1Vessel4] #Merchant
Type=usn_ae_kilauea,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions

Telegraph=3

[Taskforce1Vessel5] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3

[Taskforce1Vessel6] #Merchant
Type=usn_ae_kilauea,usn_aoe_sacramento,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3

#Southern row
[Taskforce1Vessel7] #Merchant
Type=civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3

[Taskforce1Vessel8] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3


#Middle row
[Taskforce1Vessel9] #Merchant
Type=usn_ae_kilauea,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions

Telegraph=3

[Taskforce1Vessel10] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3

[Taskforce1Vessel11] #Merchant
Type=usn_ae_kilauea,usn_aoe_sacramento,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3

#Southern row
[Taskforce1Vessel12] #Merchant
Type=civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3

[Taskforce1Vessel13] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3


#Middle row
[Taskforce1Vessel14] #Merchant
Type=usn_ae_kilauea,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions

Telegraph=3

[Taskforce1Vessel15] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3

[Taskforce1Vessel16] #Merchant
Type=usn_ae_kilauea,usn_aoe_sacramento,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3

#Southern row
[Taskforce1Vessel17] #Merchant
Type=civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3

[Taskforce1Vessel18] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3


#Middle row
[Taskforce1Vessel19] #Merchant
Type=usn_ae_kilauea,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions

Telegraph=3

[Taskforce1Vessel20] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3

[Taskforce1Vessel21] #Merchant
Type=usn_ae_kilauea,usn_aoe_sacramento,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3

#Southern row
[Taskforce1Vessel22] #Merchant
Type=civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3

[Taskforce1Vessel23] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3
[Taskforce1Vessel24] #Merchant
Type=usn_ae_kilauea,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions

Telegraph=3

[Taskforce1Vessel25] #Merchant
Type=usn_lpd_austin,usn_lst_newport,civ_ms_amra,civ_ms_car_carrier_a,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_roro_a,civ_ms_super_p
VariantReference=Random
LoadoutVariant=MilitaryVehicles
Telegraph=3

[Taskforce1Vessel26] #Merchant
Type=usn_ae_kilauea,usn_aoe_sacramento,civ_ms_act_1,civ_ms_amra,civ_ms_encounter,civ_ms_freighter_a,civ_ms_freighter_b,civ_ms_freighter_d,civ_ms_super_p
VariantReference=Random
LoadoutVariant=Munitions
Telegraph=3
[------------------------------------------]
[Taskforce2Vessel1]
Type=wp_rkr_kynda

VariantReference=Random
RadarsActive=True

RandomSpawnCenter=Taskforce1Vessel1
RandomSpawnRange=35,40
RandomSpawnDirection=-179,180

Heading=Parent
Telegraph=2
Waypoints=Turn,0,5,0|ToSpawnPosition,Taskforce1Vessel1,0,300|195,0,-70|220,0,-130|1500,0,-200
Attack=Taskforce1Vessel4,25,wp_ss-n-3,2|Taskforce1Vessel5,25,wp_ss-n-3,2|Taskforce1Vessel6,120,wp_ss-n-3,2|Taskforce1Vessel7,120,wp_ss-n-3,2
[------------------------------------------]

[ ============================== Submarines ============================== ]
[------------------------------------------]
[Taskforce1Submarine1]
Type=wp_ssn_victor3
VariantReference=Variant2
RelativePositionInNm=8,-200,28
Heading=192
Telegraph=2
Waypoints=2,-200,0|2,-400,2|-2,200,2|-2,200,-2|2,200,-2|2,200,2|-2,200,2||-2,200,-2|0,-200,1    //X - NM, Y - feet, Z - NM


[Taskforce2Submarine1]
Type=wp_ssn_victor3
VariantReference=Random
RelativePositionInNm=8,-200,28
Heading=192
Telegraph=2
Waypoints=2,-200,0|2,-400,2|-2,200,2|-2,200,-2|2,200,-2|2,200,2|-2,200,2||-2,200,-2|0,-200,1    //X - NM, Y - feet, Z - NM
Attack=Taskforce1Vessel1,310|Taskforce1Vessel1,310
TowedArrayDeployed=True

[Taskforce2Submarine2]
Type=wp_ssgn_charlie2
VariantReference=Random
RelativePositionInNm=0,-200,1
Heading=270
Telegraph=0
Waypoints=2,-200,0|2,-400,2|-2,200,2|-2,200,-2|2,200,-2|2,200,2|-2,200,2||-2,200,-2|0,-200,1    //X - NM, Y - feet, Z - NM
TowedArrayDeployed=True

[Taskforce2Submarine3]
Type=wp_ssn_victor3
VariantReference=Variant2
RelativePositionInNm=0,-200,1
Heading=270
Telegraph=0
Waypoints=2,-200,0|2,-400,2|-2,200,2|-2,200,-2|2,200,-2|2,200,2|-2,200,2||-2,200,-2|0,-200,1    //X - NM, Y - feet, Z - NM
TowedArrayDeployed=True

[------------------------------------------]
[ =============================== Aircraft =============================== ]
[Taskforce1Aircraft1] # TEST
Type=wp_tu-22m2
SquadronReference=Squadron1
RelativePositionInNm=70,20000,122
Heading=210
Waypoints=65,20000,114|700,20000,1220
Attack=Taskforce1Vessel8,15,wp_as-4,3|Taskforce1Vessel8,15,wp_as-4|Taskforce1Vessel8,15|Taskforce1Vessel8  //<- possible variants. Template: targetObject(required), timeOfAttack(optional. In seconds from mission start), ammunitionFileName(optional), numberOfShots(optional)|<next entry>

[------------------------------------------]
#Turn away time - 65 sec
[Taskforce2Aircraft1]
Type=wp_tu-22m2
SquadronReference=Squadron1
LoadoutVariant=LongRange
RelativePositionInNm=70,20000,122
Heading=210
Waypoints=65,20000,114|700,20000,1220
Attack=Taskforce1Vessel8,25,wp_as-4

[Taskforce2Aircraft2]
Type=wp_tu-22m2
SquadronReference=Squadron2
LoadoutVariant=LongRange
RelativePositionInNm=69.5,20000,122.5
Heading=210
Waypoints=64.5,20000,114.5|700,20000,1220
Attack=Taskforce1Vessel6,25,wp_as-4

[Taskforce2Aircraft3]
Type=wp_tu-22m2
SquadronReference=Squadron3
LoadoutVariant=LongRange
RelativePositionInNm=72,20000,122
Heading=210
Waypoints=67,20000,114|700,20000,1220
Attack=Taskforce1Vessel7,55,wp_as-4

[Taskforce2Aircraft4]
Type=wp_tu-22m2
SquadronReference=Squadron4
LoadoutVariant=LongRange
RelativePositionInNm=71.5,20000,122.5
Heading=210
Waypoints=66.5,20000,114.5|700,20000,1220
Attack=Taskforce1Vessel5,55,wp_as-4
[------------------------------------------]