
[Debug]
DisableEnemyAIPlayer=True
DevModeGUIScale=1
ScaleStep=0.1
#ForceMusicLoadig=True
LogMode=Test

[Language_en]
Name=Long way to Lübeck
Description=In the heat of Soviet offensive, a small convoy carries vital supplies to the besieged city of Lübeck.
Taskforce1StartMessage=<size=40>Long way to Lübeck</size>|<size=15>Commander, our intel reports that enemy supply convoy has left <color={*}ffc68c>Halmstad</color> and is moving south. We are expecting that it is heading for <color={*}ffc68c>Lübeck</color> to aid enemy forces defending region from our advancing armies.\n\nDespite its size, this convoy will make capture of Lübeck harder and delay our advance. We cant allow that, so you are ordered to gather all what is left in port and intercept this convoy before it reaches its destination. <color={*}ffc68c>You must sink at least two transport vessels.</color>\nUnfortunately all our available assets are already engaged and we unable to provide any support to you. There will be no air cover or recon. On the bright side, the enemy is busy as well so it is unlikely that you will encounter any resistance except from convoy's escort.\nWe are transfering <color={*}ffc68c>submarines</color> in the area to your command. They should help you locate and intercept this convoy.\n\nGood luck, commander!\n\n</size>
Taskforce1UnitDestroyedMessage=Enemy Destroyed|{$TrackId} {$UnitClass} <color={*}ffc68c>{$UnitNameFull}</color> has been destroyed!|Nice,Good riddance,Burn baby burn,Here goes another one
Taskforce1OneUnitsDestroyedMessage=Objective completed|One of target vessels is destroyed!\nGood job, commander! One more to go.|Lets get to it!
Taskforce1AllUnitsDestroyedMessage=Victory|Both target vessels are destroyed!\n\nCongradulations, commander! Without those supplies Lübeck will not hold for long!|Hoorah!
Taskforce1ConvoyArrivedMessage=Defeat| You have failed to stop the convoy commander!\nIt will be harder for our troops to capture Lübeck now!
Taskforce1ConvoyPassedMessage=Defeat| You have failed to stop the convoy commander!\nIt will be harder for our troops to capture Lübeck now!
Taskforce1Teleport1Message=And now we have to spend several hours just moving...
Taskforce1Teleport2Message=We need time compression...
Taskforce1Teleport3Message=Too long to wait, even on x32...\n\nIf only there was some way to skip time...
Taskforce1Teleport4Message=Screw that! Lets rewind to action...
Taskforce2StartMessage=<size=40>Long way to Lübeck</size>|<size=15>Commander, situation is dire! Enemy forces are storming Lübeck and without support city will fall soon! We desperately need to deliver supplies to defenders, so you will rendezvous with 3 transports recently arrived to <color={*}ffc68c>Halmstad</color> and escort them to <color={*}ffc68c>Lübeck</color>.\nWe understand that your force is to small to provide reliable escort, but we have no choice: we literally have noone else available in the area and without those supplies city will fall in couple of days. Fortunately most of the enemy forces are also locked in combat so at maximum you could expect some diesel submarines and attack boats.\n\nWe are counting on you, commander! Do not let us down. Godspeed.</size>
Taskforce2UnitDestroyedMessage={$UnitClass} <color={*}ffc68c>{$UnitNameFull}</color> has been destroyed!
Taskforce2OneUnitsDestroyedMessage=<color=red>Objective failed</color>|One of our transports was destroyed!\nCommander! One more,and this mission is lost!|Got it
Taskforce2AllUnitsDestroyedMessage=Defeat|We lost too many transports.\n\nYou have failed, commander! Without those supplies Lübeck will not hold for long!
Taskforce2ConvoyArrivedMessage=Victory|Congradulations, commander! You have managed to deliver much needed supplies and strengthen our defending troops!\n\nWell done!|Hoorah!
Taskforce2ConvoyPassedMessage=Victory|Congradulations, commander! You have managed to break through the blokade!\n\nWell done!|Hoorah!
#Info: UnitTags={$UnitName} {$UnitClass} {$UnitNameFull} {$UnitClass} {$UnitClassFull} {$TrackId}
Taskforce1TestMessage=Test!
NumberOfIntelItems=1
IntelligenceItem1=Bla-bla
IntelligenceTime1=11,05

[language_ru]
Name=Сохранённая миссия
Description=Последняя записаная миссия
NumberOfIntelItems=1
IntelligenceItem1=Bla-bla
IntelligenceTime1=11,05

[Environment]
Date=1984,7,1
Time=11,4
SeaState=3
Clouds=Broken_2
MapCenterLatitude=56.01
MapCenterLongitude=11.96
MapInitialZoom=10

[Mission]
Difficulty=2
PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
Taskforce1_Nation=Soviet
Taskforce2_Nation=Norway
NumberOfTaskforce1LandUnits=0
NumberOfTaskforce2LandUnits=0
NumberOfNeutralLandUnits=0
NumberOfTaskforce1Vessels=7
NumberOfTaskforce2Vessels=5
NumberOfNeutralVessels=0
NumberOfTaskforce1Submarines=2
NumberOfTaskforce2Submarines=0
NumberOfNeutralSubmarines=0
NumberOfTaskforce1Aircraft=0
NumberOfTaskforce2Aircraft=0
NumberOfNeutralAircraft=0
NumberOfTaskforce1Helicopters=0
NumberOfTaskforce2Helicopters=0
NumberOfNeutralHelicopters=0
Taskforce1_NumberOfFormations=1
Taskforce1_Formation1=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel7|LineAstern|0.2
Taskforce2_NumberOfFormations=1
Taskforce2_Formation1=Taskforce2Vessel1,Taskforce2Vessel4,Taskforce2Vessel3,Taskforce2Vessel2,Taskforce2Vessel5|Convoy
NumberOfTriggers=16

[Taskforce1Vessel1]
Type=wp_pt_shershen
VariantReference=Variant4
RelativePositionInNM=57.28,0,-86.14
Heading=-70
Telegraph=4
Waypoints=13,0,-70.01|8.72,0,-67.2|3.14,0,-66.53|1.13,0,-63.98|-3.91,0,-63.67|-8.1,0,-61.73|-38.13,0,-54.2|-62.59,0,-41.06

[Taskforce1Vessel2]
Type=wp_pt_shershen
VariantReference=Variant12
RelativePositionInNM=57.66,0,-86.28
Heading=-72
Telegraph=4
Waypoints=57.47,0,-86.21

[Taskforce1Vessel3]
Type=wp_pt_shershen
VariantReference=Variant41
RelativePositionInNM=57.85,0,-86.35
Heading=-68
Telegraph=4
Waypoints=57.66,0,-86.28

[Taskforce1Vessel4]
Type=wp_pt_p6
VariantReference=Variant10
RelativePositionInNM=58.03,0,-86.41
Heading=-72
Telegraph=4
Waypoints=57.85,0,-86.35

[Taskforce1Vessel5]
Type=wp_pt_p6
VariantReference=Variant8
RelativePositionInNM=58.22,0,-86.48
Heading=-68
Telegraph=4
Waypoints=58.03,0,-86.41

[Taskforce1Vessel6]
Type=wp_pt_p6
VariantReference=Variant39
RelativePositionInNM=58.41,0,-86.55
Heading=-72
Telegraph=4
Waypoints=58.22,0,-86.48

[Taskforce1Vessel7]
Type=wp_pt_p6
VariantReference=Variant3
RelativePositionInNM=58.6,0,-86.62
Heading=-68
Telegraph=4
Waypoints=58.41,0,-86.55

[Taskforce2Vessel1]
Type=knm_ffg_oslo
VariantReference=Variant3
RadarsActive=True
RelativePositionInNM=40.05,0,31.84
Heading=-116
Telegraph=3
Waypoints=-12.57,0,6.24|-43.01,0,5.48|-56.04,0,-3.77|-70.6,0,-12.71|-64.6,0,-34.66|-53.26,0,-54.73|-66.76,0,-78.31|-30.33,0,-91.55|-44.11,0,-110.49|-67.81,0,-118.39

[Taskforce2Vessel2]
Type=civ_ms_car_carrier_a
VariantReference=Variant3
RelativePositionInNM=42.75,0,33.16
Heading=-105
Telegraph=0
Waypoints=42.57,0,33.07

[Taskforce2Vessel3]
Type=civ_ms_freighter_d
VariantReference=Variant8
LoadoutVariant=MilitaryVehicles
RelativePositionInNM=41.85,0,32.72
Heading=-117
Telegraph=0
Waypoints=41.67,0,32.63

[Taskforce2Vessel4]
Type=civ_ms_amra
VariantReference=Variant19
LoadoutVariant=Munitions
RelativePositionInNM=40.95,0,32.28
Heading=-115
Telegraph=0
Waypoints=40.77,0,32.2

[Taskforce2Vessel5]
Type=knm_ptg_hauk
VariantReference=Variant3
RelativePositionInNM=40.14,0,32.64
Heading=-129
Telegraph=0
Waypoints=40.05,0,31.84

[Taskforce1Submarine1]
Type=wp_ss_foxtrot
VariantReference=Variant10
RelativePositionInNM=40.17,-35,-1.89
Heading=18
Telegraph=1

[Taskforce1Submarine2]
Type=wp_ss_foxtrot
VariantReference=Variant5
RelativePositionInNM=-57,-35,-62
Heading=2
Telegraph=1

[Trigger1]
Name=Start Message
Description=Message displayed at the beginning of the mission
Condition_Type=Time
Condition_Time=0.5
Action_Units=Taskforce1Vessel1,Taskforce2Vessel1
Action_UnitReformFormation=True
Action_Taskforce1_Message=Taskforce1StartMessage
Action_Taskforce2_Message=Taskforce2StartMessage

[Trigger2]
Name=NATO vessel sunk message
Description=Message displayed when any of the NATO vessels have sunk
Repeatable=True
Condition_Type=UnitDestroyed
Condition_Units=Taskforce2Vessel1,Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4,Taskforce2Vessel5
Condition_MinimumUnits=1
Action_Taskforce1_Message=Taskforce1UnitDestroyedMessage
Action_Taskforce2_Message=Taskforce2UnitDestroyedMessage



[Trigger3]
Name=WP vessel sunk message
Description=Message displayed when any of the WP vessels have sunk
Repeatable=True
Condition_Type=UnitDestroyed
Condition_Units=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Submarine1,Taskforce1Submarine2
Condition_MinimumUnits=1
Action_Taskforce1_Message=Taskforce2UnitDestroyedMessage
Action_Taskforce2_Message=Taskforce1UnitDestroyedMessage

[Trigger4]
Name=One NATO transport sunk message
Description=Message displayed when one of the NATO transports have sunk
Condition_Type=UnitDestroyed
Condition_Units=Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4
Condition_MinimumUnits=1
Action_Taskforce1_Message=Taskforce1OneUnitsDestroyedMessage
Action_Taskforce2_Message=Taskforce2OneUnitsDestroyedMessage

[Trigger5]
Name=Two NATO transport sunk message
Description=Message displayed when two of the NATO transports have sunk and WP won
Condition_Type=UnitDestroyed
Condition_Units=Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4
Condition_MinimumUnits=2
Action_Taskforce1_Message=Taskforce1AllUnitsDestroyedMessage
Action_Taskforce2_Message=Taskforce2AllUnitsDestroyedMessage
Action_Victory=Taskforce1

[Trigger6]
Name=Unit teleport
Description=Teleportation of wp_pt_shershen
Condition_Type=Time
Condition_Time=40
Action_Units=Taskforce1Vessel1
Action_PositionNM=-41,0,-52
Action_TeleportToPosition=True
Action_UnitHeading=-62
Action_UnitTelegraph=1
Action_UnitVelocityInKnots=10
Action_UnitWaypoints=Turn,0,20,current
Action_UnitReformFormation=True
Action_SetTime=20,43
Action_Taskforce1_Message=Taskforce1Teleport4Message
Action_Taskforce2_Message=Taskforce1Teleport4Message

[Trigger7]
Name=Heading correction
Description=Attack boats heading correction
Condition_Type=TriggerCompleted
Condition_Triggers=Trigger6
Action_Units=Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel7
Action_UnitHeading=-62
Action_UnitTelegraph=0

[Trigger8]
Condition_Type=Time
Condition_Time=10
Action_Taskforce1_Message=Taskforce1Teleport1Message
Action_Taskforce2_Message=Taskforce1Teleport1Message

[Trigger9]
Condition_Type=Time
Condition_Time=20
Action_Taskforce1_Message=Taskforce1Teleport2Message
Action_Taskforce2_Message=Taskforce1Teleport2Message

[Trigger10]
Condition_Type=Time
Condition_Time=30
Action_Taskforce1_Message=Taskforce1Teleport3Message
Action_Taskforce2_Message=Taskforce1Teleport3Message

[Trigger11]
Name=NATO convoy arrived
Description=Message displayed when NATO convoy arrived to destination and NATO won
Condition_Type=UnitsInTheArea
Condition_PositionNM=-55,0,-114
Condition_AreaRadiusNM=5
Condition_Units=Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4
Condition_MinimumUnits=2
Action_Taskforce1_Message=Taskforce1ConvoyPassedMessage
Action_Taskforce2_Message=Taskforce2ConvoyPassedMessage
Action_Victory=Taskforce2

[Trigger12]
Name=Unit teleport
Description=Teleportation of knm_ffg_oslo
Condition_Type=TriggerCompleted
Condition_Triggers=Trigger6
Action_Units=Taskforce2Vessel1
Action_PositionNM=-62,0,-34
Action_TeleportToPosition=True
Action_UnitHeading=156
Action_UnitTelegraph=3
Action_UnitVelocityInKnots=15
Action_UnitWaypoints=-53.25,0,-54.72|-66.75,0,-78.3|-30.33,0,-91.54|-44.1,0,-110.47|-67.8,0,-118.37
Action_UnitReformFormation=True

[Trigger13]
Name=Heading correction
Description=Convoy heading correction
Condition_Type=TriggerCompleted
Condition_Triggers=Trigger6
Action_Units=Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4,Taskforce2Vessel5
Action_UnitHeading=156
Action_UnitTelegraph=0

[Trigger14]
Name=NATO convoy passed
Description=Message displayed when NATO convoy arrived to destination and NATO won
Condition_Type=UnitsInTheArea
Condition_PositionNM=-66,0,-80
Condition_AreaRadiusNM=15
Condition_Units=Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4
Condition_MinimumUnits=2
Action_Taskforce1_Message=Taskforce1ConvoyPassedMessage
Action_Taskforce2_Message=Taskforce2ConvoyPassedMessage
Action_Victory=Taskforce2

[Trigger15]
Name=All Soviet ships lost
Description=Message displayed when all soviet vessels have sunk
Condition_Type=UnitDestroyed
Condition_Units=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel7,Taskforce1Submarine1
Condition_MinimumUnits=8
Action_Taskforce1_Message=Taskforce1ConvoyPassedMessage
Action_Taskforce2_Message=Taskforce2ConvoyPassedMessage
Action_Victory=Taskforce2

[Trigger16]
Name=Disband Formation
Condition_Type=UnitDestroyed
Condition_Units=Taskforce2Vessel1
Condition_MinimumUnits=1
Action_Units=Taskforce2Vessel2,Taskforce2Vessel3,Taskforce2Vessel4
Action_UnitWaypoints=-59,0,-78.3|-30.33,0,-91.54|-44.1,0,-110.47|-67.8,0,-118.37
