[Debug]
LogMode=Ivan

# Overrides of usersettings.ini
#DisableTerrain=True
#DevModeGUIScale=Auto      // Initial scale of DevMode GUI.
DevModeGUIScale=1      // Initial scale of DevMode GUI.
ScaleStep=0.1             // Value that is added or substracted from the scale by scale change buttons
AllowEnemyUnitsAttackPlayer=False
DisableStrategicMap=False
#FullscreenStrategicMap=True
ContextMenuScale=1.2
ContextMenuFontSize=20
#-----------------------------

#MissionStartTextDM=

[Language_en]
Name=Ivan's Test 2 mission
Description=Ivan's testing grounds with a personalized logmode for special situations

[Environment]
Date=1974,5,9
Time=15,30

SeaState=2
Clouds=Scattered
Overcast



#Aegian sea
MapCenterLatitude=36
MapCenterLongitude=25


[Mission]
Difficulty=2

PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2

Taskforce1_Nation=Soviet
Taskforce2_Nation=USA

Taskforce1_UI=Default
Taskforce2_UI=Test


Taskforce1_NumberOfFormations=1
Taskforce1_Formation1=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel6|TF Kiev|LineAstern|0.5
#Taskforce1_Formation_2=Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6



NumberOfTaskforce1LandUnits=

NumberOfTaskforce1Vessels=6
NumberOfTaskforce2Vessels=
NumberOfNeutralVessels=

NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=

NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=

NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=

[ ================================ Vessels =============================== ]
[Taskforce1Vessel1]
Type=wp_rkr_kynda
VariantReference=Variant1
RadarsActive=True

RelativePositionInNM=0,0,0
Heading=45

Telegraph=0

Waypoints=Turn,0,20,current


[Taskforce1Vessel2]
Type=wp_skr_krivak1
VariantReference=Variant2
RadarsActive=True

RelativePositionInNm=0.1,0,0
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=0


[Taskforce1Vessel3]
Type=wp_bpk_kanin
VariantReference=Variant3

RelativePositionInNm=0.2,0,0
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=0

[Taskforce1Vessel4]
Type=wp_bpk_kashin
VariantReference=Variant3

RelativePositionInNm=0.3,0,0
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=0

[Taskforce1Vessel5]
Type=wp_mrk_nanuchka
VariantReference=Variant3

RelativePositionInNm=0.4,0,0
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=0

[Taskforce1Vessel6]
Type=wp_ptg_osa1
VariantReference=Variant3

RelativePositionInNm=0.5,0,0
PositionRelativeTo=Taskforce1Vessel1

Heading=Parent
Telegraph=0






[------------------------------------------]
[Taskforce2Vessel1]
Type=wp_mrk_nanuchka
civ_ms_freighter_b
wp_bpk_kara
wp_ptg_osa1
ins_ptg_aliya
civ_fv_okean
usn_cvn_nimitz
wp_bpk_kara
VariantReference=Variant2
//VariantReference=Random
#RadarsActive=True
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=-4,0,-1
Heading=0
Telegraph=0
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=20,0,24

[------------------------------------------]
[NeutralVessel1]
Type=civ_ms_freighter_b
VariantReference=Variant1
RadarsActive=False
RelativePositionInNm=15,0,3
Heading=90
Telegraph=0
Waypoints=12,0,-3

[ ============================== Submarines ============================== ]
[Taskforce1Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Variant1
Random

#RadarsActive=True
#TowedArrayDeployed=True
ActiveSonarsEnabled=True
#TowedDecoyDeployed=True

#RelativePositionInNm=0.8,-300,-0.5
#RelativePositionInNM=0,p,0
RelativePositionInNM=-5,-100,-1
Heading=90
Telegraph=0
#Waypoints=2,-200,0|2,-400,2|4,200,4    //X - NM, Y - feet, Z - NM

[------------------------------------------]
[Taskforce2Submarine1]
Type=usn_ssn_sturgeon
VariantReference=Random
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=0,-200,-4
Heading=0
Telegraph=0
#Waypoints=2,200,0|2,400,2|4,200,4    //X - NM, Y - feet, Z - NM
Waypoints=0,-200,10

[------------------------------------------]
[NeutralSubmarine1]
Type=usn_ssn_los_angeles
VariantReference=Default
RelativePositionInNm=0,-200,-5
Heading=0
Telegraph=4
Waypoints=0,-200,10
[ =============================== Aircraft =============================== ]
[Taskforce1Aircraft1]
Type=wp_mig-23mld

//SquadronReference=Squadron12
RadarsActive=True
HomeBase=Taskforce1Vessel1
#HomeBase=Taskforce1Vessel1
LoadoutVariant=Attack

RelativePositionInNm=0,100,0
Heading=180
Waypoints=Turn,0,4,current

[------------------------------------------]
[Taskforce2Aircraft1]
Type=usn_f-4j
SquadronReference=Squadron12
RadarsActive=True
LoadoutVariant=Attack

RelativePositionInNm=10,2000,-13.8
Heading=180
Waypoints=Turn,0,4,current
Attack=Taskforce1LandUnit1,0,usn_mk-82

[------------------------------------------]
[NeutralAircraft1]
Type=civ_707
SquadronReference=Squadron1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
RelativePositionInNm=-2.9,5000,7
Heading=220

[ ============================== Helicopters ============================= ]
[Taskforce1Helicopter1]
MissionTarget=Protect
Type=wp_ka-25
usn_sh-2f
wp_ka-27
usn_sh-3h
wp_ka-25
SquadronReference=Squadron1
#LoadoutVariant=Loadout2
RadarsActive=True
HomeBase=Taskforce1Vessel1
#possible keys: RelativePositionInNM or RelativePositionInKm
#negative values go west for x and north for z, height (y) is in feet
#RelativePositionInNM=-10,4000,0
RelativePositionInNm=-0,1000,-1
#RelativePositionInNm=-12,1400,2
//OverrideSpawnHeightUnity=12.3456
Heading=90
#Waypoints=FollowLoose,Taskforce1Aircraft1,2,0,1
#Waypoints=Turn,0,20,current
#Waypoints=-7,200,0.08|10,100,1    //X - NM, Y - feet, Z - NM

[------------------------------------------]
[Taskforce2Helicopter1]
MissionTarget=Destroy
Type=usn_sh-2f
SquadronReference=Squadron2


RelativePositionInNM=-1,400,-4.005
Heading=90


[------------------------------------------]
[NeutralHelicopter1]
Type=wp_ka-27
SquadronReference=Squadron1
RelativePositionInNm=-3,1400,3
Heading=90

[ ============================== Land Units ============================== ]
[Taskforce1LandUnit11]
Type=wp_sam_site_sa-5
VariantReference=Variant1

RadarsActive=True

RelativePositionInKm=0,869,-30
OverrideSpawnHeightUnity=3.95
Heading=0

[------------------------------------------]
[Taskforce1LandUnit1]
Type=wp_large_pvo_airbase
VariantReference=Variant1
RelativePositionInNm=110,242,-15
Waypoints=20,0,-3

#CustomAirGroup=True
#usn_f-14a=Squadron3,1|Squadron4,10
#usn_s-3a=Squadron3,5