#!extend language_ja/aircraft_names.ini
[********************** Civilian *********************]
[---------------------- Aircraft ---------------------]
[civ_e100]
Type=General Aviation,一般航空
Default=E100
DefaultDescription=


[************************ Argentina ***********************]
[---------------------- Aircraft ---------------------]
[ara_a-4p]
Type=Attack,攻撃機
Default=A-4P スカイホーク,A-4P
DefaultDescription=A-4Pスカイホーク。
Squadron1=A-4P 第5航空群,A-4P
Squadron2=A-4P 第4航空旅団,A-4P
Squadron3=A-4P 第4航空旅団,A-4P
Callsigns=Squadron1,Cruz|Squadron2,Zonda|Squadron3,Zeus,Dogo

[ara_a-4q]
Type=Attack,攻撃機
Default=A-4Q スカイホーク,A-4Q
DefaultDescription=A-4Qスカイホーク。
Squadron1=A-4Q EA33,A-4Q EA33
Callsigns=Squadron1,Cola

[ara_b-707]
Type=Maritime Patrol,哨戒機
Default=B-707,B-707
DefaultDescription=フォークランド戦争中、アルゼンチン空軍のB-707は即席の長距離海上偵察を行った。非武装の機体は大型艦を探知できたが、接触目標の識別には目視が必要で、専用の海上捜索装備や防御システムは備えていなかった。
Squadron1=707 第5飛行隊,707
Callsigns=Squadron1,Carbon,Buque,Tronco

#Not sure about this, probably should start as Nesher
[ara_dagger]
Type=Fighter,戦闘機
Default=ダガー,Dagger
DefaultDescription=
Squadron1=ダガー,Dagger

[ara_p-95]
Type=Maritime Patrol,哨戒機
Default=P-95,P-95
DefaultDescription=P-95



[ara_pucara]
Type=Attack,攻撃機
Default=プカラ
DefaultDescription=
Squadron1=プカラ

[************************ Brazil ***********************]
[---------------------- Aircraft ---------------------]
[fab_c-95]
Type=Maritime Patrol,哨戒機
Default=C-95,C-95
DefaultDescription=C-95


[************************ France ***********************]
[---------------------- Aircraft ---------------------]
[fr_1150_atlantic]
Type=Maritime Patrol,哨戒機
Default=アトランティック,Atlantic
DefaultDescription=

[fr_super_etendard]
Type=Attack,攻撃機
Default=シュペルエタンダール,Super Etendard
DefaultDescription=シュペルエタンダールは1978年から運用されているフランス製の艦上攻撃機であり、フランス、アルゼンチン、イラクで使用された高性能な機体である。対艦ミサイルを搭載できるため、洋上の艦艇にとって大きな脅威となる。冷戦期のNATOで数少ない艦上攻撃機の一つでもある。
Squadron1=シュペルエタンダール,Super Etendard
Squadron2=シュペルエタンダール EA32,Super Etendard EA32
Squadron3=シュペルエタンダール,Super Etendard
Callsigns=Squadron2,Ala

[-------------------- Helicopters --------------------]
[fr_alouette_III]
Type=Utility Helicopter,汎用ヘリコプター
Default=SA.316,SA.316
DefaultDescription=SA.316/SA.319「アルエットIII」は、1950年代後半にフランスで開発された多用途ヘリコプターであり、欧州各国の軍でさまざまな任務に使用されている。この型は軽攻撃任務向けに無誘導ロケット（FFAR）、魚雷、SS.11およびAS.12空対地ミサイル、機関銃を搭載できる。
Squadron1=SA.316,SA.316
Squadron2=SA.316,SA.316
Squadron3=SA.316,SA.316
Squadron4=SA.316,SA.316
Squadron5=SA.316,SA.316
Squadron6=SA.316,SA.316

[************************ Australia ************************]
[---------------------- Aircraft ---------------------]

[************************ UK ************************]
[---------------------- Aircraft ---------------------]
[raf_gr1]
Type=Fighter,戦闘機
Default=ハリアー GR.1,GR.1
DefaultDescription=
Squadron1=ハリアー GR.1 第1飛行隊,GR.1
Squadron2=ハリアー GR.1 第3飛行隊,GR.1
Squadron3=ハリアー GR.1 第4飛行隊,GR.1
Squadron4=ハリアー GR.1 第20飛行隊,GR.1
Squadron5=ハリアー GR.1,GR.1
Squadron6=ハリアー GR.1,GR.1
Squadron7=ハリアー GR.1,GR.1
Callsigns=Squadron1,Spade|Squadron2,Nightmare|Squadron3,Tiger|Squadron4,Phoenix|Squadron5,Dragon|Squadron6,Sharp Blade|Squadron7,Wolf

[raf_gr3]
Type=Fighter,戦闘機
Default=ハリアー GR.3,GR.3
DefaultDescription=
Squadron1=ハリアー GR.3 第1飛行隊,GR.3
Squadron2=ハリアー GR.3 第3飛行隊,GR.3
Squadron3=ハリアー GR.3 第4飛行隊,GR.3
Squadron4=ハリアー GR.3 第20飛行隊,GR.3
Callsigns=Squadron1,Spade|Squadron2,Nightmare|Squadron3,Tiger|Squadron4,Phoenix

[raf_vulcan]
Type=Bomber,戦略爆撃機
Default=バルカン B.2,Vulcan
DefaultDescription=
Squadron1=バルカン B.2,Vulcan
Squadron2=バルカン B.2,Vulcan
Squadron3=バルカン B.2,Vulcan

[rn_frs1]
Type=Fighter,戦闘機
Default=シーハリアー FRS.1,FRS.1
DefaultDescription=シーハリアーFRS.1は、ハリアーGR.1をイギリス海軍向けに改良した艦上機である。空対空能力が強化され、ブルーフォックス・レーダーで空中や海上の目標を探知できる。英国キングストンの工場ではハリアーGR.1やGR.3と同じ生産ラインで製造され、同工場にとって輸出面でも大きな成功を収めた。本機は、欧州の3カ国共同評価飛行隊で運用されたケストレルとP.1127の発展型である。
Squadron1=シーハリアー FRS.1 第800海軍航空隊,FRS.1
Squadron2=シーハリアー FRS.1 第801海軍航空隊,FRS.1
Squadron3=シーハリアー FRS.1 第809海軍航空隊,FRS.1
Squadron4=シーハリアー FRS.1 第899海軍航空隊,FRS.1
Callsigns=Squadron1,Blue|Squadron2,Black|Squadron3,Red|Squadron4,Yellow

[rn_nimrod_mr1]
Type=Maritime Patrol,哨戒機
Default=ニムロッド MR.1,MR1
DefaultDescription=ニムロッドMR.1は、デ・ハビランド・コメット旅客機を基に開発された、イギリス空軍初のジェット式海上哨戒機である。1960年代後半に就役し、長い航続距離と水上捜索レーダー、ソノブイ、魚雷を生かして対潜戦と海上監視に従事した。改良型MR.2に交代するまで、英国の海上哨戒戦力の主力を担った。
Squadron1=ニムロッド MR.1,MR1

[rn_nimrod_mr2]
Type=Maritime Patrol,哨戒機
Default=ニムロッド MR.2,MR2
DefaultDescription=
Squadron1=ニムロッド MR.2,MR2
Squadron2=ニムロッド MR.1,MR1

[-------------------- Helicopters --------------------]
[raf_scout_ah1]
Type=Helicopter,ヘリコプター
Default=スカウト AH.1,Scout AH.1
DefaultDescription=
Squadron1=スカウト AH.1,Scout AH.1
#Callsigns=Squadron1,Hobby

[rn_lynx_has2]
Type=ASW Helicopter,対潜ヘリコプター
Default=リンクス HAS.2,Lynx HAS.2
DefaultDescription=リンクスは当初、イギリス陸軍の汎用ヘリコプターとして開発された。完全リジッド式ローターヘッドを採用し、複雑な曲技飛行が可能な世界最速のヘリコプターである。イギリス海軍向けのHAS.2型は、甲板上での取り回しのため主脚がそれぞれ回転する車輪式降着装置と水上捜索レーダーを備え、軽対水上戦（ASuW）兵器と対潜戦（ASW）兵器を搭載できる。
Squadron1=リンクス HAS.2 艦隊航空隊,Lynx HAS.2
Squadron2=リンクス Mk.80,Lynx HAS.2
Squadron3=リンクス Mk.2(FN),Lynx Mk.2
Squadron4=SH-14B リンクス,Lynx HAS.2
#Callsigns=Squadron1,Hobby

[rn_sea_king_has5]
Type=ASW Helicopter,対潜ヘリコプター
Default=シーキング HAS.5,HAS.5
DefaultDescription=ソ連潜水艦部隊の脅威の高まりに対抗して開発されたSH-3は、NATO諸国で広く運用される高性能な対潜ヘリコプターである。捜索救難（SAR）から空中早期警戒（AEW）まで、任務に応じた多くの派生型がある。民間型も、特に北海油田での輸送に多くの航空会社が使用している。
Squadron1=シーキング HAS.5 第814海軍航空隊,HAS.5
Squadron2=シーキング HAS.5 第820海軍航空隊,HAS.5
Squadron3=シーキング HAS.5 第824海軍航空隊,HAS.5
Squadron4=シーキング HAS.5 第825海軍航空隊,HAS.5
Squadron5=シーキング HAS.5 第826海軍航空隊,HAS.5
Callsigns=Squadron1,Knight|Squadron2,Shark|Squadron3,Dragon|Squadron4,Viking|Squadron5,Firebird

[rn_wasp_has1]
Type=ASW Helicopter,対潜ヘリコプター
Default=ワスプ HAS.1,Wasp HAS.1
DefaultDescription=
Squadron1=ワスプ HAS.1,Wasp HAS.1
#Callsigns=Squadron1,Hobby

[rn_wessex_has1]
Type=ASW Helicopter,対潜ヘリコプター
Default=ウェセックス HAS.1,Wessex HAS.1
DefaultDescription=
Squadron1=ウェセックス HAS.1,Wessex HAS.1
#Callsigns=Squadron1,Hobby

[rn_wessex_has3]
Type=ASW Helicopter,対潜ヘリコプター
Default=ウェセックス HAS.3,Wessex HAS.3
DefaultDescription=
Squadron1=ウェセックス HAS.3,Wessex HAS.3
#Callsigns=Squadron1,Hobby

[rn_wessex_hu5]
Type=Medium Lift Helicopter,中型輸送ヘリコプター
Default=ウェセックス HU.5,Wessex HU.5
DefaultDescription=
Squadron1=ウェセックス HU.5,Wessex HU.5
#Callsigns=Squadron1,Hobby

[************************ USA ************************]
[---------------------- Aircraft ---------------------]
[usaf_c-130]
Type=Transport,輸送機
Default=C-130 ハーキュリーズ,C-130
DefaultDescription=
Squadron1=C-130 ハーキュリーズ,C-130

[usaf_f-111f]
Type=Attack,攻撃機
Default=F-111F アードバーク,F-111F
DefaultDescription=F-111はアメリカ製の超音速中距離戦闘爆撃機である。1967年に導入され、攻撃、戦略爆撃（核・通常兵器）、偵察、電子戦などの任務に就いた。米軍の量産機として初めて可変後退翼とアフターバーナー付きターボファンエンジンを採用した。F-111Fは1970年代に製造された最終派生型で、電子装備が更新され、より強力なエンジンを搭載している。

# 366th TFW - Mountain Home AFB, Idaho, US
Squadron1=F-111F 第389戦術戦闘飛行隊,F-111F
Squadron2=F-111F 第390戦術戦闘飛行隊,F-111F
Squadron3=F-111F 第391戦術戦闘飛行隊,F-111F

# 48th TFW - RAF Lakenheath
Squadron4=F-111F 第492戦術戦闘飛行隊,F-111F
Squadron5=F-111F 第493戦術戦闘飛行隊,F-111F
Squadron6=F-111F 第494戦術戦闘飛行隊,F-111F
Squadron7=F-111F 第495戦術戦闘飛行隊,F-111F

Callsigns=Squadron5,Cardinal,Cougar|Squadron7,Karma,Remit

[usaf_ef-111a]
Type=EW Aircraft,電子戦機
Default=EF-111A レイヴン,EF-111FA
DefaultDescription=EF-111Aは米空軍が運用する電子戦機である。F-111を基に開発され、AIM-9ミサイル以外の武装は持たず、速度と加速力を主な防御手段とする。強力なAN/ALQ-99E妨害ポッドを搭載しており、これは艦上機EA-6Bが使用する米海軍のAN/ALQ-99妨害システムから発展したものである。EF-111Aは米空軍に、超音速で敵空域へ侵入して電子戦を行う能力をもたらした。通常は阻止攻撃任務でF-111攻撃機と連携する。

# 20th TFW - RAF Upper Heyford, England
Squadron1=EF-111A 第42電子戦飛行隊,EF-111A

# 366th TFW - Mountain Home AFB, Idaho, US
Squadron2=EF-111A 第388電子戦飛行隊,EF-111A
Squadron3=EF-111A 第390電子戦飛行隊,EF-111A
Callsigns=Squadron1,Wrench|Squadron2,Sorcerer|Squadron3,Sparky

[usn_a-4b]
Type=Attack,攻撃機
Default=A-4B スカイホーク,A-4B
DefaultDescription=スカイホーク!!!!!!
Squadron1=A-4B 第152攻撃飛行隊 'Fighting Aces',VA-152

[usn_a-4c]
Type=Attack,攻撃機
Default=A-4C スカイホーク,A-4C
DefaultDescription=スカイホーク!!!!!!
Squadron1=A-4C 第12攻撃飛行隊 'Valions',VA-15
Squadron2=A-4C 第34攻撃飛行隊 'Blue Blasters',VA-34

[usn_s-2e]
Type=ASW Aircraft,対潜哨戒機
Default=S-2E トラッカー,S-2E
DefaultDescription=S-2は双発の対潜哨戒機で、1954年に米海軍で就役した。広く輸出され、米国では1970年代半ばまで、アルゼンチンでは2025年まで運用された。S-2DとS-2Eは従来型より機体が大型化され、S-2Eにはジュリー／ジェゼベル・ソナー装備が追加された。
Squadron1=S-2E EA2S,S-2E EA2S
Squadron2=S-2E EA2S,S-2E EA2S
Callsigns=Squadron1,Tracker|Squadron2,Tracker
