#!extend language_ja/ammunition_names.ini

[AmmunitionNames]
# ------------------ Debug ------------------
_test_asm=Test Missile,,,ゲーム開発用の試験ミサイル。
_test_shell=Test Shell,,,ゲーム開発用の試験砲弾。

# ------------------ AAM ------------------
raf_skyflash_3000=Skyflash,,AAM,スカイフラッシュ3000（Pre TEMP）は、米国のスパローから派生した英国製の中距離空対空ミサイルである。AIM-7E-2に逆モノパルス方式のシーカーを搭載したもので、信頼性を高めるとともに、電子妨害への耐性（ECCM）と低高度での性能を大幅に向上させた。
raf_skyflash_6000=Skyflash,SuperTEMP,AAM,スカイフラッシュ6000（SuperTEMP）は、米国のスパローから派生した英国製の中距離空対空ミサイルである。初期型を改良したSuperTEMP（Tornado Embodied Modification Package）は、ブースト・サステイン方式のロケットモーターで射程をやや延ばし、電子妨害への耐性（ECCM）もさらに強化した。

# ------------------ SAM ------------------
rn_seaslug_mk2=GWS-2,Sea Slug Mk.2,SAM,GWS-2シースラッグMk.2は、初期型Mk.1を改良した、イギリス海軍で最初期の艦対空ミサイルの一つである。高速で燃焼時間も長いが、信頼性と命中精度は低く、低空飛行目標や高速目標への対応は苦手である。\n必要なら地上施設の攻撃にも使用できるが、その場合の命中精度は低い。
rn_seadart=GWS-30,Sea Dart,SAM,GWS-30シーダートは、シースラッグの後継となった英国の標準的な艦載中距離艦対空ミサイルである。固体ロケットブースターとラムジェットによる巡航推進を組み合わせ、米国のスタンダード・ミサイルに匹敵する性能を持つ。
rn_seawolf=GWS-25,Sea Wolf,SAM,GWS-25シーウルフはシーキャットの後継で、航空機や海面すれすれを飛ぶミサイルへの対処能力が大幅に向上した。命中精度は高いが、射程の極めて短い個艦防空用ミサイルであり、確実に守れるのは発射艦だけで、近くの味方部隊までは守れない。

# ---------- Anti-ship Missiles ----------
rn_sea_skua=Sea Skua,,ASM,シースクアはイギリス製の短距離対艦ミサイルである。

# ---------- Anti-sub  Missilies ----------


# --------------- Torpedoes ---------------
rn_mark24_mod0=Mark 24 Mod 0,Tigerfish,ASW Torpedo,Mark 24「タイガーフィッシュ」は、1970年代後半に登場した英国製の有線誘導対潜重魚雷である。1960年代にMark 20およびMark 23魚雷の後継として始まったONGAR計画から生まれたが、魚雷そのものの技術的問題により開発が長期化した。当初は高速の対潜・対艦両用魚雷として構想されたものの、Mod 0は比較的低速で対艦能力がなく、電池や弾頭の故障もあって信頼性は極めて低いと評価された。
rn_mark24_mod1=Mark 24 Mod 1,Tigerfish,Torpedo,Mark 24「タイガーフィッシュ」は、1970年代後半に登場した英国製の有線誘導対潜・対艦重魚雷である。1960年代にMark 20およびMark 23魚雷の後継として始まったONGAR計画から生まれたが、魚雷そのものの技術的問題により開発が長期化した。Mod 1はMod 0より最大潜航深度が深く、対艦能力も備える。一方で信頼性の低さと速度の遅さは解消されず、第二次世界大戦期の直進式Mark 8魚雷を置き換えたのは1980年代後半になってからである。

# ----------------- Decoys ----------------
rn_type_182_decoy=Type 182,,Decoy,Type 182曳航式対抗装置は、イギリス海軍の水上艦で使用される魚雷デコイである。偽のソナー・パルスを発して接近する魚雷のシーカーを妨害できるが、そのためにはデコイが魚雷と自艦の間に位置しなければならない。
