#!extend language_ja/land_units_names.ini
[****************************** Falklands ******************************]
[ -------------------- Land Targets Industrial: Industrial buildings ----------------]
[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]
[flk_goose_green]
Type=航空基地
Default=グース・グリーン飛行場,Goose Green
DefaultDescription=
Variant1=グース・グリーン飛行場,Goose Green

[flk_pebble_island]
Type=航空基地
Default=ペブル島飛行場,Pebble Island
DefaultDescription=
Variant1=ペブル島飛行場,Pebble Island

[flk_san_carlos_fob]
Type=航空基地
Default=サン・カルロス前進作戦基地,San Carlos FOB
DefaultDescription=
#Variant1=HMS Sheathbill,HMS Sheathbill
Variant1=サン・カルロス前進作戦基地,San Carlos FOB

[ -------------------- Radars -------------------- ]
[ -------------------- Radios and Comms -------------------- ]
[ -------------------- SAM Sites -------------------- ]
[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]
[ -------------------- Vehicles -------------------- ]