#!extend language_ja/vessel_names.ini
[****************************** Miscellaneous ******************************]
[civ_ms_roro_ferry]
Type=MV,RO-RO船
Default=RO-RO旅客船,Merchant
DefaultDescription=RO-RO船は車両甲板とランプを備え、車両やトレーラー積載貨物を効率よく迅速に積み降ろしできる。このため、軍事輸送にも非常に適している。
Variant1=MV ノーランド
Variant2=MV ノースター
Variant3=MV ストンク・ユトランディカ
Variant4=MV ストンク・ダニカ
Variant5=MV ストンク・ノルディカ
Variant6=MV ストンク・オリンピカ
Variant7=MV トール・スカンディナヴィア
Variant8=MV トール・ブリタニア
#Variant9=MV Toletela
#Variant10=MV Garnata
#Variant11=MV Habib
#Variant12=MV Monte Toledo
#Variant13=MV Monte Granada

[civ_ms_searunner]
Type=MV,RO-RO船
Default=シーランナー,Merchant
DefaultDescription=RO-RO船は車両甲板とランプを備え、車両やトレーラー積載貨物を効率よく迅速に積み降ろしできる。このため、軍事輸送にも非常に適している。この型には船尾ランプがあり、追加の貨物をクレーンで積み込むこともできる。
Variant1=MV ストンク・フレイター
Variant2=MV ストンク・ランナー
Variant3=MV ストンク・シッパー
Variant4=MV ストンク・トランスポーター
Variant5=MV ストンク・キャリアー
Variant6=MV アトランティック・プロスパー
Variant7=MV アトランティック・プロジェクト
Variant8=MV エルク
Variant9=MV メルクリオ・アウソニア
Variant10=MV メルクリオ・エスパニア
Variant11=MV メルクリオ・グレシア
Variant12=MV メルクリオ・イスパニア
Variant13=MV メルクリオ・イオニア
Variant14=MV アルファ・プログレス
Variant15=MV コンステレーション・エンタープライズ

[civ_ms_searunner_mod]
Type=MV,RO-RO船
Default=改造型シーランナー,Merchant
DefaultDescription=RO-RO船は車両甲板とランプを備え、車両やトレーラー積載貨物を効率よく迅速に積み降ろしできる。このため、軍事輸送にも非常に適している。この型は船尾ランプを備え、旅客区画の拡張と車両甲板の増設が行われている。
Variant1=MV バルティック・フェリー
Variant2=MV セルディック・フェリー
Variant3=MV ドーリック・フェリー
Variant4=MV ノルディック・フェリー

[****************************** Argentina ******************************]
[ara_cl_belgrano]
Type=CL,軽巡洋艦
Default=ブルックリン級,Brooklyn
DefaultDescription=ブルックリン級軽巡洋艦は1930年代に米海軍向けに建造され、第二次世界大戦を通じて大西洋と太平洋で活躍した。戦後、米国は相互防衛援助計画の一環として本級の大半を南米諸国の海軍に売却した。各艦は戦時中の構成のまま引き渡され、アルゼンチン、チリ、ブラジルでの運用中にセンサーの更新や、ときには新兵装の搭載が行われた。本級は15門の6インチ47口径速射砲を備え、その高い発射速度から、ソロモン諸島での夜戦を目撃した日本側は「機関銃巡洋艦」と呼んだ。
Variant1=ヘネラル・ベルグラノ C-4,Belgrano
Variant2=ヌエベ・デ・フリオ C-5, 9 de Julio
Variant3=オイギンス CL-02,O'Higgins
Variant4=カピタン・プラット CL-03,Prat
Variant5=バローゾ C-11,Barroso

[ara_cv_veinticinco_de_mayo]
Type=CVS,航空母艦
Default=コロッサス級,Colossus
DefaultDescription=
Variant1=ベインティシンコ・デ・マヨ V-2,25 De Mayo

[ara_fs_drummond]
Type=FS,コルベット
Default=ドラモンド級,Drummond
DefaultDescription=
Variant1=ドラモンド P-31,Drummond
Variant2=ゲリコ P-32,Guerrico
Variant3=グランビル P-33,Granville

[ara_ddg_hercules]
Type=DDG,駆逐艦
Default=エルクレス級,Hércules
DefaultDescription=仮アセット
Variant1=エルクレス D-1,Hércules
Variant2=サンティシマ・トリニダード D-2,Santísima Trinidad

[ara_dd_comodoro_py]
Type=DD,駆逐艦
Default=コモドロ・ピ級,Comodoro Py
DefaultDescription=仮アセット
Variant1=コモドロ・ピ D-27,Comodoro Py

[ara_ss_santa_fe]
Type=SS,哨戒潜水艦
Default=サンタ・フェ級,Santa Fe
DefaultDescription=仮アセット（バラオ級 GUPPY II）
Variant1=サンタ・フェ S-21,Santa Fe

[****************************** Civilian ******************************]
[****************************** Peoples Republic of China ******************************]
[****************************** France ******************************]
[****************************** Germany ******************************]
[fgs_ss_type_209-1200]
Type=SS,哨戒潜水艦
Default=サルタ級,Salta
#Default=Type 209/1200-class,Type 209/1200
DefaultDescription=
Variant1=サルタ S-31,Salta
Variant2=サン・ルイス S-32,San Luis

[***************************** India *****************************]
[***************************** Israel *****************************]
[****************************** Iran ******************************]
[****************************** Japan ******************************]
[****************************** Libya ******************************]
[****************************** Norway ******************************]
[****************************** Pakistan ******************************]
[****************************** Portugal ******************************]
[****************************** Spain ******************************]
[****************************** Canada ******************************]
[****************************** Australia ******************************]
[****************************** UK ******************************]
[rn_cvs_invincible]
Type=CVS,航空母艦
Default=インヴィンシブル級,Invincible
DefaultDescription=
Variant1=インヴィンシブル R05,Invincible
Variant2=イラストリアス R06,Illustrious
Variant3=アーク・ロイヤル R07,Ark Royal

[rn_ddg_county_batch1]
Type=DDG,駆逐艦
Default=カウンティ級バッチ1,County
DefaultDescription=
Variant1=デヴォンシャー D02,Devonshire
Variant2=ハンプシャー D06,Hampshire
Variant3=ケント D12,Kent
Variant4=ロンドン D16,London

[rn_ddg_county_batch2]
Type=DDG,駆逐艦
Default=カウンティ級バッチ2,County
DefaultDescription=
Variant1=ファイフ D20,Fife
Variant2=グラモーガン D19,Glamorgan
Variant3=アントリム D18,Antrim
Variant4=ノーフォーク D21,Norfolk

[rn_ddg_county_batch2_75]
Type=DDG,駆逐艦
Default=カウンティ級バッチ2,County
DefaultDescription=
Variant1=ファイフ D20,Fife
Variant2=グラモーガン D19,Glamorgan
Variant3=アントリム D18,Antrim
Variant4=ノーフォーク D21,Norfolk

[rn_ddg_sheffield]
Type=DDG,駆逐艦
Default=42型駆逐艦バッチ1,Type 42
DefaultDescription=
Variant1=シェフィールド D80,Sheffield
Variant2=バーミンガム D86,Birmingham
Variant3=ニューカッスル D87,Newcastle
Variant4=コヴェントリー D118,Coventry
Variant5=グラスゴー D88,Glasgow
Variant6=カーディフ D108,Cardiff

[rn_ff_amazon]
Type=FF,フリゲート
Default=21型フリゲート,Type 21
DefaultDescription=
Variant1=アマゾン F169,Amazon
Variant2=アンテロープ F170,Antelope
Variant3=アクティヴ F171,Active
Variant4=アンバスケイド F172,Ambuscade
Variant5=アロー F173,Arrow
Variant6=アラクリティ F174,Alacrity
Variant7=アーデント F184,Ardent
Variant8=アヴェンジャー F185,Avenger

[rn_ff_broadsword]
Type=FF,フリゲート
Default=22型フリゲートバッチ1,Type 22
DefaultDescription=
Variant1=ブロードソード F88,Broadsword
Variant2=バトルアクス F89,Battleaxe
Variant3=ブリリアント F90,Brilliant
Variant4=ブレイゼン F91,Brazen

[rn_ff_leander]
Type=FF,フリゲート
Default=リアンダー級フリゲート,Leander
DefaultDescription=
Variant1=リアンダー F109,Leander
Variant2=ダイドー F104,Dido
Variant3=ペネロピ F127,Penelope
Variant4=エイジャックス F114,Ajax
Variant5=オーロラ F10,Aurora
Variant6=ガラティア F18,Galatea
Variant7=ユーライアラス F15,Euryalus
Variant8=ナイアド F39,Naiad
Variant9=アレシューザ F38,Arethusa
Variant10=クレオパトラ F28,Cleopatra
Variant11=フィービ F42,Phoebe
Variant12=ミネルヴァ F45,Minerva
Variant13=シリウス F40,Sirius
Variant14=ジュノー F52,Juno
Variant15=アーゴノート F56,Argonaut
Variant16=ダナエ F47,Danae
Variant17=カリブディス F75,Charybdis
Variant18=ハーマイオニー F58,Hermione
Variant19=ジュピター F60,Jupiter
Variant20=バッカンテ F69,Bacchante
Variant21=アンドロメダ F57,Andromeda
Variant22=シラ F71,Scylla
Variant23=アキリーズ F12,Achilles
Variant24=ダイオミード F16,Diomede
Variant25=アポロ F70,Apollo
Variant26=アリアドネ F72,Ariadne

[rn_ff_leander_batch1]
Type=FF,フリゲート
Default=リアンダー級バッチ1,Leander
DefaultDescription=
Variant1=リアンダー F109,Leander
Variant2=エイジャックス F114,Ajax
Variant3=ガラティア F18,Galatea
Variant4=オーロラ F10,Aurora
Variant5=ナイアド F39,Naiad
Variant6=ユーライアラス F15,Euryalus
Variant7=アレシューザ F38,Arethusa
Variant8=ダイドー F104,Dido

[rn_ff_leander_batch2]
Type=FF,フリゲート
Default=リアンダー級バッチ2,Leander
DefaultDescription=
Variant1=クレオパトラ F28,Cleopatra
Variant2=フィービ F42,Phoebe
Variant3=シリウス F40,Sirius
Variant4=ミネルヴァ F45,Minerva
Variant5=アーゴノート F56,Argonaut
Variant6=ダナエ F47,Danae
Variant7=ペネロピ F127,Penelope
Variant8=ジュノー F52,Juno

[rn_ff_rothesay]
Type=FF,フリゲート
Default=ローゼシー級フリゲート,Rothesay
DefaultDescription=
Variant1=ヤーマス F101,Yarmouth
Variant2=ローゼシー F107,Rothesay
Variant3=ロンドンデリー F108,Londonderry
Variant4=リル F129,Rhyl
Variant5=プリマス F126,Plymouth
Variant6=バーウィック F115,Berwick
Variant7=ファルマス F113,Falmouth
Variant8=ロウストフト F103,Lowestoft
Variant9=ブライトン F106,Brighton

[rn_lpd_fearless]
Type=LPD,揚陸艦
Default=フィアレス級,Fearless
DefaultDescription=フィアレス級の2隻は専用設計のドック型輸送揚陸艦（LPD）であり、大型の注水可能なウェルドックに、広い飛行甲板と指揮統制設備を組み合わせている。搭載する上陸用舟艇（LCU）で車両を陸上へ輸送する。一般的な強襲揚陸艦（LHA）より多くの車両を運べるが、航空機の搭載数は大幅に少ない。
Variant1=フィアレス L10,Fearless
Variant2=イントレピッド L11,Intrepid

# submarines
[rn_ss_porpoise]
Type=SS,哨戒潜水艦
Default=ポーパス級,Porpoise
DefaultDescription=ポーパス級は1950年代後半に英国で開発されたディーゼル電気推進の攻撃・哨戒潜水艦で、全8隻が建造された。
Variant1=S01 ポーパス,Porpoise
Variant2=S02 ロクアル,Rorqual
Variant3=S03 ナーワル,Narwhal
Variant4=S04 グランパス,Grampus
Variant5=S05 フィンウェール,Finwhale
Variant6=S06 カシャロット,Cachalot
Variant7=S07 シーライオン,Sealion
Variant8=S08 ウォルラス,Walrus

[rn_ss_oberon]
Type=SS,哨戒潜水艦
Default=オベロン級,Oberon
DefaultDescription=オベロン級は、船体材料の強化と装備の改良を施したポーパス級の後継として英国で開発された、全27隻のディーゼル電気推進の攻撃・哨戒潜水艦である。優れた静粛性で知られ、冷戦期には監視、敵艦艇や潜水艦の追跡、特殊部隊の潜入と回収、対潜戦訓練などに従事した。イギリス海軍とオーストラリア海軍を含む5カ国の海軍で運用され、2000年まで現役にとどまった。
Variant1=S09 オベロン,Oberon
Variant2=S17 オセロット,Ocelot
Variant3=S10 オーディン,Odin
Variant4=S12 オリンパス,Olympus
Variant5=S14 オンスロータ,Onslaught
Variant6=S21 オニキス,Onyx
Variant7=S20 オポチュン,Opportune
Variant8=S19 オポッサム,Opossum
Variant9=S16 オラクル,Oracle
Variant10=S11 オルフェウス,Orpheus
Variant11=S13 オシリス,Osiris
Variant12=S15 オッター,Otter
Variant13=S18 オータス,Otus
#Brazil
Variant14=S20 ウマイタ,Humaitá
Variant15=S21 トネレロ,Tonelero
Variant16=S22 リアシュエロ,Riachuelo
#Chile
Variant17=S22 オブライエン,O'Brien
Variant18=S23 ハイアット,Hyatt

[rn_ssn_churchill]
Type=SSN,攻撃型原子力潜水艦
Default=チャーチル級,Churchill
DefaultDescription=チャーチル級は1970年以降に就役したイギリスの攻撃型原子力潜水艦で、全3隻が建造された。先行するヴァリアント級と設計が似ているため、同級の改良型ともみなされる。ヴァリアント級より静粛性とソナー性能が向上し、機関配置も改良された。
Variant1=S46 チャーチル,Churchill
Variant2=S48 コンカラー,Conqueror
Variant3=S50 カレイジャス,Courageous

[rn_ssn_churchill_late]
Type=SSN,攻撃型原子力潜水艦
Default=チャーチル級(後期型),Churchill
DefaultDescription=チャーチル級は1970年以降に就役したイギリスの攻撃型原子力潜水艦で、全3隻が建造された。先行するヴァリアント級と設計が似ているため、同級の改良型ともみなされる。ヴァリアント級より静粛性とソナー性能が向上し、機関配置も改良された。1980年代にはUGM-84ハープーン、タイガーフィッシュ魚雷、曳航ソナー、画期的なポンプジェット推進装置を導入する改修が施された。
Variant1=S46 チャーチル,Churchill
Variant2=S48 コンカラー,Conqueror
Variant3=S50 カレイジャス,Courageous

[rn_ssn_swiftsure]
Type=SSN,攻撃型原子力潜水艦
Default=スウィフトシュア級,Swiftsure
DefaultDescription=
Variant1=S126 スウィフトシュア,Swiftsure
Variant2=S108 サヴリン,Sovereign
Variant3=S109 サパーブ,Superb
Variant4=S104 セプター,Sceptre
Variant5=S105 スパルタン,Spartan
Variant6=S106 スプレンディッド,Splendid

[rn_ssn_trafalgar]
Type=SSN,攻撃型原子力潜水艦
Default=トラファルガー級,Trafalgar
DefaultDescription=
Variant1=S107 トラファルガー,Trafalgar
Variant2=S87 タービュレント,Turbulent
Variant3=S88 タイヤレス,Tireless
Variant4=S90 トーベイ,Torbay
Variant5=S91 トレンチャント,Trenchant
Variant6=S92 タレント,Talent
Variant7=S93 トライアンフ,Triumph

[rn_ssn_valiant]
Type=SSN,攻撃型原子力潜水艦
Default=ヴァリアント級,Valiant
DefaultDescription=ヴァリアント級は1960年代に建造されたイギリスの攻撃型原子力潜水艦で、全2隻からなる。英国初の原子力潜水艦HMSドレッドノートを大幅に改良した発展型である。機械類を浮き台に載せて振動を抑えるラフティングなど、当時としては革新的な技術を採用し、同時代の潜水艦としては高い静粛性を実現した。運用後期にはUGM-84ハープーンとタイガーフィッシュ魚雷を搭載できるよう改修された。
Variant1=S102 ヴァリアント,Valiant
Variant2=S103 ウォースパイト,Warspite

[****************************** USA ******************************]

[****************************** Soviet Union ******************************]
