
[Debug]
DisableEnemyAIPlayer=True
LoadAIScripts=True

[Language_en]
Name=AITest
[Language_cn]
Name=AITest
[Language_ru]
Name=AITest
[Language_de]
Name=AITest
[Language_es]
Name=AITest
[Language_fr]
Name=AITest
[Language_ko]
Name=AITest
[Environment]
Date=1985,6,26
Time=10,0
ConvertTimeToLocal=False
SeaState=2
Clouds=Scattered
WindDirection=SW
MapCenterLatitude=54.27
MapCenterLongitude=-26.28
LoadBackgroundData=False
[Mission]
Difficulty=0
PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
NumberOfTaskforce1Vessels=1
NumberOfTaskforce2Vessels=0
NumberOfNeutralVessels=0
NumberOfTaskforce1Submarines=0
NumberOfTaskforce2Submarines=0
NumberOfNeutralSubmarines=0
NumberOfTaskforce1Aircraft=0
NumberOfTaskforce2Aircraft=4
NumberOfNeutralAircraft=0
NumberOfTaskforce1Helicopters=0
NumberOfTaskforce2Helicopters=0
NumberOfNeutralHelicopters=0
NumberOfTaskforce1LandUnits=0
NumberOfTaskforce2LandUnits=0
NumberOfNeutralLandUnits=0
NumberOfTaskforce1Biologics=0
NumberOfTaskforce2Biologics=0
NumberOfNeutralBiologics=0
Taskforce2_NumberOfFormations=1
Taskforce2_Formation1=Taskforce2Aircraft1,Taskforce2Aircraft2,Taskforce2Aircraft3,Taskforce2Aircraft4|Group Name 2|Vic|0.1|OverrideSpawnPositions
[Taskforce1Vessel1]
Type=usn_cvn_enterprise
VariantReference=Default
StationRole=Core
MissionType=NoMission
WeaponStatus=Tight
RadarsActive=False
ActiveSonarsEnabled=False
TowedArrayDeployed=False
TowedDecoyDeployed=False
CrewSkill=Trained
Stores=Full
Damage=None
RelativePositionInNM=1512.74,0,166.65
Telegraph=2
Heading=0
CustomAirGroup=True
usn_f-14a=Squadron10,11|Squadron14,10
usn_ra-5c=Squadron4,4
usn_s-3a=Squadron6,10
usn_sh-3h=Squadron1,5
usn_f-4j=Squadron1,8
wp_mig-23a=Squadron1,8


Script1=DefaultCarrier
Script1.parameters={}




#Script1=airbase
#Script1.parameters={}

[Taskforce2Aircraft1]
Type=wp_mig-27
SquadronReference=Default
MissionType=NoMission
WeaponStatus=Tight
RadarsActive=False
CrewSkill=Trained
Stores=Full
Damage=None
RelativePositionInNM=1569.32,37000,167.97
Telegraph=3
Heading=269
Waypoints=1492.267,37000,166.2884
[Taskforce2Aircraft2]
Type=wp_mig-27
SquadronReference=Default
MissionType=NoMission
WeaponStatus=Tight
RadarsActive=False
CrewSkill=Trained
Stores=Full
Damage=None
RelativePositionInNM=1569.37,37000,168.07
Telegraph=3
Heading=269
[Taskforce2Aircraft3]
Type=wp_mig-27
SquadronReference=Default
MissionType=NoMission
WeaponStatus=Tight
RadarsActive=False
CrewSkill=Trained
Stores=Full
Damage=None
RelativePositionInNM=1569.37,37000,167.87
Telegraph=3
Heading=269
[Taskforce2Aircraft4]
Type=wp_mig-27
SquadronReference=Default
MissionType=NoMission
WeaponStatus=Tight
RadarsActive=False
CrewSkill=Trained
Stores=Full
Damage=None
RelativePositionInNM=1569.41,37000,168.17
Telegraph=3
Heading=269
[BackgroundData]
NumberOfBackgroundCityFiles=2
BackgroundCityFile1_Path=\campaigns\britishisles_cities.ini
BackgroundCityFile2_Path=\campaigns\cities.ini
NumberOfBackgroundAirportFiles=1
BackgroundAirportFile1_Path=\campaigns\airports.ini
BackgroundAirportFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundPortFiles=1
BackgroundPortFile1_Path=\campaigns\britishisles_ports.ini
BackgroundPortFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundInstallationFiles=1
BackgroundInstallationFile1_Path=\campaigns\britishisles_installations.ini
BackgroundInstallationFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundSceneryFiles=0
