
[Debug]
DisableEnemyAIPlayer=True
[Language_en]
Name=scenery_test
[Language_cn]
Name=scenery_test
[Language_ru]
Name=scenery_test
[Language_de]
Name=scenery_test
[Language_es]
Name=scenery_test
[Language_fr]
Name=scenery_test
[Language_ko]
Name=scenery_test
[Environment]
Date=1985,6,26
Time=10,0
ConvertTimeToLocal=False
SeaState=3
Clouds=Clear
WindDirection=NW
#MapCenterLatitude=54.27
#MapCenterLongitude=-26.28
MapCenterLatitude=50.662278
MapCenterLongitude=-1.591806
LoadBackgroundData=True
[Mission]
Difficulty=0
PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
NumberOfTaskforce1Vessels=1
[Taskforce1Vessel1]
Type=civ_ms_act_1
VariantReference=Default
CrewSkill=Trained
#RelativePositionInNM=1481.49,0,-214.08
RelativePositionInNM=0,0,0
Telegraph=0
Heading=0
[BackgroundData]
NumberOfBackgroundCityFiles=2
BackgroundCityFile1_Path=\campaigns\britishisles_cities.ini
BackgroundCityFile2_Path=\campaigns\cities.ini
NumberOfBackgroundAirportFiles=1
BackgroundAirportFile1_Path=\campaigns\airports.ini
BackgroundAirportFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundPortFiles=1
BackgroundPortFile1_Path=\campaigns\britishisles_ports.ini
BackgroundPortFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundInstallationFiles=1
BackgroundInstallationFile1_Path=\campaigns\britishisles_installations.ini
BackgroundInstallationFile1_DefaultGroupFile=\formations\New File.unitgroup
NumberOfBackgroundSceneryFiles=1
BackgroundSceneryFile1_Path=\campaigns\britishisles_scenery.ini
