
[Debug]
DisableEnemyAIPlayer=True
DevModeGUIScale=1
ScaleStep=0.1
LogMode=Ivan
ShowUnidentifiedUnitsIn3D=True
AllowEnemyUnitsAttackPlayer=False
AllowControlOfEnemyUnits=True
WeaponTestMode=True

[Language_en]
Name=Saved Mission
Description=Latest generated instant action mission
Taskforce1StartMessage=Barrier|Commander, enemy battlegroup is trying to break through your formation. Do not let that happen!
Taskforce1VictoryMessage=Victory!|Congratulations, commander! You are victorious!
Taskforce1DefeatMessage=Defeat|You failed to complete mission objectives, commander.
SituationMessage_1=Triggers Completed
ConditionAreaLabel=ConditionArea
ActionAreaLabel=ActionArea

[Language_ru]
Name=Сохранённая миссия
Description=Latest generated instant action mission
Taskforce1StartMessage=Barrier|Commander, enemy battlegroup is trying to break through your formation. Do not let that happen!
Taskforce1VictoryMessage=Victory!|Congratulations, commander! You are victorious!
Taskforce1DefeatMessage=Defeat|You failed to complete mission objectives, commander.
SituationMessage_1=Triggers Completed

ConditionAreaLabel=ConditionArea
ActionAreaLabel=ActionArea

[Environment]
Date=1980,8,16
Time=14,17
SeaState=2
Clouds=Clear
MapCenterLatitude=39.27
MapCenterLongitude=19.28

[Mission]
Difficulty=3
PlayerTaskforce=Taskforce1
EnemyTaskforce=Taskforce2
Taskforce1_Nation=WP
Taskforce2_Nation=NATO
Taskforce1_RulesOfEngagement=Unrestricted  //Unrestricted, Permissive, Restricted or Nonexistant
Taskforce2_RulesOfEngagement=Permissive
NumberOfTaskforce1Vessels=
NumberOfTaskforce2Vessels=
NumberOfNeutralVessels=
NumberOfTaskforce1Submarines=
NumberOfTaskforce2Submarines=
NumberOfNeutralSubmarines=0
NumberOfTaskforce1Aircraft=
NumberOfTaskforce2Aircraft=
NumberOfNeutralAircraft=
NumberOfTaskforce1Helicopters=
NumberOfTaskforce2Helicopters=
NumberOfNeutralHelicopters=0
NumberOfTaskforce1LandUnits=1 //3
NumberOfTaskforce2LandUnits=1
NumberOfNeutralLandUnits=0
NumberOfBiologic=

NumberOfTaskforce1Weapons=
NumberOfTaskforce2Weapons=0
NumberOfNeutralWeapons=0

Taskforce1_NumberOfFormations=
Taskforce1_Formation1=Taskforce1Vessel1,Taskforce1Vessel2,Taskforce1Vessel3,Taskforce1Vessel4,Taskforce1Vessel5,Taskforce1Vessel6,Taskforce1Vessel7,Taskforce1Vessel8,Taskforce1Vessel9,Taskforce1Submarine1,Taskforce1Aircraft1,Taskforce1Aircraft2,Taskforce1Aircraft3,Taskforce1Helicopter10|Battlegroup
Taskforce1_Formation1=Taskforce1Aircraft1,Taskforce1Aircraft2,Taskforce1Aircraft3|Test Flight|Vic|0.1|OverrideSpawnPositions
Taskforce2_NumberOfFormations=2
Taskforce2_Formation1=Taskforce2Vessel1,Taskforce2Vessel2,Taskforce2Vessel3|Test group|Vic|1|OverrideSpawnPositions
Taskforce2_Formation2=Taskforce2Aircraft1,Taskforce2Aircraft2,Taskforce2Aircraft3|Target Flight|Vic|0.1|OverrideSpawnPositions
NumberOfTriggers=2

[Taskforce1LandUnit1]
#Type=wp_airbase_4
Type=wp_car_ural
Type=usa_car_hmmwv
Type=usa_mlrs_m270
Type=jsdf_sam_type81
Type=wp_sa-8
Type=wp_airbase_4
#Type=wp_mbt_t-72a
#Type=usa_aaa_vulcan
#Type=usa_ifv_bradley
Type=wp_mbt_t-72a
Type=usa_mbt_abrams
Type=usa_m109a2
Type=wp_sa-13
Type=wp_large_pvo_airbase
Type=wp_airbase_2
Type=wp_airbase_3
Type=is_airbase_akureyri
Type=is_airbase_reykjavik
Type=wp_airbase_1
#VariantReference=Variant1
RadarsActive=True
WeaponStatus=Free
RelativePositionInNM=91.4,Low,-10.12
RelativePositionInNM=90,Low,-9.12
RelativePositionInNM=27.72,Low,26.26
Heading=90

[Taskforce1LandUnit2]
#Type=jsdf_sam_type81
Type=usa_ifv_bradley
Type=wp_spa_2s3
Type=usa_m109a2
VariantReference=Variant0
RadarsActive=True
#WeaponStatus=Free
RelativePositionInNM=91.2,Low,-10.2
RelativePositionInNM=90.1,Low,-9.12
RelativePositionInNM=98,Low,-9
Heading=0

[Taskforce1LandUnit3]
#Type=usa_mbt_abrams
Type=wp_sa-13
VariantReference=Variant0
RadarsActive=True
#WeaponStatus=Free
RelativePositionInNM=91.8,Low,-10.2
#RelativePositionInNM=92,Low,-9.12
RelativePositionInNM=89,Low,-9
Heading=0

[Taskforce2LandUnit1]
Type=tgt_refinery_small
Type=nato_radar
#VariantReference=Variant1
RadarsActive=True
WeaponStatus=Free
RelativePositionInNM=92,Low,-9.12
RelativePositionInNM=51.81,Low,-3.31
Heading=90

[Taskforce1Vessel1]
#SetSelected=true
Type=jmsdf_ddh_haruna
Type=usn_cg_ticonderoga
Type=usn_ff_knox
Type=jmsdf_dd_yamagumo
Type=usn_ffg_oliver_hazard_perry
Type=wp_rkr_slava
Type=wp_em_sovremenny
Type=wp_pt_libelle
Type=usn_cg_leahy
Type=ir_fab_boghammar
Type=usn_lha_tarawa
Type=wp_cv_orel
Type=usn_cv_kitty_hawk
Type=usn_ddg_coontz
Type=a_tv_schedar
Type=all_life_raft_single
Type=all_life_raft_open
Type=all_assault_raft
Type=usn_ddg_adams_early
Type=all_life_raft
Heading=0
#RelativePositionInNM=95,0,-16
RelativePositionInNM=0,0,0
VariantReference=Variant1

[Taskforce1Vessel2]
Type=wp_pt_libelle
Type=wp_rkr_slava
Type=wp_rkr_kynda
RelativePositionInNM=10,0,0

[Taskforce2Vessel1]
#Type=wp_rkr_kirov
Type=usn_ddg_coontz
RelativePositionInNM=0,0,5
Telegraph=3
Waypoints=Turn,0,20,current
StationRole=ASW
RadarsActive=True

[Taskforce2Vessel2]
Type=wp_rkr_slava
Type=wp_rkr_kynda
RelativePositionInNM=20,0,
StationRole=ASW

[Taskforce2Vessel3]
Type=usn_ddg_coontz
Type=wp_rkr_kirov
Type=usn_ddg_coontz
RelativePositionInNM=16,0,0
StationRole=ASW

[Taskforce1Submarine1]
Type=wp_ssn_victor3
Type=jmsdf_ss_yushio
Type=jmsdf_ss_uzushio
Type=jmsdf_ss_asashio
Type=a_sscv_caph
Type=wp_ssn_victor3
Type=usn_ssn_skipjack
Type=wp_ssn_alfa
#RelativePositionInNM=-2,0,0
RelativePositionInNM=-2,p,0
Waypoints=18.2488,Shallow,-19.5861|32.269,Shallow,-29.4805

[Taskforce1Submarine2]
Type=usn_ssn_sturgeon
RelativePositionInNM=5,-100,0

[Taskforce2Submarine1]
Type=usn_ssn_sturgeon
RelativePositionInNM=2,-1000,0

[Taskforce1Aircraft1]
SetSelected=True
#Type=jasdf_f-4ej
Type=wp_su-24m
Type=usaf_f-4d
Type=wp_mig-23a
Type=wp_tu-22m2
Type=usn_f-14a
Type=a_ta_navi
Type=wp_mig-23a
Type=wp_tu-22m2
Type=wp_mig-21
Type=usaf_f-5e
Type=wp_mig-23a
Type=usn_f-14a
#SquadronReference=Squadron6
CallsignIndex=1
#RelativePositionInNM=90,1000,-9
RelativePositionInNM=0,50,0
Homebase=Taskforce1LandUnit1
#RadarsActive=True
LoadoutVariant=Strike
LoadoutVariant=SEAD
#LoadoutVariant=GuidedStrike
#LoadoutVariant=ShortRangeIntercept
#WeaponStatus=Free
Heading=0
Telegraph=3
Waypoints=Turn,0,12,current
#HomeBase=Taskforce1Vessel1

[Taskforce1Aircraft2]
Type=usaf_f-4d
Type=a_ta_navi
Type=wp_tu-22m2
Type=usn_f-14a
Type=wp_mig-23a
SquadronReference=Squadron6
#LoadoutVariant=GuidedStrike
RadarsActive=True
RelativePositionInNM=0,3000,-2
RelativePositionInNM=0,cruise,0.5
Homebase=Taskforce1LandUnit1
Heading=0
Telegraph=3
Waypoints=Turn,0,20,current
HomeBase=Taskforce1Vessel1

[Taskforce1Aircraft3]
Type=usaf_f-4d
Type=a_ta_navi
Type=usn_f-14a
Type=wp_mig-23a
SquadronReference=Squadron6
LoadoutVariant=GuidedStrike
RelativePositionInNM=0,3000,-1
RelativePositionInNM=12,25000,0
Homebase=Taskforce1LandUnit1
Heading=0
Telegraph=3
Waypoints=Turn,0,20,current
HomeBase=Taskforce1Vessel1

[Taskforce2Aircraft1]
Type=wp_tu-16
Type=usn_e-2c
SquadronReference=Squadron1
RelativePositionInNM=-2,3000,5
Heading=90
Telegraph=3
Waypoints=Turn,0,20,current

[Taskforce2Aircraft2]
Type=usmc_av-8a
Type=usn_e-2c
SquadronReference=Squadron1
RelativePositionInNM=-2,3000,30.5
Heading=90
Telegraph=3
Waypoints=Turn,0,20,current

[Taskforce2Aircraft3]
Type=usn_e-2c
SquadronReference=Squadron1
RelativePositionInNM=-2,3000,29.5
Heading=90
Telegraph=3
Waypoints=Turn,0,20,current


[Taskforce2Aircraft4]
Type=usn_e-2c
Type=wp_tu-16k
SquadronReference=Squadron1
RelativePositionInNM=-2,500,5
Heading=-90
Telegraph=3
Waypoints=Turn,0,20,current


[Taskforce1Helicopter1]
#SetSelected=true
Undetectable=True
Type=usmc_ah-1t
Type=usn_ch-46
#RelativePositionInNM=90,Low,-10
RelativePositionInNM=0,20,4

[Taskforce1Helicopter2]
Type=usn_ch-46
RelativePositionInNM=10,1000,0

[Taskforce2Helicopter1]
Type=usn_ch-46
RelativePositionInNM=0,1000,10

[Taskforce2Helicopter2]
Type=usn_ch-46
RelativePositionInNM=10,1000,10

[Biologic1]
Type=bio_humpback
RelativePositionInNM=-2,-100,0

[Taskforce1Weapon1]
Type=wp_ss-n-22

RelativePositionInNM=5,500,0
Heading=-80,90,30
Velocity=523

TargetObject=Taskforce2Vessel1
#TargetGeoPosition=39.27,19.58,0
TargetPositionInNM=18,0,0

HomeBase=Taskforce1Vessel1
#Nation=Iran

#CurrentState=TerminalApproach

[-Trigger1]
Name=Orel Sunk
Condition_Type=UnitDestroyed
Condition_Units=Taskforce1Vessel1
#Condition_UnitType=Vessel

Action_Taskforce1_Message=SituationMessage_1
Action_Victory=Taskforce2

#Action_EnableTriggers=Trigger1
#Action_ReactivateTriggers=Trigger1



#Condition_Type=UnitDestroyed
#Condition_Units=Taskforce1Vessel1
#Action_Taskforce1_Message=SituationMessage_1

[Trigger1] 
Condition_Type=Time
Condition_Time=100000000
Action_Taskforce1_Message=Taskforce1StartMessage

Condition_qwe_Type=Time
Condition_qwe_Time=30

Condition_asd_Type=Time
Condition_asd_Time=10

#ConditionsCompleted=<qwe>AND<asd>

Condition_PositionNM=30,0,0
Condition_AreaRadiusNM=10
Condition_AreaLabel=ConditionArea
Condition_AreaDisplaySide=Both


Action_PositionNM=-30,0,0
Action_AreaRadiusNM=10
Action_AreaLabel=ActionAreaLabel
Action_AreaDisplaySide=Both

[Trigger2] 
#Condition_Type=UnitsInTheArea

Condition_PositionNM=30,0,0
Condition_AreaRadiusNM=10
Condition_AreaLabel=ConditionAreaLabel
Condition_AreaDisplaySide=Both

Condition_Type=TriggerCompleted
Condition_Triggers=Trigger1
Condition_Taskforce=Taskforce1

Action_Taskforce1_Message=Taskforce1VictoryMessage